export const Activos=[
    {"Cuenta":"1","Descripción":"Activo","Naturaleza":"Debe"},
    {"Cuenta":"11","Descripción":"Disponible","Naturaleza":"Debe"},
    {"Cuenta":"1105","Descripción":"Caja","Naturaleza":"Debe"},
    {"Cuenta":"110505","Descripción":"Caja general","Naturaleza":"Debe"},
    {"Cuenta":"110510","Descripción":"Cajas menores","Naturaleza":"Debe"},
    {"Cuenta":"110515","Descripción":"Moneda extranjera","Naturaleza":"Debe"},
    {"Cuenta":"1110","Descripción":"Bancos","Naturaleza":"Debe"},
    {"Cuenta":"111005","Descripción":"Moneda nacional","Naturaleza":"Debe"},
    {"Cuenta":"111010","Descripción":"Moneda extranjera","Naturaleza":"Debe"},
    {"Cuenta":"1115","Descripción":"Remesas en tránsito","Naturaleza":"Debe"},
    {"Cuenta":"111505","Descripción":"Moneda nacional","Naturaleza":"Debe"},
    {"Cuenta":"111510","Descripción":"Moneda extranjera","Naturaleza":"Debe"},
    {"Cuenta":"1120","Descripción":"Cuentas de ahorro","Naturaleza":"Debe"},
    {"Cuenta":"112005","Descripción":"Bancos","Naturaleza":"Debe"},
    {"Cuenta":"112010","Descripción":"Corporaciones de ahorro y vivienda","Naturaleza":"Debe"},
    {"Cuenta":"112015","Descripción":"Organismos cooperativos financieros","Naturaleza":"Debe"},
    {"Cuenta":"1125","Descripción":"Fondos","Naturaleza":"Debe"},
    {"Cuenta":"112505","Descripción":"Rotatorios moneda nacional","Naturaleza":"Debe"},
    {"Cuenta":"112510","Descripción":"Rotatorios moneda extranjera","Naturaleza":"Debe"},
    {"Cuenta":"112515","Descripción":"Especiales moneda nacional","Naturaleza":"Debe"},
    {"Cuenta":"112520","Descripción":"Especiales moneda extranjera","Naturaleza":"Debe"},
    {"Cuenta":"112525","Descripción":"De amortización moneda nacional","Naturaleza":"Debe"},
    {"Cuenta":"112530","Descripción":"De amortización moneda extranjera","Naturaleza":"Debe"},
    {"Cuenta":"12","Descripción":"Inversiones","Naturaleza":"Debe"},
    {"Cuenta":"1205","Descripción":"Acciones","Naturaleza":"Debe"},
    {"Cuenta":"120505","Descripción":"Agricultura, ganadería, caza y silvicultura","Naturaleza":"Debe"},
    {"Cuenta":"120510","Descripción":"Pesca","Naturaleza":"Debe"},
    {"Cuenta":"120515","Descripción":"Explotación de minas y canteras","Naturaleza":"Debe"},
    {"Cuenta":"120520","Descripción":"Industria manufacturera","Naturaleza":"Debe"},
    {"Cuenta":"120525","Descripción":"Suministro de electricidad, gas y agua","Naturaleza":"Debe"},
    {"Cuenta":"120530","Descripción":"Construcción","Naturaleza":"Debe"},
    {"Cuenta":"120535","Descripción":"Comercio al por mayor y al por menor","Naturaleza":"Debe"},
    {"Cuenta":"120540","Descripción":"Hoteles y restaurantes","Naturaleza":"Debe"},
    {"Cuenta":"120545","Descripción":"Transporte, almacenamiento y comunicaciones","Naturaleza":"Debe"},
    {"Cuenta":"120550","Descripción":"Actividad financiera","Naturaleza":"Debe"},
    {"Cuenta":"120555","Descripción":"Actividades inmobiliarias, empresariales y de alquiler","Naturaleza":"Debe"},
    {"Cuenta":"120560","Descripción":"Enseñanza","Naturaleza":"Debe"},
    {"Cuenta":"120565","Descripción":"Servicios sociales y de salud","Naturaleza":"Debe"},
    {"Cuenta":"120570","Descripción":"Otras actividades de servicios comunitarios, sociales y personales","Naturaleza":"Debe"},
    {"Cuenta":"120599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1210","Descripción":"Cuotas o partes de interés social","Naturaleza":"Debe"},
    {"Cuenta":"121005","Descripción":"Agricultura, ganadería, caza y silvicultura","Naturaleza":"Debe"},
    {"Cuenta":"121010","Descripción":"Pesca","Naturaleza":"Debe"},
    {"Cuenta":"121015","Descripción":"Explotación de minas y canteras","Naturaleza":"Debe"},
    {"Cuenta":"121020","Descripción":"Industria manufacturera","Naturaleza":"Debe"},
    {"Cuenta":"121025","Descripción":"Suministro de electricidad, gas y agua","Naturaleza":"Debe"},
    {"Cuenta":"121030","Descripción":"Construcción","Naturaleza":"Debe"},
    {"Cuenta":"121035","Descripción":"Comercio al por mayor y al por menor","Naturaleza":"Debe"},
    {"Cuenta":"121040","Descripción":"Hoteles y restaurantes","Naturaleza":"Debe"},
    {"Cuenta":"121045","Descripción":"Transporte, almacenamiento y comunicaciones","Naturaleza":"Debe"},
    {"Cuenta":"121050","Descripción":"Actividad financiera","Naturaleza":"Debe"},
    {"Cuenta":"121055","Descripción":"Actividades inmobiliarias, empresariales y de alquiler","Naturaleza":"Debe"},
    {"Cuenta":"121060","Descripción":"Enseñanza","Naturaleza":"Debe"},
    {"Cuenta":"121065","Descripción":"Servicios sociales y de salud","Naturaleza":"Debe"},
    {"Cuenta":"121070","Descripción":"Otras actividades de servicios comunitarios, sociales y personales","Naturaleza":"Debe"},
    {"Cuenta":"121099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1215","Descripción":"Bonos","Naturaleza":"Debe"},
    {"Cuenta":"121505","Descripción":"Bonos públicos moneda nacional","Naturaleza":"Debe"},
    {"Cuenta":"121510","Descripción":"Bonos públicos moneda extranjera","Naturaleza":"Debe"},
    {"Cuenta":"121515","Descripción":"Bonos ordinarios","Naturaleza":"Debe"},
    {"Cuenta":"121520","Descripción":"Bonos convertibles en acciones","Naturaleza":"Debe"},
    {"Cuenta":"121595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"1220","Descripción":"Cédulas","Naturaleza":"Debe"},
    {"Cuenta":"122005","Descripción":"Cédulas de capitalización","Naturaleza":"Debe"},
    {"Cuenta":"122010","Descripción":"Cédulas hipotecarias","Naturaleza":"Debe"},
    {"Cuenta":"122015","Descripción":"Cédulas de inversión","Naturaleza":"Debe"},
    {"Cuenta":"122095","Descripción":"Otras","Naturaleza":"Debe"},
    {"Cuenta":"1225","Descripción":"Certificados","Naturaleza":"Debe"},
    {"Cuenta":"122505","Descripción":"Certificados de depósito a término (CDT)","Naturaleza":"Debe"},
    {"Cuenta":"122510","Descripción":"Certificados de depósito de ahorro","Naturaleza":"Debe"},
    {"Cuenta":"122515","Descripción":"Certificados de ahorro de valor constante (CAVC)","Naturaleza":"Debe"},
    {"Cuenta":"122520","Descripción":"Certificados de cambio","Naturaleza":"Debe"},
    {"Cuenta":"122525","Descripción":"Certificados cafeteros valorizables","Naturaleza":"Debe"},
    {"Cuenta":"122530","Descripción":"Certificados eléctricos valorizables (CEV)","Naturaleza":"Debe"},
    {"Cuenta":"122535","Descripción":"Certificados de reembolso tributario (CERT)","Naturaleza":"Debe"},
    {"Cuenta":"122540","Descripción":"Certificados de desarrollo turístico","Naturaleza":"Debe"},
    {"Cuenta":"122545","Descripción":"Certificados de inversión forestal (CIF)","Naturaleza":"Debe"},
    {"Cuenta":"122595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"1230","Descripción":"Papeles comerciales","Naturaleza":"Debe"},
    {"Cuenta":"123005","Descripción":"Empresas comerciales","Naturaleza":"Debe"},
    {"Cuenta":"123010","Descripción":"Empresas industriales","Naturaleza":"Debe"},
    {"Cuenta":"123015","Descripción":"Empresas de servicios","Naturaleza":"Debe"},
    {"Cuenta":"1235","Descripción":"Títulos","Naturaleza":"Debe"},
    {"Cuenta":"123505","Descripción":"Títulos de desarrollo agropecuario","Naturaleza":"Debe"},
    {"Cuenta":"123510","Descripción":"Títulos canjeables por certificados de cambio","Naturaleza":"Debe"},
    {"Cuenta":"123515","Descripción":"Títulos de tesorería (TES)","Naturaleza":"Debe"},
    {"Cuenta":"123520","Descripción":"Títulos de participación","Naturaleza":"Debe"},
    {"Cuenta":"123525","Descripción":"Títulos de crédito de fomento","Naturaleza":"Debe"},
    {"Cuenta":"123530","Descripción":"Títulos financieros agroindustriales (TFA)","Naturaleza":"Debe"},
    {"Cuenta":"123535","Descripción":"Títulos de ahorro cafetero (TAC)","Naturaleza":"Debe"},
    {"Cuenta":"123540","Descripción":"Títulos de ahorro nacional (TAN)","Naturaleza":"Debe"},
    {"Cuenta":"123545","Descripción":"Títulos energéticos de rentabilidad creciente (TER)","Naturaleza":"Debe"},
    {"Cuenta":"123550","Descripción":"Títulos de ahorro educativo (TAE)","Naturaleza":"Debe"},
    {"Cuenta":"123555","Descripción":"Títulos financieros industriales y comerciales","Naturaleza":"Debe"},
    {"Cuenta":"123560","Descripción":"Tesoros","Naturaleza":"Debe"},
    {"Cuenta":"123565","Descripción":"Títulos de devolución de impuestos nacionales (TIDIS)","Naturaleza":"Debe"},
    {"Cuenta":"123570","Descripción":"Títulos inmobiliarios","Naturaleza":"Debe"},
    {"Cuenta":"123595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"1240","Descripción":"Aceptaciones bancarias o financieras","Naturaleza":"Debe"},
    {"Cuenta":"124005","Descripción":"Bancos comerciales","Naturaleza":"Debe"},
    {"Cuenta":"124010","Descripción":"Compañías de financiamiento comercial","Naturaleza":"Debe"},
    {"Cuenta":"124015","Descripción":"Corporaciones financieras","Naturaleza":"Debe"},
    {"Cuenta":"124095","Descripción":"Otras","Naturaleza":"Debe"},
    {"Cuenta":"1245","Descripción":"Derechos fiduciarios","Naturaleza":"Debe"},
    {"Cuenta":"124505","Descripción":"Fideicomisos de inversión moneda nacional","Naturaleza":"Debe"},
    {"Cuenta":"124510","Descripción":"Fideicomisos de inversión moneda extranjera","Naturaleza":"Debe"},
    {"Cuenta":"1250","Descripción":"Derechos de recompra de inversiones negociadas (repos)","Naturaleza":"Debe"},
    {"Cuenta":"125005","Descripción":"Acciones","Naturaleza":"Debe"},
    {"Cuenta":"125010","Descripción":"Cuotas o partes de interés social","Naturaleza":"Debe"},
    {"Cuenta":"125015","Descripción":"Bonos","Naturaleza":"Debe"},
    {"Cuenta":"125020","Descripción":"Cédulas","Naturaleza":"Debe"},
    {"Cuenta":"125025","Descripción":"Certificados","Naturaleza":"Debe"},
    {"Cuenta":"125030","Descripción":"Papeles comerciales","Naturaleza":"Debe"},
    {"Cuenta":"125035","Descripción":"Títulos","Naturaleza":"Debe"},
    {"Cuenta":"125040","Descripción":"Aceptaciones bancarias o financieras","Naturaleza":"Debe"},
    {"Cuenta":"125095","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"125099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1255","Descripción":"Obligatorias","Naturaleza":"Debe"},
    {"Cuenta":"125505","Descripción":"Bonos de financiamiento especial","Naturaleza":"Debe"},
    {"Cuenta":"125510","Descripción":"Bonos de financiamiento presupuestal","Naturaleza":"Debe"},
    {"Cuenta":"125515","Descripción":"Bonos para desarrollo social y seguridad interna (BDSI)","Naturaleza":"Debe"},
    {"Cuenta":"125595","Descripción":"Otras","Naturaleza":"Debe"},
    {"Cuenta":"1260","Descripción":"Cuentas en participación","Naturaleza":"Debe"},
    {"Cuenta":"126099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1295","Descripción":"Otras inversiones","Naturaleza":"Debe"},
    {"Cuenta":"129505","Descripción":"Aportes en cooperativas","Naturaleza":"Debe"},
    {"Cuenta":"129510","Descripción":"Derechos en clubes sociales","Naturaleza":"Debe"},
    {"Cuenta":"129515","Descripción":"Acciones o derechos en clubes deportivos","Naturaleza":"Debe"},
    {"Cuenta":"129520","Descripción":"Bonos en colegios","Naturaleza":"Debe"},
    {"Cuenta":"129595","Descripción":"Diversas","Naturaleza":"Debe"},
    {"Cuenta":"129599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1299","Descripción":"Provisiones","Naturaleza":"Debe"},
    {"Cuenta":"129905","Descripción":"Acciones","Naturaleza":"Debe"},
    {"Cuenta":"129910","Descripción":"Cuotas o partes de interés social","Naturaleza":"Debe"},
    {"Cuenta":"129915","Descripción":"Bonos","Naturaleza":"Debe"},
    {"Cuenta":"129920","Descripción":"Cédulas","Naturaleza":"Debe"},
    {"Cuenta":"129925","Descripción":"Certificados","Naturaleza":"Debe"},
    {"Cuenta":"129930","Descripción":"Papeles comerciales","Naturaleza":"Debe"},
    {"Cuenta":"129935","Descripción":"Títulos","Naturaleza":"Debe"},
    {"Cuenta":"129940","Descripción":"Aceptaciones bancarias o financieras","Naturaleza":"Debe"},
    {"Cuenta":"129945","Descripción":"Derechos fiduciarios","Naturaleza":"Debe"},
    {"Cuenta":"129950","Descripción":"Derechos de recompra de inversiones negociadas","Naturaleza":"Debe"},
    {"Cuenta":"129955","Descripción":"Obligatorias","Naturaleza":"Debe"},
    {"Cuenta":"129960","Descripción":"Cuentas en participación","Naturaleza":"Debe"},
    {"Cuenta":"129995","Descripción":"Otras inversiones","Naturaleza":"Debe"},
    {"Cuenta":"13","Descripción":"Deudores","Naturaleza":"Debe"},
    {"Cuenta":"1305","Descripción":"Clientes","Naturaleza":"Debe"},
    {"Cuenta":"130505","Descripción":"Nacionales","Naturaleza":"Debe"},
    {"Cuenta":"130510","Descripción":"Del exterior","Naturaleza":"Debe"},
    {"Cuenta":"130515","Descripción":"Deudores del sistema","Naturaleza":"Debe"},
    {"Cuenta":"1310","Descripción":"Cuentas corrientes comerciales","Naturaleza":"Debe"},
    {"Cuenta":"131005","Descripción":"Casa matriz","Naturaleza":"Debe"},
    {"Cuenta":"131010","Descripción":"Compañías vinculadas","Naturaleza":"Debe"},
    {"Cuenta":"131015","Descripción":"Accionistas o socios","Naturaleza":"Debe"},
    {"Cuenta":"131020","Descripción":"Particulares","Naturaleza":"Debe"},
    {"Cuenta":"131095","Descripción":"Otras","Naturaleza":"Debe"},
    {"Cuenta":"1315","Descripción":"Cuentas por cobrar a casa matriz","Naturaleza":"Debe"},
    {"Cuenta":"131505","Descripción":"Ventas","Naturaleza":"Debe"},
    {"Cuenta":"131510","Descripción":"Pagos a nombre de casa matriz","Naturaleza":"Debe"},
    {"Cuenta":"131515","Descripción":"Valores recibidos por casa matriz","Naturaleza":"Debe"},
    {"Cuenta":"131520","Descripción":"Préstamos","Naturaleza":"Debe"},
    {"Cuenta":"1320","Descripción":"Cuentas por cobrar a vinculados económicos","Naturaleza":"Debe"},
    {"Cuenta":"132005","Descripción":"Filiales","Naturaleza":"Debe"},
    {"Cuenta":"132010","Descripción":"Subsidiarias","Naturaleza":"Debe"},
    {"Cuenta":"132015","Descripción":"Sucursales","Naturaleza":"Debe"},
    {"Cuenta":"1323","Descripción":"Cuentas por cobrar a directores","Naturaleza":"Debe"},
    {"Cuenta":"1325","Descripción":"Cuentas por cobrar a socios y accionistas","Naturaleza":"Debe"},
    {"Cuenta":"132505","Descripción":"A socios","Naturaleza":"Debe"},
    {"Cuenta":"132510","Descripción":"A accionistas","Naturaleza":"Debe"},
    {"Cuenta":"1328","Descripción":"Aportes por cobrar","Naturaleza":"Debe"},
    {"Cuenta":"1330","Descripción":"Anticipos y avances","Naturaleza":"Debe"},
    {"Cuenta":"133005","Descripción":"A proveedores","Naturaleza":"Debe"},
    {"Cuenta":"133010","Descripción":"A contratistas","Naturaleza":"Debe"},
    {"Cuenta":"133015","Descripción":"A trabajadores","Naturaleza":"Debe"},
    {"Cuenta":"133020","Descripción":"A agentes","Naturaleza":"Debe"},
    {"Cuenta":"133025","Descripción":"A concesionarios","Naturaleza":"Debe"},
    {"Cuenta":"133030","Descripción":"De adjudicaciones","Naturaleza":"Debe"},
    {"Cuenta":"133095","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"133099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1332","Descripción":"Cuentas de operación conjunta","Naturaleza":"Debe"},
    {"Cuenta":"1335","Descripción":"Depósitos","Naturaleza":"Debe"},
    {"Cuenta":"133505","Descripción":"Para importaciones","Naturaleza":"Debe"},
    {"Cuenta":"133510","Descripción":"Para servicios","Naturaleza":"Debe"},
    {"Cuenta":"133515","Descripción":"Para contratos","Naturaleza":"Debe"},
    {"Cuenta":"133520","Descripción":"Para responsabilidades","Naturaleza":"Debe"},
    {"Cuenta":"133525","Descripción":"Para juicios ejecutivos","Naturaleza":"Debe"},
    {"Cuenta":"133530","Descripción":"Para adquisición de acciones, cuotas o derechos sociales","Naturaleza":"Debe"},
    {"Cuenta":"133535","Descripción":"En garantía","Naturaleza":"Debe"},
    {"Cuenta":"133595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"1340","Descripción":"Promesas de compra venta","Naturaleza":"Debe"},
    {"Cuenta":"134005","Descripción":"De bienes raíces","Naturaleza":"Debe"},
    {"Cuenta":"134010","Descripción":"De maquinaria y equipo","Naturaleza":"Debe"},
    {"Cuenta":"134015","Descripción":"De flota y equipo de transporte","Naturaleza":"Debe"},
    {"Cuenta":"134020","Descripción":"De flota y equipo aéreo","Naturaleza":"Debe"},
    {"Cuenta":"134025","Descripción":"De flota y equipo férreo","Naturaleza":"Debe"},
    {"Cuenta":"134030","Descripción":"De flota y equipo  fluvial y/o marítimo","Naturaleza":"Debe"},
    {"Cuenta":"134035","Descripción":"De semovientes","Naturaleza":"Debe"},
    {"Cuenta":"134095","Descripción":"De otros bienes","Naturaleza":"Debe"},
    {"Cuenta":"1345","Descripción":"Ingresos por cobrar","Naturaleza":"Debe"},
    {"Cuenta":"134505","Descripción":"Dividendos y/o participaciones","Naturaleza":"Debe"},
    {"Cuenta":"134510","Descripción":"Intereses","Naturaleza":"Debe"},
    {"Cuenta":"134515","Descripción":"Comisiones","Naturaleza":"Debe"},
    {"Cuenta":"134520","Descripción":"Honorarios","Naturaleza":"Debe"},
    {"Cuenta":"134525","Descripción":"Servicios","Naturaleza":"Debe"},
    {"Cuenta":"134530","Descripción":"Arrendamientos","Naturaleza":"Debe"},
    {"Cuenta":"134535","Descripción":"CERT por cobrar","Naturaleza":"Debe"},
    {"Cuenta":"134595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"1350","Descripción":"Retención sobre contratos","Naturaleza":"Debe"},
    {"Cuenta":"135005","Descripción":"De construcción","Naturaleza":"Debe"},
    {"Cuenta":"135010","Descripción":"De prestación de servicios","Naturaleza":"Debe"},
    {"Cuenta":"135095","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"1355","Descripción":"Anticipo de impuestos y contribuciones o saldos a favor","Naturaleza":"Debe"},
    {"Cuenta":"135505","Descripción":"Anticipo de impuestos de renta y complementarios","Naturaleza":"Debe"},
    {"Cuenta":"135510","Descripción":"Anticipo de impuestos de industria y comercio","Naturaleza":"Debe"},
    {"Cuenta":"135515","Descripción":"Retención en la fuente","Naturaleza":"Debe"},
    {"Cuenta":"135517","Descripción":"Impuesto a las ventas retenido","Naturaleza":"Debe"},
    {"Cuenta":"135518","Descripción":"Impuesto de industria y comercio retenido","Naturaleza":"Debe"},
    {"Cuenta":"135520","Descripción":"Sobrantes en liquidación privada de impuestos","Naturaleza":"Debe"},
    {"Cuenta":"135525","Descripción":"Contribuciones","Naturaleza":"Debe"},
    {"Cuenta":"135530","Descripción":"Impuestos descontables","Naturaleza":"Debe"},
    {"Cuenta":"135595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"1360","Descripción":"Reclamaciones","Naturaleza":"Debe"},
    {"Cuenta":"136005","Descripción":"A compañías aseguradoras","Naturaleza":"Debe"},
    {"Cuenta":"136010","Descripción":"A transportadores","Naturaleza":"Debe"},
    {"Cuenta":"136015","Descripción":"Por tiquetes aéreos","Naturaleza":"Debe"},
    {"Cuenta":"136095","Descripción":"Otras","Naturaleza":"Debe"},
    {"Cuenta":"1365","Descripción":"Cuentas por cobrar a trabajadores","Naturaleza":"Debe"},
    {"Cuenta":"136505","Descripción":"Vivienda","Naturaleza":"Debe"},
    {"Cuenta":"136510","Descripción":"Vehículos","Naturaleza":"Debe"},
    {"Cuenta":"136515","Descripción":"Educación","Naturaleza":"Debe"},
    {"Cuenta":"136520","Descripción":"Médicos, odontológicos y similares","Naturaleza":"Debe"},
    {"Cuenta":"136525","Descripción":"Calamidad doméstica","Naturaleza":"Debe"},
    {"Cuenta":"136530","Descripción":"Responsabilidades","Naturaleza":"Debe"},
    {"Cuenta":"136595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"1370","Descripción":"Préstamos a particulares","Naturaleza":"Debe"},
    {"Cuenta":"137005","Descripción":"Con garantía real","Naturaleza":"Debe"},
    {"Cuenta":"137010","Descripción":"Con garantía personal","Naturaleza":"Debe"},
    {"Cuenta":"1380","Descripción":"Deudores varios","Naturaleza":"Debe"},
    {"Cuenta":"138005","Descripción":"Depositarios","Naturaleza":"Debe"},
    {"Cuenta":"138010","Descripción":"Comisionistas de bolsas","Naturaleza":"Debe"},
    {"Cuenta":"138015","Descripción":"Fondo de inversión","Naturaleza":"Debe"},
    {"Cuenta":"138020","Descripción":"Cuentas por cobrar de terceros","Naturaleza":"Debe"},
    {"Cuenta":"138025","Descripción":"Pagos por cuenta de terceros","Naturaleza":"Debe"},
    {"Cuenta":"138030","Descripción":"Fondos de inversión social","Naturaleza":"Debe"},
    {"Cuenta":"138095","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"1385","Descripción":"Derechos de recompra de cartera negociada","Naturaleza":"Debe"},
    {"Cuenta":"1390","Descripción":"Deudas de difícil cobro","Naturaleza":"Debe"},
    {"Cuenta":"1399","Descripción":"Provisiones","Naturaleza":"Debe"},
    {"Cuenta":"139905","Descripción":"Clientes","Naturaleza":"Debe"},
    {"Cuenta":"139910","Descripción":"Cuentas corrientes comerciales","Naturaleza":"Debe"},
    {"Cuenta":"139915","Descripción":"Cuentas por cobrar a casa matriz","Naturaleza":"Debe"},
    {"Cuenta":"139920","Descripción":"Cuentas por cobrar a vinculados económicos","Naturaleza":"Debe"},
    {"Cuenta":"139925","Descripción":"Cuentas por cobrar a socios y accionistas","Naturaleza":"Debe"},
    {"Cuenta":"139930","Descripción":"Anticipos y avances","Naturaleza":"Debe"},
    {"Cuenta":"139932","Descripción":"Cuentas de operación conjunta","Naturaleza":"Debe"},
    {"Cuenta":"139935","Descripción":"Depósitos","Naturaleza":"Debe"},
    {"Cuenta":"139940","Descripción":"Promesas de compraventa","Naturaleza":"Debe"},
    {"Cuenta":"139945","Descripción":"Ingresos por cobrar","Naturaleza":"Debe"},
    {"Cuenta":"139950","Descripción":"Retención sobre contratos","Naturaleza":"Debe"},
    {"Cuenta":"139955","Descripción":"Reclamaciones","Naturaleza":"Debe"},
    {"Cuenta":"139960","Descripción":"Cuentas por cobrar a trabajadores","Naturaleza":"Debe"},
    {"Cuenta":"139965","Descripción":"Préstamos a particulares","Naturaleza":"Debe"},
    {"Cuenta":"139975","Descripción":"Deudores varios","Naturaleza":"Debe"},
    {"Cuenta":"139980","Descripción":"Derechos de recompra de cartera negociada","Naturaleza":"Debe"},
    {"Cuenta":"14","Descripción":"Inventarios","Naturaleza":"Debe"},
    {"Cuenta":"1405","Descripción":"Materias primas","Naturaleza":"Debe"},
    {"Cuenta":"140599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1410","Descripción":"Productos en proceso","Naturaleza":"Debe"},
    {"Cuenta":"141099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1415","Descripción":"Obras de construcción en curso","Naturaleza":"Debe"},
    {"Cuenta":"141599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1417","Descripción":"Obras de urbanismo","Naturaleza":"Debe"},
    {"Cuenta":"141799","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1420","Descripción":"Contratos en ejecución","Naturaleza":"Debe"},
    {"Cuenta":"142099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1425","Descripción":"Cultivos en desarrollo","Naturaleza":"Debe"},
    {"Cuenta":"142599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1428","Descripción":"Plantaciones agrícolas","Naturaleza":"Debe"},
    {"Cuenta":"142899","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1430","Descripción":"Productos terminados","Naturaleza":"Debe"},
    {"Cuenta":"143005","Descripción":"Productos manufacturados","Naturaleza":"Debe"},
    {"Cuenta":"143010","Descripción":"Productos extraídos y/o procesados","Naturaleza":"Debe"},
    {"Cuenta":"143015","Descripción":"Productos agrícolas y forestales","Naturaleza":"Debe"},
    {"Cuenta":"143020","Descripción":"Subproductos","Naturaleza":"Debe"},
    {"Cuenta":"143025","Descripción":"Productos de pesca","Naturaleza":"Debe"},
    {"Cuenta":"143099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1435","Descripción":"Mercancías no fabricadas por la empresa","Naturaleza":"Debe"},
    {"Cuenta":"143599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1440","Descripción":"Bienes raíces para la venta","Naturaleza":"Debe"},
    {"Cuenta":"144099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1445","Descripción":"Semovientes","Naturaleza":"Debe"},
    {"Cuenta":"144599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1450","Descripción":"Terrenos","Naturaleza":"Debe"},
    {"Cuenta":"145005","Descripción":"Por urbanizar","Naturaleza":"Debe"},
    {"Cuenta":"145010","Descripción":"Urbanizados por construir","Naturaleza":"Debe"},
    {"Cuenta":"145099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1455","Descripción":"Materiales, repuestos y accesorios","Naturaleza":"Debe"},
    {"Cuenta":"145599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1460","Descripción":"Envases y empaques","Naturaleza":"Debe"},
    {"Cuenta":"146099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1465","Descripción":"Inventarios en tránsito","Naturaleza":"Debe"},
    {"Cuenta":"146599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1499","Descripción":"Provisiones","Naturaleza":"Debe"},
    {"Cuenta":"149905","Descripción":"Para obsolescencia","Naturaleza":"Debe"},
    {"Cuenta":"149910","Descripción":"Para diferencia de inventario físico","Naturaleza":"Debe"},
    {"Cuenta":"149915","Descripción":"Para pérdidas de inventarios","Naturaleza":"Debe"},
    {"Cuenta":"149920","Descripción":"Lifo","Naturaleza":"Debe"},
    {"Cuenta":"15","Descripción":"Propiedades, planta y equipo","Naturaleza":"Debe"},
    {"Cuenta":"1504","Descripción":"Terrenos","Naturaleza":"Debe"},
    {"Cuenta":"150405","Descripción":"Urbanos","Naturaleza":"Debe"},
    {"Cuenta":"150410","Descripción":"Rurales","Naturaleza":"Debe"},
    {"Cuenta":"150499","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1506","Descripción":"Materiales proyectos petroleros","Naturaleza":"Debe"},
    {"Cuenta":"150605","Descripción":"Tuberías y equipo","Naturaleza":"Debe"},
    {"Cuenta":"150610","Descripción":"Costos de importación materiales","Naturaleza":"Debe"},
    {"Cuenta":"150615","Descripción":"Proyectos de construcción","Naturaleza":"Debe"},
    {"Cuenta":"150699","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1508","Descripción":"Construcciones en curso","Naturaleza":"Debe"},
    {"Cuenta":"150805","Descripción":"Construcciones y edificaciones","Naturaleza":"Debe"},
    {"Cuenta":"150810","Descripción":"Acueductos, plantas y redes","Naturaleza":"Debe"},
    {"Cuenta":"150815","Descripción":"Vías de comunicación","Naturaleza":"Debe"},
    {"Cuenta":"150820","Descripción":"Pozos artesianos","Naturaleza":"Debe"},
    {"Cuenta":"150825","Descripción":"Proyectos de exploración","Naturaleza":"Debe"},
    {"Cuenta":"150830","Descripción":"Proyectos de desarrollo","Naturaleza":"Debe"},
    {"Cuenta":"150899","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1512","Descripción":"Maquinaria y equipos en montaje","Naturaleza":"Debe"},
    {"Cuenta":"151205","Descripción":"Maquinaria y equipo","Naturaleza":"Debe"},
    {"Cuenta":"151210","Descripción":"Equipo de oficina","Naturaleza":"Debe"},
    {"Cuenta":"151215","Descripción":"Equipo de computación y comunicación","Naturaleza":"Debe"},
    {"Cuenta":"151220","Descripción":"Equipo médico-científico","Naturaleza":"Debe"},
    {"Cuenta":"151225","Descripción":"Equipo de hoteles y restaurantes","Naturaleza":"Debe"},
    {"Cuenta":"151230","Descripción":"Flota y equipo de transporte","Naturaleza":"Debe"},
    {"Cuenta":"151235","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Debe"},
    {"Cuenta":"151240","Descripción":"Flota y equipo aéreo","Naturaleza":"Debe"},
    {"Cuenta":"151245","Descripción":"Flota y equipo férreo","Naturaleza":"Debe"},
    {"Cuenta":"151250","Descripción":"Plantas y redes","Naturaleza":"Debe"},
    {"Cuenta":"151299","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1516","Descripción":"Construcciones y edificaciones","Naturaleza":"Debe"},
    {"Cuenta":"151605","Descripción":"Edificios","Naturaleza":"Debe"},
    {"Cuenta":"151610","Descripción":"Oficinas","Naturaleza":"Debe"},
    {"Cuenta":"151615","Descripción":"Almacenes","Naturaleza":"Debe"},
    {"Cuenta":"151620","Descripción":"Fábricas y plantas industriales","Naturaleza":"Debe"},
    {"Cuenta":"151625","Descripción":"Salas de exhibición y ventas","Naturaleza":"Debe"},
    {"Cuenta":"151630","Descripción":"Cafetería y casinos","Naturaleza":"Debe"},
    {"Cuenta":"151635","Descripción":"Silos","Naturaleza":"Debe"},
    {"Cuenta":"151640","Descripción":"Invernaderos","Naturaleza":"Debe"},
    {"Cuenta":"151645","Descripción":"Casetas y campamentos","Naturaleza":"Debe"},
    {"Cuenta":"151650","Descripción":"Instalaciones agropecuarias","Naturaleza":"Debe"},
    {"Cuenta":"151655","Descripción":"Viviendas para empleados y obreros","Naturaleza":"Debe"},
    {"Cuenta":"151660","Descripción":"Terminal de buses y taxis","Naturaleza":"Debe"},
    {"Cuenta":"151663","Descripción":"Terminal marítimo","Naturaleza":"Debe"},
    {"Cuenta":"151665","Descripción":"Terminal férreo","Naturaleza":"Debe"},
    {"Cuenta":"151670","Descripción":"Parqueaderos, garajes y depósitos","Naturaleza":"Debe"},
    {"Cuenta":"151675","Descripción":"Hangares","Naturaleza":"Debe"},
    {"Cuenta":"151680","Descripción":"Bodegas","Naturaleza":"Debe"},
    {"Cuenta":"151695","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"151699","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1520","Descripción":"Maquinaria y equipo","Naturaleza":"Debe"},
    {"Cuenta":"152099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1524","Descripción":"Equipo de oficina","Naturaleza":"Debe"},
    {"Cuenta":"152405","Descripción":"Muebles y enseres","Naturaleza":"Debe"},
    {"Cuenta":"152410","Descripción":"Equipos","Naturaleza":"Debe"},
    {"Cuenta":"152495","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"152499","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1528","Descripción":"Equipo de computación y comunicación","Naturaleza":"Debe"},
    {"Cuenta":"152805","Descripción":"Equipos de procesamiento de datos","Naturaleza":"Debe"},
    {"Cuenta":"152810","Descripción":"Equipos de telecomunicaciones","Naturaleza":"Debe"},
    {"Cuenta":"152815","Descripción":"Equipos de radio","Naturaleza":"Debe"},
    {"Cuenta":"152820","Descripción":"Satélites y antenas","Naturaleza":"Debe"},
    {"Cuenta":"152825","Descripción":"Líneas telefónicas","Naturaleza":"Debe"},
    {"Cuenta":"152895","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"152899","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1532","Descripción":"Equipo médico-científico","Naturaleza":"Debe"},
    {"Cuenta":"153205","Descripción":"Médico","Naturaleza":"Debe"},
    {"Cuenta":"153210","Descripción":"Odontológico","Naturaleza":"Debe"},
    {"Cuenta":"153215","Descripción":"Laboratorio","Naturaleza":"Debe"},
    {"Cuenta":"153220","Descripción":"Instrumental","Naturaleza":"Debe"},
    {"Cuenta":"153295","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"153299","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1536","Descripción":"Equipo de hoteles y restaurantes","Naturaleza":"Debe"},
    {"Cuenta":"153605","Descripción":"De habitaciones","Naturaleza":"Debe"},
    {"Cuenta":"153610","Descripción":"De comestibles y bebidas","Naturaleza":"Debe"},
    {"Cuenta":"153695","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"153699","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1540","Descripción":"Flota y equipo de transporte","Naturaleza":"Debe"},
    {"Cuenta":"154005","Descripción":"Autos, camionetas y camperos","Naturaleza":"Debe"},
    {"Cuenta":"154008","Descripción":"Camiones, volquetas y furgones","Naturaleza":"Debe"},
    {"Cuenta":"154010","Descripción":"Tractomulas y remolques","Naturaleza":"Debe"},
    {"Cuenta":"154015","Descripción":"Buses y busetas","Naturaleza":"Debe"},
    {"Cuenta":"154017","Descripción":"Recolectores y contenedores","Naturaleza":"Debe"},
    {"Cuenta":"154020","Descripción":"Montacargas","Naturaleza":"Debe"},
    {"Cuenta":"154025","Descripción":"Palas y grúas","Naturaleza":"Debe"},
    {"Cuenta":"154030","Descripción":"Motocicletas","Naturaleza":"Debe"},
    {"Cuenta":"154035","Descripción":"Bicicletas","Naturaleza":"Debe"},
    {"Cuenta":"154040","Descripción":"Estibas y carretas","Naturaleza":"Debe"},
    {"Cuenta":"154045","Descripción":"Bandas transportadoras","Naturaleza":"Debe"},
    {"Cuenta":"154095","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"154099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1544","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Debe"},
    {"Cuenta":"154405","Descripción":"Buques","Naturaleza":"Debe"},
    {"Cuenta":"154410","Descripción":"Lanchas","Naturaleza":"Debe"},
    {"Cuenta":"154415","Descripción":"Remolcadoras","Naturaleza":"Debe"},
    {"Cuenta":"154420","Descripción":"Botes","Naturaleza":"Debe"},
    {"Cuenta":"154425","Descripción":"Boyas","Naturaleza":"Debe"},
    {"Cuenta":"154430","Descripción":"Amarres","Naturaleza":"Debe"},
    {"Cuenta":"154435","Descripción":"Contenedores y chasises","Naturaleza":"Debe"},
    {"Cuenta":"154440","Descripción":"Gabarras","Naturaleza":"Debe"},
    {"Cuenta":"154495","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"154499","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1548","Descripción":"Flota y equipo aéreo","Naturaleza":"Debe"},
    {"Cuenta":"154805","Descripción":"Aviones","Naturaleza":"Debe"},
    {"Cuenta":"154810","Descripción":"Avionetas","Naturaleza":"Debe"},
    {"Cuenta":"154815","Descripción":"Helicópteros","Naturaleza":"Debe"},
    {"Cuenta":"154820","Descripción":"Turbinas y motores","Naturaleza":"Debe"},
    {"Cuenta":"154825","Descripción":"Manuales de entrenamiento personal técnico","Naturaleza":"Debe"},
    {"Cuenta":"154830","Descripción":"Equipos de vuelo","Naturaleza":"Debe"},
    {"Cuenta":"154895","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"154899","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1552","Descripción":"Flota y equipo férreo","Naturaleza":"Debe"},
    {"Cuenta":"155205","Descripción":"Locomotoras","Naturaleza":"Debe"},
    {"Cuenta":"155210","Descripción":"Vagones","Naturaleza":"Debe"},
    {"Cuenta":"155215","Descripción":"Redes férreas","Naturaleza":"Debe"},
    {"Cuenta":"155295","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"155299","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1556","Descripción":"Acueductos, plantas y redes","Naturaleza":"Debe"},
    {"Cuenta":"155605","Descripción":"Instalaciones para agua y energía","Naturaleza":"Debe"},
    {"Cuenta":"155610","Descripción":"Acueducto, acequias y canalizaciones","Naturaleza":"Debe"},
    {"Cuenta":"155615","Descripción":"Plantas de generación hidráulica","Naturaleza":"Debe"},
    {"Cuenta":"155620","Descripción":"Plantas de generación térmica","Naturaleza":"Debe"},
    {"Cuenta":"155625","Descripción":"Plantas de generación a gas","Naturaleza":"Debe"},
    {"Cuenta":"155628","Descripción":"Plantas de generación diesel, gasolina y petróleo","Naturaleza":"Debe"},
    {"Cuenta":"155630","Descripción":"Plantas de distribución","Naturaleza":"Debe"},
    {"Cuenta":"155635","Descripción":"Plantas de transmisión y subestaciones","Naturaleza":"Debe"},
    {"Cuenta":"155640","Descripción":"Oleoductos","Naturaleza":"Debe"},
    {"Cuenta":"155645","Descripción":"Gasoductos","Naturaleza":"Debe"},
    {"Cuenta":"155647","Descripción":"Poliductos","Naturaleza":"Debe"},
    {"Cuenta":"155650","Descripción":"Redes de distribución","Naturaleza":"Debe"},
    {"Cuenta":"155655","Descripción":"Plantas de tratamiento","Naturaleza":"Debe"},
    {"Cuenta":"155660","Descripción":"Redes de recolección de aguas negras","Naturaleza":"Debe"},
    {"Cuenta":"155665","Descripción":"Instalaciones y equipo de bombeo","Naturaleza":"Debe"},
    {"Cuenta":"155670","Descripción":"Redes de distribución de vapor","Naturaleza":"Debe"},
    {"Cuenta":"155675","Descripción":"Redes de aire","Naturaleza":"Debe"},
    {"Cuenta":"155680","Descripción":"Redes alimentación de gas","Naturaleza":"Debe"},
    {"Cuenta":"155682","Descripción":"Redes externas de telefonía","Naturaleza":"Debe"},
    {"Cuenta":"155685","Descripción":"Plantas deshidratadoras","Naturaleza":"Debe"},
    {"Cuenta":"155695","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"155699","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1560","Descripción":"Armamento de vigilancia","Naturaleza":"Debe"},
    {"Cuenta":"156099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1562","Descripción":"Envases y empaques","Naturaleza":"Debe"},
    {"Cuenta":"156299","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1564","Descripción":"Plantaciones agrícolas y forestales","Naturaleza":"Debe"},
    {"Cuenta":"156405","Descripción":"Cultivos en desarrollo","Naturaleza":"Debe"},
    {"Cuenta":"156410","Descripción":"Cultivos amortizables","Naturaleza":"Debe"},
    {"Cuenta":"156499","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1568","Descripción":"Vías de comunicación","Naturaleza":"Debe"},
    {"Cuenta":"156805","Descripción":"Pavimentación y patios","Naturaleza":"Debe"},
    {"Cuenta":"156810","Descripción":"Vías","Naturaleza":"Debe"},
    {"Cuenta":"156815","Descripción":"Puentes","Naturaleza":"Debe"},
    {"Cuenta":"156820","Descripción":"Calles","Naturaleza":"Debe"},
    {"Cuenta":"156825","Descripción":"Aeródromos","Naturaleza":"Debe"},
    {"Cuenta":"156895","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"156899","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1572","Descripción":"Minas y canteras","Naturaleza":"Debe"},
    {"Cuenta":"157205","Descripción":"Minas","Naturaleza":"Debe"},
    {"Cuenta":"157210","Descripción":"Canteras","Naturaleza":"Debe"},
    {"Cuenta":"157299","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1576","Descripción":"Pozos artesianos","Naturaleza":"Debe"},
    {"Cuenta":"157699","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1580","Descripción":"Yacimientos","Naturaleza":"Debe"},
    {"Cuenta":"158099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1584","Descripción":"Semovientes","Naturaleza":"Debe"},
    {"Cuenta":"158499","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1588","Descripción":"Propiedades, planta y equipo en tránsito","Naturaleza":"Debe"},
    {"Cuenta":"158805","Descripción":"Maquinaria y equipo","Naturaleza":"Debe"},
    {"Cuenta":"158810","Descripción":"Equipo de oficina","Naturaleza":"Debe"},
    {"Cuenta":"158815","Descripción":"Equipo de computación y comunicación","Naturaleza":"Debe"},
    {"Cuenta":"158820","Descripción":"Equipo médico-científico","Naturaleza":"Debe"},
    {"Cuenta":"158825","Descripción":"Equipo de hoteles y restaurantes","Naturaleza":"Debe"},
    {"Cuenta":"158830","Descripción":"Flota y equipo de transporte","Naturaleza":"Debe"},
    {"Cuenta":"158835","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Debe"},
    {"Cuenta":"158840","Descripción":"Flota y equipo aéreo","Naturaleza":"Debe"},
    {"Cuenta":"158845","Descripción":"Flota y equipo férreo","Naturaleza":"Debe"},
    {"Cuenta":"158850","Descripción":"Plantas y redes","Naturaleza":"Debe"},
    {"Cuenta":"158855","Descripción":"Armamento de vigilancia","Naturaleza":"Debe"},
    {"Cuenta":"158860","Descripción":"Semovientes","Naturaleza":"Debe"},
    {"Cuenta":"158865","Descripción":"Envases y empaques","Naturaleza":"Debe"},
    {"Cuenta":"158899","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1592","Descripción":"Depreciación acumulada","Naturaleza":"Debe"},
    {"Cuenta":"159205","Descripción":"Construcciones y edificaciones","Naturaleza":"Debe"},
    {"Cuenta":"159210","Descripción":"Maquinaria y equipo","Naturaleza":"Debe"},
    {"Cuenta":"159215","Descripción":"Equipo de oficina","Naturaleza":"Debe"},
    {"Cuenta":"159220","Descripción":"Equipo de computación y comunicación","Naturaleza":"Debe"},
    {"Cuenta":"159225","Descripción":"Equipo médico-científico","Naturaleza":"Debe"},
    {"Cuenta":"159230","Descripción":"Equipo de hoteles y restaurantes","Naturaleza":"Debe"},
    {"Cuenta":"159235","Descripción":"Flota y equipo de transporte","Naturaleza":"Debe"},
    {"Cuenta":"159240","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Debe"},
    {"Cuenta":"159245","Descripción":"Flota y equipo aéreo","Naturaleza":"Debe"},
    {"Cuenta":"159250","Descripción":"Flota y equipo férreo","Naturaleza":"Debe"},
    {"Cuenta":"159255","Descripción":"Acueductos, plantas y redes","Naturaleza":"Debe"},
    {"Cuenta":"159260","Descripción":"Armamento de vigilancia","Naturaleza":"Debe"},
    {"Cuenta":"159265","Descripción":"Envases y empaques","Naturaleza":"Debe"},
    {"Cuenta":"159299","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1596","Descripción":"Depreciación diferida","Naturaleza":"Debe"},
    {"Cuenta":"159605","Descripción":"Exceso fiscal sobre la contable","Naturaleza":"Debe"},
    {"Cuenta":"159610","Descripción":"Defecto fiscal sobre la contable (CR)","Naturaleza":"Debe"},
    {"Cuenta":"159699","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1597","Descripción":"Amortización acumulada","Naturaleza":"Debe"},
    {"Cuenta":"159705","Descripción":"Plantaciones agrícolas y forestales","Naturaleza":"Debe"},
    {"Cuenta":"159710","Descripción":"Vías de comunicación","Naturaleza":"Debe"},
    {"Cuenta":"159715","Descripción":"Semovientes","Naturaleza":"Debe"},
    {"Cuenta":"159799","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1598","Descripción":"Agotamiento acumulado","Naturaleza":"Debe"},
    {"Cuenta":"159805","Descripción":"Minas y canteras","Naturaleza":"Debe"},
    {"Cuenta":"159815","Descripción":"Pozos artesianos","Naturaleza":"Debe"},
    {"Cuenta":"159820","Descripción":"Yacimientos","Naturaleza":"Debe"},
    {"Cuenta":"159899","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1599","Descripción":"Provisiones","Naturaleza":"Debe"},
    {"Cuenta":"159904","Descripción":"Terrenos","Naturaleza":"Debe"},
    {"Cuenta":"159906","Descripción":"Materiales proyectos petroleros","Naturaleza":"Debe"},
    {"Cuenta":"159908","Descripción":"Construcciones en curso","Naturaleza":"Debe"},
    {"Cuenta":"159912","Descripción":"Maquinaria en montaje","Naturaleza":"Debe"},
    {"Cuenta":"159916","Descripción":"Construcciones y edificaciones","Naturaleza":"Debe"},
    {"Cuenta":"159920","Descripción":"Maquinaria y equipo","Naturaleza":"Debe"},
    {"Cuenta":"159924","Descripción":"Equipo de oficina","Naturaleza":"Debe"},
    {"Cuenta":"159928","Descripción":"Equipo de computación y comunicación","Naturaleza":"Debe"},
    {"Cuenta":"159932","Descripción":"Equipo médico-científico","Naturaleza":"Debe"},
    {"Cuenta":"159936","Descripción":"Equipo de hoteles y restaurantes","Naturaleza":"Debe"},
    {"Cuenta":"159940","Descripción":"Flota y equipo de transporte","Naturaleza":"Debe"},
    {"Cuenta":"159944","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Debe"},
    {"Cuenta":"159948","Descripción":"Flota y equipo aéreo","Naturaleza":"Debe"},
    {"Cuenta":"159952","Descripción":"Flota y equipo férreo","Naturaleza":"Debe"},
    {"Cuenta":"159956","Descripción":"Acueductos, plantas y redes","Naturaleza":"Debe"},
    {"Cuenta":"159960","Descripción":"Armamento de vigilancia","Naturaleza":"Debe"},
    {"Cuenta":"159962","Descripción":"Envases y empaques","Naturaleza":"Debe"},
    {"Cuenta":"159964","Descripción":"Plantaciones agrícolas y forestales","Naturaleza":"Debe"},
    {"Cuenta":"159968","Descripción":"Vías de comunicación","Naturaleza":"Debe"},
    {"Cuenta":"159972","Descripción":"Minas y canteras","Naturaleza":"Debe"},
    {"Cuenta":"159980","Descripción":"Pozos artesianos","Naturaleza":"Debe"},
    {"Cuenta":"159984","Descripción":"Yacimientos","Naturaleza":"Debe"},
    {"Cuenta":"159988","Descripción":"Semovientes","Naturaleza":"Debe"},
    {"Cuenta":"159992","Descripción":"Propiedades, planta y equipo en tránsito","Naturaleza":"Debe"},
    {"Cuenta":"16","Descripción":"Intangibles","Naturaleza":"Debe"},
    {"Cuenta":"1605","Descripción":"Crédito mercantil","Naturaleza":"Debe"},
    {"Cuenta":"160505","Descripción":"Formado o estimado","Naturaleza":"Debe"},
    {"Cuenta":"160510","Descripción":"Adquirido o comprado","Naturaleza":"Debe"},
    {"Cuenta":"160599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1610","Descripción":"Marcas","Naturaleza":"Debe"},
    {"Cuenta":"161005","Descripción":"Adquiridas","Naturaleza":"Debe"},
    {"Cuenta":"161010","Descripción":"Formadas","Naturaleza":"Debe"},
    {"Cuenta":"161099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1615","Descripción":"Patentes","Naturaleza":"Debe"},
    {"Cuenta":"161505","Descripción":"Adquiridas","Naturaleza":"Debe"},
    {"Cuenta":"161510","Descripción":"Formadas","Naturaleza":"Debe"},
    {"Cuenta":"161599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1620","Descripción":"Concesiones y franquicias","Naturaleza":"Debe"},
    {"Cuenta":"162005","Descripción":"Concesiones","Naturaleza":"Debe"},
    {"Cuenta":"162010","Descripción":"Franquicias","Naturaleza":"Debe"},
    {"Cuenta":"162099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1625","Descripción":"Derechos","Naturaleza":"Debe"},
    {"Cuenta":"162505","Descripción":"Derechos de autor","Naturaleza":"Debe"},
    {"Cuenta":"162510","Descripción":"Puesto de bolsa","Naturaleza":"Debe"},
    {"Cuenta":"162515","Descripción":"En fideicomisos inmobiliarios","Naturaleza":"Debe"},
    {"Cuenta":"162520","Descripción":"En fideicomisos de garantía","Naturaleza":"Debe"},
    {"Cuenta":"162525","Descripción":"En fideicomisos de administración","Naturaleza":"Debe"},
    {"Cuenta":"162530","Descripción":"De exhibición - películas","Naturaleza":"Debe"},
    {"Cuenta":"162535","Descripción":"En bienes recibidos en arrendamiento financiero (leasing)","Naturaleza":"Debe"},
    {"Cuenta":"162595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"162599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1630","Descripción":"Know how","Naturaleza":"Debe"},
    {"Cuenta":"163099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1635","Descripción":"Licencias","Naturaleza":"Debe"},
    {"Cuenta":"163599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1698","Descripción":"Depreciación y/o amortización acumulada","Naturaleza":"Debe"},
    {"Cuenta":"169805","Descripción":"Crédito mercantil","Naturaleza":"Debe"},
    {"Cuenta":"169810","Descripción":"Marcas","Naturaleza":"Debe"},
    {"Cuenta":"169815","Descripción":"Patentes","Naturaleza":"Debe"},
    {"Cuenta":"169820","Descripción":"Concesiones y franquicias","Naturaleza":"Debe"},
    {"Cuenta":"169830","Descripción":"Derechos","Naturaleza":"Debe"},
    {"Cuenta":"169835","Descripción":"Know how","Naturaleza":"Debe"},
    {"Cuenta":"169840","Descripción":"Licencias","Naturaleza":"Debe"},
    {"Cuenta":"169899","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1699","Descripción":"Provisiones","Naturaleza":"Debe"},
    {"Cuenta":"17","Descripción":"Diferidos","Naturaleza":"Debe"},
    {"Cuenta":"1705","Descripción":"Gastos pagados por anticipado","Naturaleza":"Debe"},
    {"Cuenta":"170505","Descripción":"Intereses","Naturaleza":"Debe"},
    {"Cuenta":"170510","Descripción":"Honorarios","Naturaleza":"Debe"},
    {"Cuenta":"170515","Descripción":"Comisiones","Naturaleza":"Debe"},
    {"Cuenta":"170520","Descripción":"Seguros y fianzas","Naturaleza":"Debe"},
    {"Cuenta":"170525","Descripción":"Arrendamientos","Naturaleza":"Debe"},
    {"Cuenta":"170530","Descripción":"Bodegajes","Naturaleza":"Debe"},
    {"Cuenta":"170535","Descripción":"Mantenimiento equipos","Naturaleza":"Debe"},
    {"Cuenta":"170540","Descripción":"Servicios","Naturaleza":"Debe"},
    {"Cuenta":"170545","Descripción":"Suscripciones","Naturaleza":"Debe"},
    {"Cuenta":"170595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"1710","Descripción":"Cargos diferidos","Naturaleza":"Debe"},
    {"Cuenta":"171004","Descripción":"Organización y preoperativos","Naturaleza":"Debe"},
    {"Cuenta":"171008","Descripción":"Remodelaciones","Naturaleza":"Debe"},
    {"Cuenta":"171012","Descripción":"Estudios, investigaciones y proyectos","Naturaleza":"Debe"},
    {"Cuenta":"171016","Descripción":"Programas para computador (software)","Naturaleza":"Debe"},
    {"Cuenta":"171020","Descripción":"Útiles y papelería","Naturaleza":"Debe"},
    {"Cuenta":"171024","Descripción":"Mejoras a propiedades ajenas","Naturaleza":"Debe"},
    {"Cuenta":"171028","Descripción":"Contribuciones y afiliaciones","Naturaleza":"Debe"},
    {"Cuenta":"171032","Descripción":"Entrenamiento de personal","Naturaleza":"Debe"},
    {"Cuenta":"171036","Descripción":"Ferias y exposiciones","Naturaleza":"Debe"},
    {"Cuenta":"171040","Descripción":"Licencias","Naturaleza":"Debe"},
    {"Cuenta":"171044","Descripción":"Publicidad, propaganda y promoción","Naturaleza":"Debe"},
    {"Cuenta":"171048","Descripción":"Elementos de aseo y cafetería","Naturaleza":"Debe"},
    {"Cuenta":"171052","Descripción":"Moldes y troqueles","Naturaleza":"Debe"},
    {"Cuenta":"171056","Descripción":"Instrumental quirúrgico","Naturaleza":"Debe"},
    {"Cuenta":"171060","Descripción":"Dotación y suministro a trabajadores","Naturaleza":"Debe"},
    {"Cuenta":"171064","Descripción":"Elementos de ropería y lencería","Naturaleza":"Debe"},
    {"Cuenta":"171068","Descripción":"Loza y cristalería","Naturaleza":"Debe"},
    {"Cuenta":"171069","Descripción":"Platería","Naturaleza":"Debe"},
    {"Cuenta":"171070","Descripción":"Cubiertería","Naturaleza":"Debe"},
    {"Cuenta":"171076","Descripción":"Impuesto de renta diferido ?débitos? por diferencias temporales","Naturaleza":"Debe"},
    {"Cuenta":"171080","Descripción":"Concursos y licitaciones","Naturaleza":"Debe"},
    {"Cuenta":"171095","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"171099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1715","Descripción":"Costos de exploración por amortizar","Naturaleza":"Debe"},
    {"Cuenta":"171505","Descripción":"Pozos secos","Naturaleza":"Debe"},
    {"Cuenta":"171510","Descripción":"Pozos no comerciales","Naturaleza":"Debe"},
    {"Cuenta":"171515","Descripción":"Otros costos de exploración","Naturaleza":"Debe"},
    {"Cuenta":"171599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1720","Descripción":"Costos de explotación y desarrollo","Naturaleza":"Debe"},
    {"Cuenta":"172005","Descripción":"Perforación y explotación","Naturaleza":"Debe"},
    {"Cuenta":"172010","Descripción":"Perforaciones campos en desarrollo","Naturaleza":"Debe"},
    {"Cuenta":"172015","Descripción":"Facilidades de producción","Naturaleza":"Debe"},
    {"Cuenta":"172020","Descripción":"Servicio a pozos","Naturaleza":"Debe"},
    {"Cuenta":"172099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1730","Descripción":"Cargos por corrección monetaria diferida","Naturaleza":"Debe"},
    {"Cuenta":"1798","Descripción":"Amortización acumulada","Naturaleza":"Debe"},
    {"Cuenta":"179805","Descripción":"Costos de exploración por amortizar","Naturaleza":"Debe"},
    {"Cuenta":"179810","Descripción":"Costos de explotación y desarrollo","Naturaleza":"Debe"},
    {"Cuenta":"179899","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"18","Descripción":"Otros activos","Naturaleza":"Debe"},
    {"Cuenta":"1805","Descripción":"Bienes de arte y cultura","Naturaleza":"Debe"},
    {"Cuenta":"180505","Descripción":"Obras de arte","Naturaleza":"Debe"},
    {"Cuenta":"180510","Descripción":"Bibliotecas","Naturaleza":"Debe"},
    {"Cuenta":"180595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"180599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1895","Descripción":"Diversos","Naturaleza":"Debe"},
    {"Cuenta":"189505","Descripción":"Máquinas porteadoras","Naturaleza":"Debe"},
    {"Cuenta":"189510","Descripción":"Bienes entregados en comodato","Naturaleza":"Debe"},
    {"Cuenta":"189515","Descripción":"Amortización acumulada de bienes entregados en comodato (CR)","Naturaleza":"Debe"},
    {"Cuenta":"189520","Descripción":"Bienes recibidos en pago","Naturaleza":"Debe"},
    {"Cuenta":"189525","Descripción":"Derechos sucesorales","Naturaleza":"Debe"},
    {"Cuenta":"189530","Descripción":"Estampillas","Naturaleza":"Debe"},
    {"Cuenta":"189595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"189599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"1899","Descripción":"Provisiones","Naturaleza":"Debe"},
    {"Cuenta":"189905","Descripción":"Bienes de arte y cultura","Naturaleza":"Debe"},
    {"Cuenta":"189995","Descripción":"Diversos","Naturaleza":"Debe"},
    {"Cuenta":"19","Descripción":"Valorizaciones","Naturaleza":"Debe"},
    {"Cuenta":"1905","Descripción":"De inversiones","Naturaleza":"Debe"},
    {"Cuenta":"190505","Descripción":"Acciones","Naturaleza":"Debe"},
    {"Cuenta":"190510","Descripción":"Cuotas o partes de interés social","Naturaleza":"Debe"},
    {"Cuenta":"190515","Descripción":"Derechos fiduciarios","Naturaleza":"Debe"},
    {"Cuenta":"1910","Descripción":"De propiedades, planta y equipo","Naturaleza":"Debe"},
    {"Cuenta":"191004","Descripción":"Terrenos","Naturaleza":"Debe"},
    {"Cuenta":"191006","Descripción":"Materiales proyectos petroleros","Naturaleza":"Debe"},
    {"Cuenta":"191008","Descripción":"Construcciones y edificaciones","Naturaleza":"Debe"},
    {"Cuenta":"191012","Descripción":"Maquinaria y equipo","Naturaleza":"Debe"},
    {"Cuenta":"191016","Descripción":"Equipo de oficina","Naturaleza":"Debe"},
    {"Cuenta":"191020","Descripción":"Equipo de computación y comunicación","Naturaleza":"Debe"},
    {"Cuenta":"191024","Descripción":"Equipo médico-científico","Naturaleza":"Debe"},
    {"Cuenta":"191028","Descripción":"Equipo de hoteles y restaurantes","Naturaleza":"Debe"},
    {"Cuenta":"191032","Descripción":"Flota y equipo de transporte","Naturaleza":"Debe"},
    {"Cuenta":"191036","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Debe"},
    {"Cuenta":"191040","Descripción":"Flota y equipo aéreo","Naturaleza":"Debe"},
    {"Cuenta":"191044","Descripción":"Flota y equipo férreo","Naturaleza":"Debe"},
    {"Cuenta":"191048","Descripción":"Acueductos, plantas y redes","Naturaleza":"Debe"},
    {"Cuenta":"191052","Descripción":"Armamento de vigilancia","Naturaleza":"Debe"},
    {"Cuenta":"191056","Descripción":"Envases y empaques","Naturaleza":"Debe"},
    {"Cuenta":"191060","Descripción":"Plantaciones agrícolas y forestales","Naturaleza":"Debe"},
    {"Cuenta":"191064","Descripción":"Vías de comunicación","Naturaleza":"Debe"},
    {"Cuenta":"191068","Descripción":"Minas y canteras","Naturaleza":"Debe"},
    {"Cuenta":"191072","Descripción":"Pozos artesianos","Naturaleza":"Debe"},
    {"Cuenta":"191076","Descripción":"Yacimientos","Naturaleza":"Debe"},
    {"Cuenta":"191080","Descripción":"Semovientes","Naturaleza":"Debe"},
    {"Cuenta":"1995","Descripción":"De otros activos","Naturaleza":"Debe"},
    {"Cuenta":"199505","Descripción":"Bienes de arte y cultura","Naturaleza":"Debe"},
    {"Cuenta":"199510","Descripción":"Bienes entregados en comodato","Naturaleza":"Debe"},
    {"Cuenta":"199515","Descripción":"Bienes recibidos en pago","Naturaleza":"Debe"},
    {"Cuenta":"199520","Descripción":"Inventario de semovientes","Naturaleza":"Debe"}
]
