export const Costos = [
    {"Cuenta":"6","Descripción":"Costos de ventas","Naturaleza":"Debe"},
    {"Cuenta":"61","Descripción":"Costo de ventas y de prestación de servicios","Naturaleza":"Debe"},
    {"Cuenta":"6105","Descripción":"Agricultura, ganadería, caza y silvicultura","Naturaleza":"Debe"},
    {"Cuenta":"610505","Descripción":"Cultivo de cereales","Naturaleza":"Debe"},
    {"Cuenta":"610510","Descripción":"Cultivos de hortalizas, legumbres y plantas ornamentales","Naturaleza":"Debe"},
    {"Cuenta":"610515","Descripción":"Cultivos de frutas, nueces y plantas aromáticas","Naturaleza":"Debe"},
    {"Cuenta":"610520","Descripción":"Cultivo de café","Naturaleza":"Debe"},
    {"Cuenta":"610525","Descripción":"Cultivo de flores","Naturaleza":"Debe"},
    {"Cuenta":"610530","Descripción":"Cultivo de caña de azúcar","Naturaleza":"Debe"},
    {"Cuenta":"610535","Descripción":"Cultivo de algodón y plantas para material textil","Naturaleza":"Debe"},
    {"Cuenta":"610540","Descripción":"Cultivo de banano","Naturaleza":"Debe"},
    {"Cuenta":"610545","Descripción":"Otros cultivos agrícolas","Naturaleza":"Debe"},
    {"Cuenta":"610550","Descripción":"Cría de ovejas, cabras, asnos, mulas y burdéganos","Naturaleza":"Debe"},
    {"Cuenta":"610555","Descripción":"Cría de ganado caballar y vacuno","Naturaleza":"Debe"},
    {"Cuenta":"610560","Descripción":"Producción avícola","Naturaleza":"Debe"},
    {"Cuenta":"610565","Descripción":"Cría de otros animales","Naturaleza":"Debe"},
    {"Cuenta":"610570","Descripción":"Servicios agrícolas y ganaderos","Naturaleza":"Debe"},
    {"Cuenta":"610575","Descripción":"Actividad de caza","Naturaleza":"Debe"},
    {"Cuenta":"610580","Descripción":"Actividad de silvicultura","Naturaleza":"Debe"},
    {"Cuenta":"610595","Descripción":"Actividades conexas","Naturaleza":"Debe"},
    {"Cuenta":"610599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"6110","Descripción":"Pesca","Naturaleza":"Debe"},
    {"Cuenta":"611005","Descripción":"Actividad de pesca","Naturaleza":"Debe"},
    {"Cuenta":"611010","Descripción":"Explotación de criaderos de peces","Naturaleza":"Debe"},
    {"Cuenta":"611095","Descripción":"Actividades conexas","Naturaleza":"Debe"},
    {"Cuenta":"611099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"6115","Descripción":"Explotación de minas y canteras","Naturaleza":"Debe"},
    {"Cuenta":"611505","Descripción":"Carbón","Naturaleza":"Debe"},
    {"Cuenta":"611510","Descripción":"Petróleo crudo","Naturaleza":"Debe"},
    {"Cuenta":"611512","Descripción":"Gas natural","Naturaleza":"Debe"},
    {"Cuenta":"611514","Descripción":"Servicios relacionados con extracción de petróleo y gas","Naturaleza":"Debe"},
    {"Cuenta":"611515","Descripción":"Minerales de hierro","Naturaleza":"Debe"},
    {"Cuenta":"611520","Descripción":"Minerales metalíferos no ferrosos","Naturaleza":"Debe"},
    {"Cuenta":"611525","Descripción":"Piedra, arena y arcilla","Naturaleza":"Debe"},
    {"Cuenta":"611527","Descripción":"Piedras preciosas","Naturaleza":"Debe"},
    {"Cuenta":"611528","Descripción":"Oro","Naturaleza":"Debe"},
    {"Cuenta":"611530","Descripción":"Otras minas y canteras","Naturaleza":"Debe"},
    {"Cuenta":"611532","Descripción":"Prestación de servicios sector minero","Naturaleza":"Debe"},
    {"Cuenta":"611595","Descripción":"Actividades conexas","Naturaleza":"Debe"},
    {"Cuenta":"611599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"6120","Descripción":"Industrias manufactureras","Naturaleza":"Debe"},
    {"Cuenta":"612001","Descripción":"Producción y procesamiento de carnes y productos cárnicos","Naturaleza":"Debe"},
    {"Cuenta":"612002","Descripción":"Productos de pescado","Naturaleza":"Debe"},
    {"Cuenta":"612003","Descripción":"Productos de frutas, legumbres y hortalizas","Naturaleza":"Debe"},
    {"Cuenta":"612004","Descripción":"Elaboración de aceites y grasas","Naturaleza":"Debe"},
    {"Cuenta":"612005","Descripción":"Elaboración  de productos lácteos","Naturaleza":"Debe"},
    {"Cuenta":"612006","Descripción":"Elaboración de productos de molinería","Naturaleza":"Debe"},
    {"Cuenta":"612007","Descripción":"Elaboración de almidones y derivados","Naturaleza":"Debe"},
    {"Cuenta":"612008","Descripción":"Elaboración de alimentos para animales","Naturaleza":"Debe"},
    {"Cuenta":"612009","Descripción":"Elaboración de productos para panadería","Naturaleza":"Debe"},
    {"Cuenta":"612010","Descripción":"Elaboración de azúcar y melazas","Naturaleza":"Debe"},
    {"Cuenta":"612011","Descripción":"Elaboración de cacao, chocolate y confitería","Naturaleza":"Debe"},
    {"Cuenta":"612012","Descripción":"Elaboración  de pastas y productos farináceos","Naturaleza":"Debe"},
    {"Cuenta":"612013","Descripción":"Elaboración de productos de café","Naturaleza":"Debe"},
    {"Cuenta":"612014","Descripción":"Elaboración de otros productos alimenticios","Naturaleza":"Debe"},
    {"Cuenta":"612015","Descripción":"Elaboración de bebidas alcohólicas y alcohol etílico","Naturaleza":"Debe"},
    {"Cuenta":"612016","Descripción":"Elaboración de vinos","Naturaleza":"Debe"},
    {"Cuenta":"612017","Descripción":"Elaboración de bebidas malteadas y de malta","Naturaleza":"Debe"},
    {"Cuenta":"612018","Descripción":"Elaboración de bebidas no alcohólicas","Naturaleza":"Debe"},
    {"Cuenta":"612019","Descripción":"Elaboración de productos de tabaco","Naturaleza":"Debe"},
    {"Cuenta":"612020","Descripción":"Preparación e hilatura de fibras textiles y tejeduría","Naturaleza":"Debe"},
    {"Cuenta":"612021","Descripción":"Acabado de productos textiles","Naturaleza":"Debe"},
    {"Cuenta":"612022","Descripción":"Elaboración de artículos de materiales textiles","Naturaleza":"Debe"},
    {"Cuenta":"612023","Descripción":"Elaboración de tapices y alfombras","Naturaleza":"Debe"},
    {"Cuenta":"612024","Descripción":"Elaboración de cuerdas, cordeles, bramantes y redes","Naturaleza":"Debe"},
    {"Cuenta":"612025","Descripción":"Elaboración de otros productos textiles","Naturaleza":"Debe"},
    {"Cuenta":"612026","Descripción":"Elaboración de tejidos","Naturaleza":"Debe"},
    {"Cuenta":"612027","Descripción":"Elaboración de prendas de vestir","Naturaleza":"Debe"},
    {"Cuenta":"612028","Descripción":"Preparación, adobo y teñido de pieles","Naturaleza":"Debe"},
    {"Cuenta":"612029","Descripción":"Curtido, adobo o preparación de cuero","Naturaleza":"Debe"},
    {"Cuenta":"612030","Descripción":"Elaboración de maletas, bolsos y similares","Naturaleza":"Debe"},
    {"Cuenta":"612031","Descripción":"Elaboración de calzado","Naturaleza":"Debe"},
    {"Cuenta":"612032","Descripción":"Producción de madera, artículos de madera y corcho","Naturaleza":"Debe"},
    {"Cuenta":"612033","Descripción":"Elaboración de pasta y productos de madera, papel y cartón","Naturaleza":"Debe"},
    {"Cuenta":"612034","Descripción":"Ediciones y publicaciones","Naturaleza":"Debe"},
    {"Cuenta":"612035","Descripción":"Impresión","Naturaleza":"Debe"},
    {"Cuenta":"612036","Descripción":"Servicios relacionados con la edición y la impresión","Naturaleza":"Debe"},
    {"Cuenta":"612037","Descripción":"Reproducción de grabaciones","Naturaleza":"Debe"},
    {"Cuenta":"612038","Descripción":"Elaboración de productos de horno de coque","Naturaleza":"Debe"},
    {"Cuenta":"612039","Descripción":"Elaboración de productos de la refinación de petróleo","Naturaleza":"Debe"},
    {"Cuenta":"612040","Descripción":"Elaboración de sustancias químicas básicas","Naturaleza":"Debe"},
    {"Cuenta":"612041","Descripción":"Elaboración de abonos y compuestos de nitrógeno","Naturaleza":"Debe"},
    {"Cuenta":"612042","Descripción":"Elaboración de plástico y caucho sintético","Naturaleza":"Debe"},
    {"Cuenta":"612043","Descripción":"Elaboración de productos químicos de uso agropecuario","Naturaleza":"Debe"},
    {"Cuenta":"612044","Descripción":"Elaboración de pinturas, tintas y masillas","Naturaleza":"Debe"},
    {"Cuenta":"612045","Descripción":"Elaboración de productos farmacéuticos y botánicos","Naturaleza":"Debe"},
    {"Cuenta":"612046","Descripción":"Elaboración de jabones, detergentes y preparados de tocador","Naturaleza":"Debe"},
    {"Cuenta":"612047","Descripción":"Elaboración de otros productos químicos","Naturaleza":"Debe"},
    {"Cuenta":"612048","Descripción":"Elaboración de fibras","Naturaleza":"Debe"},
    {"Cuenta":"612049","Descripción":"Elaboración de otros productos de caucho","Naturaleza":"Debe"},
    {"Cuenta":"612050","Descripción":"Elaboración de productos de plástico","Naturaleza":"Debe"},
    {"Cuenta":"612051","Descripción":"Elaboración de vidrio y productos de vidrio","Naturaleza":"Debe"},
    {"Cuenta":"612052","Descripción":"Elaboración de productos de cerámica, loza, piedra, arcilla y porcelana","Naturaleza":"Debe"},
    {"Cuenta":"612053","Descripción":"Elaboración de cemento, cal y yeso","Naturaleza":"Debe"},
    {"Cuenta":"612054","Descripción":"Elaboración de artículos de hormigón, cemento y yeso","Naturaleza":"Debe"},
    {"Cuenta":"612055","Descripción":"Corte, tallado y acabado de la piedra","Naturaleza":"Debe"},
    {"Cuenta":"612056","Descripción":"Elaboración de otros productos minerales no metálicos","Naturaleza":"Debe"},
    {"Cuenta":"612057","Descripción":"Industrias básicas y fundición de hierro y acero","Naturaleza":"Debe"},
    {"Cuenta":"612058","Descripción":"Productos primarios de metales preciosos y de metales no ferrosos","Naturaleza":"Debe"},
    {"Cuenta":"612059","Descripción":"Fundición de metales no ferrosos","Naturaleza":"Debe"},
    {"Cuenta":"612060","Descripción":"Fabricación de productos metálicos para uso estructural","Naturaleza":"Debe"},
    {"Cuenta":"612061","Descripción":"Forja, prensado, estampado, laminado de metal y pulvimetalurgia","Naturaleza":"Debe"},
    {"Cuenta":"612062","Descripción":"Revestimiento de metales y obras de ingeniería mecánica","Naturaleza":"Debe"},
    {"Cuenta":"612063","Descripción":"Fabricación de artículos de ferretería","Naturaleza":"Debe"},
    {"Cuenta":"612064","Descripción":"Elaboración de otros productos de metal","Naturaleza":"Debe"},
    {"Cuenta":"612065","Descripción":"Fabricación de maquinaria y equipo","Naturaleza":"Debe"},
    {"Cuenta":"612066","Descripción":"Fabricación de equipos de elevación y manipulación","Naturaleza":"Debe"},
    {"Cuenta":"612067","Descripción":"Elaboración de aparatos de uso doméstico","Naturaleza":"Debe"},
    {"Cuenta":"612068","Descripción":"Elaboración de equipo de oficina","Naturaleza":"Debe"},
    {"Cuenta":"612069","Descripción":"Elaboración de pilas y baterías primarias","Naturaleza":"Debe"},
    {"Cuenta":"612070","Descripción":"Elaboración de equipo de iluminación","Naturaleza":"Debe"},
    {"Cuenta":"612071","Descripción":"Elaboración de otros tipos de equipo eléctrico","Naturaleza":"Debe"},
    {"Cuenta":"612072","Descripción":"Fabricación de equipos de radio, televisión y comunicaciones","Naturaleza":"Debe"},
    {"Cuenta":"612073","Descripción":"Fabricación de aparatos e instrumentos médicos","Naturaleza":"Debe"},
    {"Cuenta":"612074","Descripción":"Fabricación de instrumentos de medición y control","Naturaleza":"Debe"},
    {"Cuenta":"612075","Descripción":"Fabricación de instrumentos de óptica y equipo fotográfico","Naturaleza":"Debe"},
    {"Cuenta":"612076","Descripción":"Fabricación de relojes","Naturaleza":"Debe"},
    {"Cuenta":"612077","Descripción":"Fabricación de vehículos automotores","Naturaleza":"Debe"},
    {"Cuenta":"612078","Descripción":"Fabricación de carrocerías para automotores","Naturaleza":"Debe"},
    {"Cuenta":"612079","Descripción":"Fabricación de partes, piezas y accesorios para automotores","Naturaleza":"Debe"},
    {"Cuenta":"612080","Descripción":"Fabricación y reparación de buques y otras embarcaciones","Naturaleza":"Debe"},
    {"Cuenta":"612081","Descripción":"Fabricación de locomotoras y material rodante para ferrocarriles","Naturaleza":"Debe"},
    {"Cuenta":"612082","Descripción":"Fabricación de aeronaves","Naturaleza":"Debe"},
    {"Cuenta":"612083","Descripción":"Fabricación de motocicletas","Naturaleza":"Debe"},
    {"Cuenta":"612084","Descripción":"Fabricación de bicicletas y sillas de ruedas","Naturaleza":"Debe"},
    {"Cuenta":"612085","Descripción":"Fabricación de otros tipos de transporte","Naturaleza":"Debe"},
    {"Cuenta":"612086","Descripción":"Fabricación de muebles","Naturaleza":"Debe"},
    {"Cuenta":"612087","Descripción":"Fabricación de joyas y artículos conexos","Naturaleza":"Debe"},
    {"Cuenta":"612088","Descripción":"Fabricación de instrumentos de música","Naturaleza":"Debe"},
    {"Cuenta":"612089","Descripción":"Fabricación de artículos y equipo para deporte","Naturaleza":"Debe"},
    {"Cuenta":"612090","Descripción":"Fabricación de juegos y juguetes","Naturaleza":"Debe"},
    {"Cuenta":"612091","Descripción":"Reciclamiento de desperdicios","Naturaleza":"Debe"},
    {"Cuenta":"612095","Descripción":"Productos de otras industrias manufactureras","Naturaleza":"Debe"},
    {"Cuenta":"612099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"6125","Descripción":"Suministro de electricidad, gas y agua","Naturaleza":"Debe"},
    {"Cuenta":"612505","Descripción":"Generación, captación y distribución de energía eléctrica","Naturaleza":"Debe"},
    {"Cuenta":"612510","Descripción":"Fabricación de gas y distribución de combustibles gaseosos","Naturaleza":"Debe"},
    {"Cuenta":"612515","Descripción":"Captación, depuración y distribución de agua","Naturaleza":"Debe"},
    {"Cuenta":"612595","Descripción":"Actividades conexas","Naturaleza":"Debe"},
    {"Cuenta":"612599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"6130","Descripción":"Construcción","Naturaleza":"Debe"},
    {"Cuenta":"613005","Descripción":"Preparación de terrenos","Naturaleza":"Debe"},
    {"Cuenta":"613010","Descripción":"Construcción de edificios y obras de ingeniería civil","Naturaleza":"Debe"},
    {"Cuenta":"613015","Descripción":"Acondicionamiento de edificios","Naturaleza":"Debe"},
    {"Cuenta":"613020","Descripción":"Terminación de edificaciones","Naturaleza":"Debe"},
    {"Cuenta":"613025","Descripción":"Alquiler de equipo con operario","Naturaleza":"Debe"},
    {"Cuenta":"613095","Descripción":"Actividades conexas","Naturaleza":"Debe"},
    {"Cuenta":"613099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"6135","Descripción":"Comercio al por mayor y al por menor","Naturaleza":"Debe"},
    {"Cuenta":"613502","Descripción":"Venta de vehículos automotores","Naturaleza":"Debe"},
    {"Cuenta":"613504","Descripción":"Mantenimiento, reparación y lavado de vehículos automotores","Naturaleza":"Debe"},
    {"Cuenta":"613506","Descripción":"Venta de partes, piezas y accesorios de vehículos automotores","Naturaleza":"Debe"},
    {"Cuenta":"613508","Descripción":"Venta  de combustibles sólidos, líquidos, gaseosos","Naturaleza":"Debe"},
    {"Cuenta":"613510","Descripción":"Venta de lubricantes, aditivos, llantas y lujos para automotores","Naturaleza":"Debe"},
    {"Cuenta":"613512","Descripción":"Venta a cambio de retribución o por contrata","Naturaleza":"Debe"},
    {"Cuenta":"613514","Descripción":"Venta de insumos, materias primas agropecuarias y flores","Naturaleza":"Debe"},
    {"Cuenta":"613516","Descripción":"Venta de otros insumos y materias primas no agropecuarias","Naturaleza":"Debe"},
    {"Cuenta":"613518","Descripción":"Venta de animales vivos y cueros","Naturaleza":"Debe"},
    {"Cuenta":"613520","Descripción":"Venta de productos en almacenes no especializados","Naturaleza":"Debe"},
    {"Cuenta":"613522","Descripción":"Venta de productos agropecuarios","Naturaleza":"Debe"},
    {"Cuenta":"613524","Descripción":"Venta de productos textiles, de vestir, de cuero y calzado","Naturaleza":"Debe"},
    {"Cuenta":"613526","Descripción":"Venta de papel y cartón","Naturaleza":"Debe"},
    {"Cuenta":"613528","Descripción":"Venta de libros, revistas, elementos de papelería, útiles y textos escolares","Naturaleza":"Debe"},
    {"Cuenta":"613530","Descripción":"Venta de juegos, juguetes y artículos deportivos","Naturaleza":"Debe"},
    {"Cuenta":"613532","Descripción":"Venta de instrumentos quirúrgicos y ortopédicos","Naturaleza":"Debe"},
    {"Cuenta":"613534","Descripción":"Venta de artículos en relojerías y joyerías","Naturaleza":"Debe"},
    {"Cuenta":"613536","Descripción":"Venta de electrodomésticos y muebles","Naturaleza":"Debe"},
    {"Cuenta":"613538","Descripción":"Venta de productos de aseo, farmacéuticos,  medicinales y artículos de tocador","Naturaleza":"Debe"},
    {"Cuenta":"613540","Descripción":"Venta de cubiertos, vajillas, cristalería, porcelanas, cerámicas y otros artículos de uso doméstico","Naturaleza":"Debe"},
    {"Cuenta":"613542","Descripción":"Venta de materiales de construcción, fontanería y calefacción","Naturaleza":"Debe"},
    {"Cuenta":"613544","Descripción":"Venta de pinturas y lacas","Naturaleza":"Debe"},
    {"Cuenta":"613546","Descripción":"Venta de productos de vidrios y marquetería","Naturaleza":"Debe"},
    {"Cuenta":"613548","Descripción":"Venta de herramientas y artículos de ferretería","Naturaleza":"Debe"},
    {"Cuenta":"613550","Descripción":"Venta de químicos","Naturaleza":"Debe"},
    {"Cuenta":"613552","Descripción":"Venta de productos intermedios, desperdicios y desechos","Naturaleza":"Debe"},
    {"Cuenta":"613554","Descripción":"Venta de maquinaria, equipo de oficina y programas de computador","Naturaleza":"Debe"},
    {"Cuenta":"613556","Descripción":"Venta de artículos en cacharrerías y misceláneas","Naturaleza":"Debe"},
    {"Cuenta":"613558","Descripción":"Venta de instrumentos musicales","Naturaleza":"Debe"},
    {"Cuenta":"613560","Descripción":"Venta de artículos en casas de empeño y prenderías","Naturaleza":"Debe"},
    {"Cuenta":"613562","Descripción":"Venta de equipo fotográfico","Naturaleza":"Debe"},
    {"Cuenta":"613564","Descripción":"Venta de equipo óptico y de precisión","Naturaleza":"Debe"},
    {"Cuenta":"613566","Descripción":"Venta de empaques","Naturaleza":"Debe"},
    {"Cuenta":"613568","Descripción":"Venta de equipo profesional y científico","Naturaleza":"Debe"},
    {"Cuenta":"613570","Descripción":"Venta de loterías, rifas, chance, apuestas y similares","Naturaleza":"Debe"},
    {"Cuenta":"613572","Descripción":"Reparación de efectos personales y electrodomésticos","Naturaleza":"Debe"},
    {"Cuenta":"613595","Descripción":"Venta de otros productos","Naturaleza":"Debe"},
    {"Cuenta":"613599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"6140","Descripción":"Hoteles y restaurantes","Naturaleza":"Debe"},
    {"Cuenta":"614005","Descripción":"Hotelería","Naturaleza":"Debe"},
    {"Cuenta":"614010","Descripción":"Campamento y otros tipos de hospedaje","Naturaleza":"Debe"},
    {"Cuenta":"614015","Descripción":"Restaurantes","Naturaleza":"Debe"},
    {"Cuenta":"614020","Descripción":"Bares y cantinas","Naturaleza":"Debe"},
    {"Cuenta":"614095","Descripción":"Actividades conexas","Naturaleza":"Debe"},
    {"Cuenta":"614099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"6145","Descripción":"Transporte, almacenamiento y comunicaciones","Naturaleza":"Debe"},
    {"Cuenta":"614505","Descripción":"Servicio de transporte por carretera","Naturaleza":"Debe"},
    {"Cuenta":"614510","Descripción":"Servicio de transporte por vía férrea","Naturaleza":"Debe"},
    {"Cuenta":"614515","Descripción":"Servicio de transporte por vía acuática","Naturaleza":"Debe"},
    {"Cuenta":"614520","Descripción":"Servicio de transporte por vía aérea","Naturaleza":"Debe"},
    {"Cuenta":"614525","Descripción":"Servicio de transporte por tuberías","Naturaleza":"Debe"},
    {"Cuenta":"614530","Descripción":"Manipulación de carga","Naturaleza":"Debe"},
    {"Cuenta":"614535","Descripción":"Almacenamiento y depósito","Naturaleza":"Debe"},
    {"Cuenta":"614540","Descripción":"Servicios complementarios para el transporte","Naturaleza":"Debe"},
    {"Cuenta":"614545","Descripción":"Agencias de viaje","Naturaleza":"Debe"},
    {"Cuenta":"614550","Descripción":"Otras agencias de transporte","Naturaleza":"Debe"},
    {"Cuenta":"614555","Descripción":"Servicio postal y de correo","Naturaleza":"Debe"},
    {"Cuenta":"614560","Descripción":"Servicio telefónico","Naturaleza":"Debe"},
    {"Cuenta":"614565","Descripción":"Servicio de telégrafo","Naturaleza":"Debe"},
    {"Cuenta":"614570","Descripción":"Servicio de transmisión de datos","Naturaleza":"Debe"},
    {"Cuenta":"614575","Descripción":"Servicio de radio y televisión por cable","Naturaleza":"Debe"},
    {"Cuenta":"614580","Descripción":"Transmisión de sonido e imágenes por contrato","Naturaleza":"Debe"},
    {"Cuenta":"614595","Descripción":"Actividades conexas","Naturaleza":"Debe"},
    {"Cuenta":"614599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"6150","Descripción":"Actividad financiera","Naturaleza":"Debe"},
    {"Cuenta":"615005","Descripción":"De inversiones","Naturaleza":"Debe"},
    {"Cuenta":"615010","Descripción":"De servicio de bolsa","Naturaleza":"Debe"},
    {"Cuenta":"615099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"6155","Descripción":"Actividades inmobiliarias, empresariales y de alquiler","Naturaleza":"Debe"},
    {"Cuenta":"615505","Descripción":"Arrendamientos de bienes inmuebles","Naturaleza":"Debe"},
    {"Cuenta":"615510","Descripción":"Inmobiliarias por retribución o contrata","Naturaleza":"Debe"},
    {"Cuenta":"615515","Descripción":"Alquiler equipo de transporte","Naturaleza":"Debe"},
    {"Cuenta":"615520","Descripción":"Alquiler maquinaria y equipo","Naturaleza":"Debe"},
    {"Cuenta":"615525","Descripción":"Alquiler de efectos personales y enseres domésticos","Naturaleza":"Debe"},
    {"Cuenta":"615530","Descripción":"Consultoría en equipo y programas de informática","Naturaleza":"Debe"},
    {"Cuenta":"615535","Descripción":"Procesamiento de datos","Naturaleza":"Debe"},
    {"Cuenta":"615540","Descripción":"Mantenimiento y reparación de maquinaria de oficina","Naturaleza":"Debe"},
    {"Cuenta":"615545","Descripción":"Investigaciones científicas y de desarrollo","Naturaleza":"Debe"},
    {"Cuenta":"615550","Descripción":"Actividades empresariales de consultoría","Naturaleza":"Debe"},
    {"Cuenta":"615555","Descripción":"Publicidad","Naturaleza":"Debe"},
    {"Cuenta":"615560","Descripción":"Dotación de personal","Naturaleza":"Debe"},
    {"Cuenta":"615565","Descripción":"Investigación y seguridad","Naturaleza":"Debe"},
    {"Cuenta":"615570","Descripción":"Limpieza de inmuebles","Naturaleza":"Debe"},
    {"Cuenta":"615575","Descripción":"Fotografía","Naturaleza":"Debe"},
    {"Cuenta":"615580","Descripción":"Envase y empaque","Naturaleza":"Debe"},
    {"Cuenta":"615585","Descripción":"Fotocopiado","Naturaleza":"Debe"},
    {"Cuenta":"615590","Descripción":"Mantenimiento y reparación de maquinaria y  equipo","Naturaleza":"Debe"},
    {"Cuenta":"615595","Descripción":"Actividades conexas","Naturaleza":"Debe"},
    {"Cuenta":"615599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"6160","Descripción":"Enseñanza","Naturaleza":"Debe"},
    {"Cuenta":"616005","Descripción":"Actividades relacionadas con la educación","Naturaleza":"Debe"},
    {"Cuenta":"616095","Descripción":"Actividades conexas","Naturaleza":"Debe"},
    {"Cuenta":"616099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"6165","Descripción":"Servicios sociales y de salud","Naturaleza":"Debe"},
    {"Cuenta":"616505","Descripción":"Servicio hospitalario","Naturaleza":"Debe"},
    {"Cuenta":"616510","Descripción":"Servicio médico","Naturaleza":"Debe"},
    {"Cuenta":"616515","Descripción":"Servicio odontológico","Naturaleza":"Debe"},
    {"Cuenta":"616520","Descripción":"Servicio de laboratorio","Naturaleza":"Debe"},
    {"Cuenta":"616525","Descripción":"Actividades veterinarias","Naturaleza":"Debe"},
    {"Cuenta":"616530","Descripción":"Actividades de servicios sociales","Naturaleza":"Debe"},
    {"Cuenta":"616595","Descripción":"Actividades conexas","Naturaleza":"Debe"},
    {"Cuenta":"616599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"6170","Descripción":"Otras actividades de servicios comunitarios, sociales y personales","Naturaleza":"Debe"},
    {"Cuenta":"617005","Descripción":"Eliminación de desperdicios y aguas residuales","Naturaleza":"Debe"},
    {"Cuenta":"617010","Descripción":"Actividades de asociación","Naturaleza":"Debe"},
    {"Cuenta":"617015","Descripción":"Producción y distribución de filmes y videocintas","Naturaleza":"Debe"},
    {"Cuenta":"617020","Descripción":"Exhibición de filmes y videocintas","Naturaleza":"Debe"},
    {"Cuenta":"617025","Descripción":"Actividad de radio y televisión","Naturaleza":"Debe"},
    {"Cuenta":"617030","Descripción":"Actividad teatral, musical y artística","Naturaleza":"Debe"},
    {"Cuenta":"617035","Descripción":"Grabación y producción de discos","Naturaleza":"Debe"},
    {"Cuenta":"617040","Descripción":"Entretenimiento y esparcimiento","Naturaleza":"Debe"},
    {"Cuenta":"617045","Descripción":"Agencias de noticias","Naturaleza":"Debe"},
    {"Cuenta":"617050","Descripción":"Lavanderías y similares","Naturaleza":"Debe"},
    {"Cuenta":"617055","Descripción":"Peluquerías y similares","Naturaleza":"Debe"},
    {"Cuenta":"617060","Descripción":"Servicios funerarios","Naturaleza":"Debe"},
    {"Cuenta":"617065","Descripción":"Zonas francas","Naturaleza":"Debe"},
    {"Cuenta":"617095","Descripción":"Actividades conexas","Naturaleza":"Debe"},
    {"Cuenta":"617099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"62","Descripción":"Compras","Naturaleza":"Debe"},
    {"Cuenta":"6205","Descripción":"De mercancías","Naturaleza":"Debe"},
    {"Cuenta":"620599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"6210","Descripción":"De materias primas","Naturaleza":"Debe"},
    {"Cuenta":"621099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"6215","Descripción":"De materiales indirectos","Naturaleza":"Debe"},
    {"Cuenta":"621599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"6220","Descripción":"Compra de energía","Naturaleza":"Debe"},
    {"Cuenta":"622099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"6225","Descripción":"Devoluciones en compras (CR)","Naturaleza":"Debe"},
    {"Cuenta":"622599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
]