export const Gastos = [
    {"Cuenta":"5","Descripción":"Gastos","Naturaleza":"Debe"},
    {"Cuenta":"51","Descripción":"Operacionales de administración","Naturaleza":"Debe"},
    {"Cuenta":"5105","Descripción":"Gastos de personal","Naturaleza":"Debe"},
    {"Cuenta":"510503","Descripción":"Salario integral","Naturaleza":"Debe"},
    {"Cuenta":"510506","Descripción":"Sueldos","Naturaleza":"Debe"},
    {"Cuenta":"510512","Descripción":"Jornales","Naturaleza":"Debe"},
    {"Cuenta":"510515","Descripción":"Horas extras y recargos","Naturaleza":"Debe"},
    {"Cuenta":"510518","Descripción":"Comisiones","Naturaleza":"Debe"},
    {"Cuenta":"510521","Descripción":"Viáticos","Naturaleza":"Debe"},
    {"Cuenta":"510524","Descripción":"Incapacidades","Naturaleza":"Debe"},
    {"Cuenta":"510527","Descripción":"Auxilio de transporte","Naturaleza":"Debe"},
    {"Cuenta":"510530","Descripción":"Cesantías","Naturaleza":"Debe"},
    {"Cuenta":"510533","Descripción":"Intereses sobre cesantías","Naturaleza":"Debe"},
    {"Cuenta":"510536","Descripción":"Prima de servicios","Naturaleza":"Debe"},
    {"Cuenta":"510539","Descripción":"Vacaciones","Naturaleza":"Debe"},
    {"Cuenta":"510542","Descripción":"Primas extralegales","Naturaleza":"Debe"},
    {"Cuenta":"510545","Descripción":"Auxilios","Naturaleza":"Debe"},
    {"Cuenta":"510548","Descripción":"Bonificaciones","Naturaleza":"Debe"},
    {"Cuenta":"510551","Descripción":"Dotación y suministro a trabajadores","Naturaleza":"Debe"},
    {"Cuenta":"510554","Descripción":"Seguros","Naturaleza":"Debe"},
    {"Cuenta":"510557","Descripción":"Cuotas partes pensiones de jubilación","Naturaleza":"Debe"},
    {"Cuenta":"510558","Descripción":"Amortización cálculo actuarial pensiones de jubilación","Naturaleza":"Debe"},
    {"Cuenta":"510559","Descripción":"Pensiones de jubilación","Naturaleza":"Debe"},
    {"Cuenta":"510560","Descripción":"Indemnizaciones laborales","Naturaleza":"Debe"},
    {"Cuenta":"510561","Descripción":"Amortización bonos pensionales","Naturaleza":"Debe"},
    {"Cuenta":"510562","Descripción":"Amortización títulos pensionales","Naturaleza":"Debe"},
    {"Cuenta":"510563","Descripción":"Capacitación al personal","Naturaleza":"Debe"},
    {"Cuenta":"510566","Descripción":"Gastos deportivos y de recreación","Naturaleza":"Debe"},
    {"Cuenta":"510568","Descripción":"Aportes a administradoras de riesgos profesionales, ARP","Naturaleza":"Debe"},
    {"Cuenta":"510569","Descripción":"Aportes a entidades promotoras de salud, EPS","Naturaleza":"Debe"},
    {"Cuenta":"510570","Descripción":"Aportes a fondos de pensiones y/o cesantías","Naturaleza":"Debe"},
    {"Cuenta":"510572","Descripción":"Aportes cajas de compensación familiar","Naturaleza":"Debe"},
    {"Cuenta":"510575","Descripción":"Aportes ICBF","Naturaleza":"Debe"},
    {"Cuenta":"510578","Descripción":"SENA","Naturaleza":"Debe"},
    {"Cuenta":"510581","Descripción":"Aportes sindicales","Naturaleza":"Debe"},
    {"Cuenta":"510584","Descripción":"Gastos médicos y drogas","Naturaleza":"Debe"},
    {"Cuenta":"510595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"510599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5110","Descripción":"Honorarios","Naturaleza":"Debe"},
    {"Cuenta":"511005","Descripción":"Junta directiva","Naturaleza":"Debe"},
    {"Cuenta":"511010","Descripción":"Revisoría fiscal","Naturaleza":"Debe"},
    {"Cuenta":"511015","Descripción":"Auditoría externa","Naturaleza":"Debe"},
    {"Cuenta":"511020","Descripción":"Avalúos","Naturaleza":"Debe"},
    {"Cuenta":"511025","Descripción":"Asesoría jurídica","Naturaleza":"Debe"},
    {"Cuenta":"511030","Descripción":"Asesoría financiera","Naturaleza":"Debe"},
    {"Cuenta":"511035","Descripción":"Asesoría técnica","Naturaleza":"Debe"},
    {"Cuenta":"511095","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"511099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5115","Descripción":"Impuestos","Naturaleza":"Debe"},
    {"Cuenta":"511505","Descripción":"Industria y comercio","Naturaleza":"Debe"},
    {"Cuenta":"511510","Descripción":"De timbres","Naturaleza":"Debe"},
    {"Cuenta":"511515","Descripción":"A la propiedad raíz","Naturaleza":"Debe"},
    {"Cuenta":"511520","Descripción":"Derechos sobre instrumentos públicos","Naturaleza":"Debe"},
    {"Cuenta":"511525","Descripción":"De valorización","Naturaleza":"Debe"},
    {"Cuenta":"511530","Descripción":"De turismo","Naturaleza":"Debe"},
    {"Cuenta":"511535","Descripción":"Tasa por utilización de puertos","Naturaleza":"Debe"},
    {"Cuenta":"511540","Descripción":"De vehículos","Naturaleza":"Debe"},
    {"Cuenta":"511545","Descripción":"De espectáculos públicos","Naturaleza":"Debe"},
    {"Cuenta":"511550","Descripción":"Cuotas de fomento","Naturaleza":"Debe"},
    {"Cuenta":"511570","Descripción":"IVA descontable","Naturaleza":"Debe"},
    {"Cuenta":"511595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"511599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5120","Descripción":"Arrendamientos","Naturaleza":"Debe"},
    {"Cuenta":"512005","Descripción":"Terrenos","Naturaleza":"Debe"},
    {"Cuenta":"512010","Descripción":"Construcciones y edificaciones","Naturaleza":"Debe"},
    {"Cuenta":"512015","Descripción":"Maquinaria y equipo","Naturaleza":"Debe"},
    {"Cuenta":"512020","Descripción":"Equipo de oficina","Naturaleza":"Debe"},
    {"Cuenta":"512025","Descripción":"Equipo de computación y comunicación","Naturaleza":"Debe"},
    {"Cuenta":"512030","Descripción":"Equipo médico-científico","Naturaleza":"Debe"},
    {"Cuenta":"512035","Descripción":"Equipo de hoteles y restaurantes","Naturaleza":"Debe"},
    {"Cuenta":"512040","Descripción":"Flota y equipo de transporte","Naturaleza":"Debe"},
    {"Cuenta":"512045","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Debe"},
    {"Cuenta":"512050","Descripción":"Flota y equipo aéreo","Naturaleza":"Debe"},
    {"Cuenta":"512055","Descripción":"Flota y equipo férreo","Naturaleza":"Debe"},
    {"Cuenta":"512060","Descripción":"Acueductos, plantas y redes","Naturaleza":"Debe"},
    {"Cuenta":"512065","Descripción":"Aeródromos","Naturaleza":"Debe"},
    {"Cuenta":"512070","Descripción":"Semovientes","Naturaleza":"Debe"},
    {"Cuenta":"512095","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"512099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5125","Descripción":"Contribuciones y afiliaciones","Naturaleza":"Debe"},
    {"Cuenta":"512505","Descripción":"Contribuciones","Naturaleza":"Debe"},
    {"Cuenta":"512510","Descripción":"Afiliaciones y sostenimiento","Naturaleza":"Debe"},
    {"Cuenta":"512599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5130","Descripción":"Seguros","Naturaleza":"Debe"},
    {"Cuenta":"513005","Descripción":"Manejo","Naturaleza":"Debe"},
    {"Cuenta":"513010","Descripción":"Cumplimiento","Naturaleza":"Debe"},
    {"Cuenta":"513015","Descripción":"Corriente débil","Naturaleza":"Debe"},
    {"Cuenta":"513020","Descripción":"Vida colectiva","Naturaleza":"Debe"},
    {"Cuenta":"513025","Descripción":"Incendio","Naturaleza":"Debe"},
    {"Cuenta":"513030","Descripción":"Terremoto","Naturaleza":"Debe"},
    {"Cuenta":"513035","Descripción":"Sustracción y hurto","Naturaleza":"Debe"},
    {"Cuenta":"513040","Descripción":"Flota y equipo de transporte","Naturaleza":"Debe"},
    {"Cuenta":"513045","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Debe"},
    {"Cuenta":"513050","Descripción":"Flota y equipo aéreo","Naturaleza":"Debe"},
    {"Cuenta":"513055","Descripción":"Flota y equipo férreo","Naturaleza":"Debe"},
    {"Cuenta":"513060","Descripción":"Responsabilidad civil y extracontractual","Naturaleza":"Debe"},
    {"Cuenta":"513065","Descripción":"Vuelo","Naturaleza":"Debe"},
    {"Cuenta":"513070","Descripción":"Rotura de maquinaria","Naturaleza":"Debe"},
    {"Cuenta":"513075","Descripción":"Obligatorio accidente de tránsito","Naturaleza":"Debe"},
    {"Cuenta":"513080","Descripción":"Lucro cesante","Naturaleza":"Debe"},
    {"Cuenta":"513085","Descripción":"Transporte de mercancía","Naturaleza":"Debe"},
    {"Cuenta":"513095","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"513099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5135","Descripción":"Servicios","Naturaleza":"Debe"},
    {"Cuenta":"513505","Descripción":"Aseo y vigilancia","Naturaleza":"Debe"},
    {"Cuenta":"513510","Descripción":"Temporales","Naturaleza":"Debe"},
    {"Cuenta":"513515","Descripción":"Asistencia técnica","Naturaleza":"Debe"},
    {"Cuenta":"513520","Descripción":"Procesamiento electrónico de datos","Naturaleza":"Debe"},
    {"Cuenta":"513525","Descripción":"Acueducto y alcantarillado","Naturaleza":"Debe"},
    {"Cuenta":"513530","Descripción":"Energía eléctrica","Naturaleza":"Debe"},
    {"Cuenta":"513535","Descripción":"Teléfono","Naturaleza":"Debe"},
    {"Cuenta":"513540","Descripción":"Correo, portes y telegramas","Naturaleza":"Debe"},
    {"Cuenta":"513545","Descripción":"Fax y télex","Naturaleza":"Debe"},
    {"Cuenta":"513550","Descripción":"Transporte, fletes y acarreos","Naturaleza":"Debe"},
    {"Cuenta":"513555","Descripción":"Gas","Naturaleza":"Debe"},
    {"Cuenta":"513595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"513599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5140","Descripción":"Gastos legales","Naturaleza":"Debe"},
    {"Cuenta":"514005","Descripción":"Notariales","Naturaleza":"Debe"},
    {"Cuenta":"514010","Descripción":"Registro mercantil","Naturaleza":"Debe"},
    {"Cuenta":"514015","Descripción":"Trámites y licencias","Naturaleza":"Debe"},
    {"Cuenta":"514020","Descripción":"Aduaneros","Naturaleza":"Debe"},
    {"Cuenta":"514025","Descripción":"Consulares","Naturaleza":"Debe"},
    {"Cuenta":"514095","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"514099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5145","Descripción":"Mantenimiento y reparaciones","Naturaleza":"Debe"},
    {"Cuenta":"514505","Descripción":"Terrenos","Naturaleza":"Debe"},
    {"Cuenta":"514510","Descripción":"Construcciones y edificaciones","Naturaleza":"Debe"},
    {"Cuenta":"514515","Descripción":"Maquinaria y equipo","Naturaleza":"Debe"},
    {"Cuenta":"514520","Descripción":"Equipo de oficina","Naturaleza":"Debe"},
    {"Cuenta":"514525","Descripción":"Equipo de computación y comunicación","Naturaleza":"Debe"},
    {"Cuenta":"514530","Descripción":"Equipo médico-científico","Naturaleza":"Debe"},
    {"Cuenta":"514535","Descripción":"Equipo de hoteles y restaurantes","Naturaleza":"Debe"},
    {"Cuenta":"514540","Descripción":"Flota y equipo de transporte","Naturaleza":"Debe"},
    {"Cuenta":"514545","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Debe"},
    {"Cuenta":"514550","Descripción":"Flota y equipo aéreo","Naturaleza":"Debe"},
    {"Cuenta":"514555","Descripción":"Flota y equipo férreo","Naturaleza":"Debe"},
    {"Cuenta":"514560","Descripción":"Acueductos, plantas y redes","Naturaleza":"Debe"},
    {"Cuenta":"514565","Descripción":"Armamento de vigilancia","Naturaleza":"Debe"},
    {"Cuenta":"514570","Descripción":"Vías de comunicación","Naturaleza":"Debe"},
    {"Cuenta":"514599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5150","Descripción":"Adecuación e instalación","Naturaleza":"Debe"},
    {"Cuenta":"515005","Descripción":"Instalaciones eléctricas","Naturaleza":"Debe"},
    {"Cuenta":"515010","Descripción":"Arreglos ornamentales","Naturaleza":"Debe"},
    {"Cuenta":"515015","Descripción":"Reparaciones locativas","Naturaleza":"Debe"},
    {"Cuenta":"515095","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"515099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5155","Descripción":"Gastos de viaje","Naturaleza":"Debe"},
    {"Cuenta":"515505","Descripción":"Alojamiento y manutención","Naturaleza":"Debe"},
    {"Cuenta":"515510","Descripción":"Pasajes fluviales y/o marítimos","Naturaleza":"Debe"},
    {"Cuenta":"515515","Descripción":"Pasajes aéreos","Naturaleza":"Debe"},
    {"Cuenta":"515520","Descripción":"Pasajes terrestres","Naturaleza":"Debe"},
    {"Cuenta":"515525","Descripción":"Pasajes férreos","Naturaleza":"Debe"},
    {"Cuenta":"515595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"515599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5160","Descripción":"Depreciaciones","Naturaleza":"Debe"},
    {"Cuenta":"516005","Descripción":"Construcciones y edificaciones","Naturaleza":"Debe"},
    {"Cuenta":"516010","Descripción":"Maquinaria y equipo","Naturaleza":"Debe"},
    {"Cuenta":"516015","Descripción":"Equipo de oficina","Naturaleza":"Debe"},
    {"Cuenta":"516020","Descripción":"Equipo de computación y comunicación","Naturaleza":"Debe"},
    {"Cuenta":"516025","Descripción":"Equipo médico-científico","Naturaleza":"Debe"},
    {"Cuenta":"516030","Descripción":"Equipo de hoteles y restaurantes","Naturaleza":"Debe"},
    {"Cuenta":"516035","Descripción":"Flota y equipo de transporte","Naturaleza":"Debe"},
    {"Cuenta":"516040","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Debe"},
    {"Cuenta":"516045","Descripción":"Flota y equipo aéreo","Naturaleza":"Debe"},
    {"Cuenta":"516050","Descripción":"Flota y equipo férreo","Naturaleza":"Debe"},
    {"Cuenta":"516055","Descripción":"Acueductos, plantas y redes","Naturaleza":"Debe"},
    {"Cuenta":"516060","Descripción":"Armamento de vigilancia","Naturaleza":"Debe"},
    {"Cuenta":"516099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5165","Descripción":"Amortizaciones","Naturaleza":"Debe"},
    {"Cuenta":"516505","Descripción":"Vías de comunicación","Naturaleza":"Debe"},
    {"Cuenta":"516510","Descripción":"Intangibles","Naturaleza":"Debe"},
    {"Cuenta":"516515","Descripción":"Cargos diferidos","Naturaleza":"Debe"},
    {"Cuenta":"516595","Descripción":"Otras","Naturaleza":"Debe"},
    {"Cuenta":"516599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5195","Descripción":"Diversos","Naturaleza":"Debe"},
    {"Cuenta":"519505","Descripción":"Comisiones","Naturaleza":"Debe"},
    {"Cuenta":"519510","Descripción":"Libros, suscripciones, periódicos y revistas","Naturaleza":"Debe"},
    {"Cuenta":"519515","Descripción":"Música ambiental","Naturaleza":"Debe"},
    {"Cuenta":"519520","Descripción":"Gastos de representación y relaciones públicas","Naturaleza":"Debe"},
    {"Cuenta":"519525","Descripción":"Elementos de aseo y cafetería","Naturaleza":"Debe"},
    {"Cuenta":"519530","Descripción":"Útiles, papelería y fotocopias","Naturaleza":"Debe"},
    {"Cuenta":"519535","Descripción":"Combustibles y lubricantes","Naturaleza":"Debe"},
    {"Cuenta":"519540","Descripción":"Envases y empaques","Naturaleza":"Debe"},
    {"Cuenta":"519545","Descripción":"Taxis y buses","Naturaleza":"Debe"},
    {"Cuenta":"519550","Descripción":"Estampillas","Naturaleza":"Debe"},
    {"Cuenta":"519555","Descripción":"Microfilmación","Naturaleza":"Debe"},
    {"Cuenta":"519560","Descripción":"Casino y restaurante","Naturaleza":"Debe"},
    {"Cuenta":"519565","Descripción":"Parqueaderos","Naturaleza":"Debe"},
    {"Cuenta":"519570","Descripción":"Indemnización por daños a terceros","Naturaleza":"Debe"},
    {"Cuenta":"519575","Descripción":"Pólvora y similares","Naturaleza":"Debe"},
    {"Cuenta":"519595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"519599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5199","Descripción":"Provisiones","Naturaleza":"Debe"},
    {"Cuenta":"519905","Descripción":"Inversiones","Naturaleza":"Debe"},
    {"Cuenta":"519910","Descripción":"Deudores","Naturaleza":"Debe"},
    {"Cuenta":"519915","Descripción":"Propiedades, planta y equipo","Naturaleza":"Debe"},
    {"Cuenta":"519995","Descripción":"Otros activos","Naturaleza":"Debe"},
    {"Cuenta":"519999","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"52","Descripción":"Operacionales de ventas","Naturaleza":"Debe"},
    {"Cuenta":"5205","Descripción":"Gastos de personal","Naturaleza":"Debe"},
    {"Cuenta":"520503","Descripción":"Salario integral","Naturaleza":"Debe"},
    {"Cuenta":"520506","Descripción":"Sueldos","Naturaleza":"Debe"},
    {"Cuenta":"520512","Descripción":"Jornales","Naturaleza":"Debe"},
    {"Cuenta":"520515","Descripción":"Horas extras y recargos","Naturaleza":"Debe"},
    {"Cuenta":"520518","Descripción":"Comisiones","Naturaleza":"Debe"},
    {"Cuenta":"520521","Descripción":"Viáticos","Naturaleza":"Debe"},
    {"Cuenta":"520524","Descripción":"Incapacidades","Naturaleza":"Debe"},
    {"Cuenta":"520527","Descripción":"Auxilio de transporte","Naturaleza":"Debe"},
    {"Cuenta":"520530","Descripción":"Cesantías","Naturaleza":"Debe"},
    {"Cuenta":"520533","Descripción":"Intereses sobre cesantías","Naturaleza":"Debe"},
    {"Cuenta":"520536","Descripción":"Prima de servicios","Naturaleza":"Debe"},
    {"Cuenta":"520539","Descripción":"Vacaciones","Naturaleza":"Debe"},
    {"Cuenta":"520542","Descripción":"Primas extralegales","Naturaleza":"Debe"},
    {"Cuenta":"520545","Descripción":"Auxilios","Naturaleza":"Debe"},
    {"Cuenta":"520548","Descripción":"Bonificaciones","Naturaleza":"Debe"},
    {"Cuenta":"520551","Descripción":"Dotación y suministro a trabajadores","Naturaleza":"Debe"},
    {"Cuenta":"520554","Descripción":"Seguros","Naturaleza":"Debe"},
    {"Cuenta":"520557","Descripción":"Cuotas partes pensiones de jubilación","Naturaleza":"Debe"},
    {"Cuenta":"520558","Descripción":"Amortización cálculo actuarial pensiones de jubilación","Naturaleza":"Debe"},
    {"Cuenta":"520559","Descripción":"Pensiones de jubilación","Naturaleza":"Debe"},
    {"Cuenta":"520560","Descripción":"Indemnizaciones laborales","Naturaleza":"Debe"},
    {"Cuenta":"520561","Descripción":"Amortización bonos pensionales","Naturaleza":"Debe"},
    {"Cuenta":"520562","Descripción":"Amortización títulos pensionales","Naturaleza":"Debe"},
    {"Cuenta":"520563","Descripción":"Capacitación al personal","Naturaleza":"Debe"},
    {"Cuenta":"520566","Descripción":"Gastos deportivos y de recreación","Naturaleza":"Debe"},
    {"Cuenta":"520568","Descripción":"Aportes a administradoras de riesgos profesionales, ARP","Naturaleza":"Debe"},
    {"Cuenta":"520569","Descripción":"Aportes a entidades promotoras de salud, EPS","Naturaleza":"Debe"},
    {"Cuenta":"520570","Descripción":"Aportes a fondos de pensiones y/o cesantías","Naturaleza":"Debe"},
    {"Cuenta":"520572","Descripción":"Aportes cajas de compensación familiar","Naturaleza":"Debe"},
    {"Cuenta":"520575","Descripción":"Aportes ICBF","Naturaleza":"Debe"},
    {"Cuenta":"520578","Descripción":"SENA","Naturaleza":"Debe"},
    {"Cuenta":"520581","Descripción":"Aportes sindicales","Naturaleza":"Debe"},
    {"Cuenta":"520584","Descripción":"Gastos médicos y drogas","Naturaleza":"Debe"},
    {"Cuenta":"520595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"520599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5210","Descripción":"Honorarios","Naturaleza":"Debe"},
    {"Cuenta":"521005","Descripción":"Junta directiva","Naturaleza":"Debe"},
    {"Cuenta":"521010","Descripción":"Revisoría fiscal","Naturaleza":"Debe"},
    {"Cuenta":"521015","Descripción":"Auditoría externa","Naturaleza":"Debe"},
    {"Cuenta":"521020","Descripción":"Avalúos","Naturaleza":"Debe"},
    {"Cuenta":"521025","Descripción":"Asesoría jurídica","Naturaleza":"Debe"},
    {"Cuenta":"521030","Descripción":"Asesoría financiera","Naturaleza":"Debe"},
    {"Cuenta":"521035","Descripción":"Asesoría técnica","Naturaleza":"Debe"},
    {"Cuenta":"521095","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"521099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5215","Descripción":"Impuestos","Naturaleza":"Debe"},
    {"Cuenta":"521505","Descripción":"Industria y comercio","Naturaleza":"Debe"},
    {"Cuenta":"521510","Descripción":"De timbres","Naturaleza":"Debe"},
    {"Cuenta":"521515","Descripción":"A la propiedad raíz","Naturaleza":"Debe"},
    {"Cuenta":"521520","Descripción":"Derechos sobre instrumentos públicos","Naturaleza":"Debe"},
    {"Cuenta":"521525","Descripción":"De valorización","Naturaleza":"Debe"},
    {"Cuenta":"521530","Descripción":"De turismo","Naturaleza":"Debe"},
    {"Cuenta":"521535","Descripción":"Tasa por utilización de puertos","Naturaleza":"Debe"},
    {"Cuenta":"521540","Descripción":"De vehículos","Naturaleza":"Debe"},
    {"Cuenta":"521545","Descripción":"De espectáculos públicos","Naturaleza":"Debe"},
    {"Cuenta":"521550","Descripción":"Cuotas de fomento","Naturaleza":"Debe"},
    {"Cuenta":"521555","Descripción":"Licores","Naturaleza":"Debe"},
    {"Cuenta":"521560","Descripción":"Cervezas","Naturaleza":"Debe"},
    {"Cuenta":"521565","Descripción":"Cigarrillos","Naturaleza":"Debe"},
    {"Cuenta":"521570","Descripción":"IVA descontable","Naturaleza":"Debe"},
    {"Cuenta":"521595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"521599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5220","Descripción":"Arrendamientos","Naturaleza":"Debe"},
    {"Cuenta":"522005","Descripción":"Terrenos","Naturaleza":"Debe"},
    {"Cuenta":"522010","Descripción":"Construcciones y edificaciones","Naturaleza":"Debe"},
    {"Cuenta":"522015","Descripción":"Maquinaria y equipo","Naturaleza":"Debe"},
    {"Cuenta":"522020","Descripción":"Equipo de oficina","Naturaleza":"Debe"},
    {"Cuenta":"522025","Descripción":"Equipo de computación y comunicación","Naturaleza":"Debe"},
    {"Cuenta":"522030","Descripción":"Equipo médico-científico","Naturaleza":"Debe"},
    {"Cuenta":"522035","Descripción":"Equipo de hoteles y restaurantes","Naturaleza":"Debe"},
    {"Cuenta":"522040","Descripción":"Flota y equipo de transporte","Naturaleza":"Debe"},
    {"Cuenta":"522045","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Debe"},
    {"Cuenta":"522050","Descripción":"Flota y equipo aéreo","Naturaleza":"Debe"},
    {"Cuenta":"522055","Descripción":"Flota y equipo férreo","Naturaleza":"Debe"},
    {"Cuenta":"522060","Descripción":"Acueductos, plantas y redes","Naturaleza":"Debe"},
    {"Cuenta":"522065","Descripción":"Aeródromos","Naturaleza":"Debe"},
    {"Cuenta":"522070","Descripción":"Semovientes","Naturaleza":"Debe"},
    {"Cuenta":"522095","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"522099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5225","Descripción":"Contribuciones y afiliaciones","Naturaleza":"Debe"},
    {"Cuenta":"522505","Descripción":"Contribuciones","Naturaleza":"Debe"},
    {"Cuenta":"522510","Descripción":"Afiliaciones y sostenimiento","Naturaleza":"Debe"},
    {"Cuenta":"522599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5230","Descripción":"Seguros","Naturaleza":"Debe"},
    {"Cuenta":"523005","Descripción":"Manejo","Naturaleza":"Debe"},
    {"Cuenta":"523010","Descripción":"Cumplimiento","Naturaleza":"Debe"},
    {"Cuenta":"523015","Descripción":"Corriente débil","Naturaleza":"Debe"},
    {"Cuenta":"523020","Descripción":"Vida colectiva","Naturaleza":"Debe"},
    {"Cuenta":"523025","Descripción":"Incendio","Naturaleza":"Debe"},
    {"Cuenta":"523030","Descripción":"Terremoto","Naturaleza":"Debe"},
    {"Cuenta":"523035","Descripción":"Sustracción y hurto","Naturaleza":"Debe"},
    {"Cuenta":"523040","Descripción":"Flota y equipo de transporte","Naturaleza":"Debe"},
    {"Cuenta":"523045","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Debe"},
    {"Cuenta":"523050","Descripción":"Flota y equipo aéreo","Naturaleza":"Debe"},
    {"Cuenta":"523055","Descripción":"Flota y equipo férreo","Naturaleza":"Debe"},
    {"Cuenta":"523060","Descripción":"Responsabilidad civil y extracontractual","Naturaleza":"Debe"},
    {"Cuenta":"523065","Descripción":"Vuelo","Naturaleza":"Debe"},
    {"Cuenta":"523070","Descripción":"Rotura de maquinaria","Naturaleza":"Debe"},
    {"Cuenta":"523075","Descripción":"Obligatorio accidente de tránsito","Naturaleza":"Debe"},
    {"Cuenta":"523080","Descripción":"Lucro cesante","Naturaleza":"Debe"},
    {"Cuenta":"523095","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"523099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5235","Descripción":"Servicios","Naturaleza":"Debe"},
    {"Cuenta":"523505","Descripción":"Aseo y vigilancia","Naturaleza":"Debe"},
    {"Cuenta":"523510","Descripción":"Temporales","Naturaleza":"Debe"},
    {"Cuenta":"523515","Descripción":"Asistencia técnica","Naturaleza":"Debe"},
    {"Cuenta":"523520","Descripción":"Procesamiento electrónico de datos","Naturaleza":"Debe"},
    {"Cuenta":"523525","Descripción":"Acueducto y alcantarillado","Naturaleza":"Debe"},
    {"Cuenta":"523530","Descripción":"Energía eléctrica","Naturaleza":"Debe"},
    {"Cuenta":"523535","Descripción":"Teléfono","Naturaleza":"Debe"},
    {"Cuenta":"523540","Descripción":"Correo, portes y telegramas","Naturaleza":"Debe"},
    {"Cuenta":"523545","Descripción":"Fax y télex","Naturaleza":"Debe"},
    {"Cuenta":"523550","Descripción":"Transporte, fletes y acarreos","Naturaleza":"Debe"},
    {"Cuenta":"523555","Descripción":"Gas","Naturaleza":"Debe"},
    {"Cuenta":"523560","Descripción":"Publicidad, propaganda y promoción","Naturaleza":"Debe"},
    {"Cuenta":"523595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"523599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5240","Descripción":"Gastos legales","Naturaleza":"Debe"},
    {"Cuenta":"524005","Descripción":"Notariales","Naturaleza":"Debe"},
    {"Cuenta":"524010","Descripción":"Registro mercantil","Naturaleza":"Debe"},
    {"Cuenta":"524015","Descripción":"Trámites y licencias","Naturaleza":"Debe"},
    {"Cuenta":"524020","Descripción":"Aduaneros","Naturaleza":"Debe"},
    {"Cuenta":"524025","Descripción":"Consulares","Naturaleza":"Debe"},
    {"Cuenta":"524095","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"524099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5245","Descripción":"Mantenimiento y reparaciones","Naturaleza":"Debe"},
    {"Cuenta":"524505","Descripción":"Terrenos","Naturaleza":"Debe"},
    {"Cuenta":"524510","Descripción":"Construcciones y edificaciones","Naturaleza":"Debe"},
    {"Cuenta":"524515","Descripción":"Maquinaria y equipo","Naturaleza":"Debe"},
    {"Cuenta":"524520","Descripción":"Equipo de oficina","Naturaleza":"Debe"},
    {"Cuenta":"524525","Descripción":"Equipo de computación y comunicación","Naturaleza":"Debe"},
    {"Cuenta":"524530","Descripción":"Equipo médico-científico","Naturaleza":"Debe"},
    {"Cuenta":"524535","Descripción":"Equipo de hoteles y restaurantes","Naturaleza":"Debe"},
    {"Cuenta":"524540","Descripción":"Flota y equipo de transporte","Naturaleza":"Debe"},
    {"Cuenta":"524545","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Debe"},
    {"Cuenta":"524550","Descripción":"Flota y equipo aéreo","Naturaleza":"Debe"},
    {"Cuenta":"524555","Descripción":"Flota y equipo férreo","Naturaleza":"Debe"},
    {"Cuenta":"524560","Descripción":"Acueductos, plantas y redes","Naturaleza":"Debe"},
    {"Cuenta":"524565","Descripción":"Armamento de vigilancia","Naturaleza":"Debe"},
    {"Cuenta":"524570","Descripción":"Vías de comunicación","Naturaleza":"Debe"},
    {"Cuenta":"524599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5250","Descripción":"Adecuación e instalación","Naturaleza":"Debe"},
    {"Cuenta":"525005","Descripción":"Instalaciones eléctricas","Naturaleza":"Debe"},
    {"Cuenta":"525010","Descripción":"Arreglos ornamentales","Naturaleza":"Debe"},
    {"Cuenta":"525015","Descripción":"Reparaciones locativas","Naturaleza":"Debe"},
    {"Cuenta":"525095","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"525099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5255","Descripción":"Gastos de viaje","Naturaleza":"Debe"},
    {"Cuenta":"525505","Descripción":"Alojamiento y manutención","Naturaleza":"Debe"},
    {"Cuenta":"525510","Descripción":"Pasajes fluviales y/o marítimos","Naturaleza":"Debe"},
    {"Cuenta":"525515","Descripción":"Pasajes aéreos","Naturaleza":"Debe"},
    {"Cuenta":"525520","Descripción":"Pasajes terrestres","Naturaleza":"Debe"},
    {"Cuenta":"525525","Descripción":"Pasajes férreos","Naturaleza":"Debe"},
    {"Cuenta":"525595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"525599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5260","Descripción":"Depreciaciones","Naturaleza":"Debe"},
    {"Cuenta":"526005","Descripción":"Construcciones y edificaciones","Naturaleza":"Debe"},
    {"Cuenta":"526010","Descripción":"Maquinaria y equipo","Naturaleza":"Debe"},
    {"Cuenta":"526015","Descripción":"Equipo de oficina","Naturaleza":"Debe"},
    {"Cuenta":"526020","Descripción":"Equipo de computación y comunicación","Naturaleza":"Debe"},
    {"Cuenta":"526025","Descripción":"Equipo médico-científico","Naturaleza":"Debe"},
    {"Cuenta":"526030","Descripción":"Equipo de hoteles y restaurantes","Naturaleza":"Debe"},
    {"Cuenta":"526035","Descripción":"Flota y equipo de transporte","Naturaleza":"Debe"},
    {"Cuenta":"526040","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Debe"},
    {"Cuenta":"526045","Descripción":"Flota y equipo aéreo","Naturaleza":"Debe"},
    {"Cuenta":"526050","Descripción":"Flota y equipo férreo","Naturaleza":"Debe"},
    {"Cuenta":"526055","Descripción":"Acueductos, plantas y redes","Naturaleza":"Debe"},
    {"Cuenta":"526060","Descripción":"Armamento de vigilancia","Naturaleza":"Debe"},
    {"Cuenta":"526065","Descripción":"Envases y empaques","Naturaleza":"Debe"},
    {"Cuenta":"526099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5265","Descripción":"Amortizaciones","Naturaleza":"Debe"},
    {"Cuenta":"526505","Descripción":"Vías de comunicación","Naturaleza":"Debe"},
    {"Cuenta":"526510","Descripción":"Intangibles","Naturaleza":"Debe"},
    {"Cuenta":"526515","Descripción":"Cargos diferidos","Naturaleza":"Debe"},
    {"Cuenta":"526595","Descripción":"Otras","Naturaleza":"Debe"},
    {"Cuenta":"526599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5270","Descripción":"Financieros-reajuste del sistema","Naturaleza":"Debe"},
    {"Cuenta":"527099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5275","Descripción":"Pérdidas método de participación","Naturaleza":"Debe"},
    {"Cuenta":"527505","Descripción":"De sociedades anónimas y/o asimiladas","Naturaleza":"Debe"},
    {"Cuenta":"527510","Descripción":"De sociedades limitadas y/o asimiladas","Naturaleza":"Debe"},
    {"Cuenta":"5295","Descripción":"Diversos","Naturaleza":"Debe"},
    {"Cuenta":"529505","Descripción":"Comisiones","Naturaleza":"Debe"},
    {"Cuenta":"529510","Descripción":"Libros, suscripciones, periódicos y revistas","Naturaleza":"Debe"},
    {"Cuenta":"529515","Descripción":"Música ambiental","Naturaleza":"Debe"},
    {"Cuenta":"529520","Descripción":"Gastos de representación y relaciones públicas","Naturaleza":"Debe"},
    {"Cuenta":"529525","Descripción":"Elementos de aseo y cafetería","Naturaleza":"Debe"},
    {"Cuenta":"529530","Descripción":"Útiles, papelería y fotocopias","Naturaleza":"Debe"},
    {"Cuenta":"529535","Descripción":"Combustibles y lubricantes","Naturaleza":"Debe"},
    {"Cuenta":"529540","Descripción":"Envases y empaques","Naturaleza":"Debe"},
    {"Cuenta":"529545","Descripción":"Taxis y buses","Naturaleza":"Debe"},
    {"Cuenta":"529550","Descripción":"Estampillas","Naturaleza":"Debe"},
    {"Cuenta":"529555","Descripción":"Microfilmación","Naturaleza":"Debe"},
    {"Cuenta":"529560","Descripción":"Casino y restaurante","Naturaleza":"Debe"},
    {"Cuenta":"529565","Descripción":"Parqueaderos","Naturaleza":"Debe"},
    {"Cuenta":"529570","Descripción":"Indemnización por daños a terceros","Naturaleza":"Debe"},
    {"Cuenta":"529575","Descripción":"Pólvora y similares","Naturaleza":"Debe"},
    {"Cuenta":"529595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"529599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5299","Descripción":"Provisiones","Naturaleza":"Debe"},
    {"Cuenta":"529905","Descripción":"Inversiones","Naturaleza":"Debe"},
    {"Cuenta":"529910","Descripción":"Deudores","Naturaleza":"Debe"},
    {"Cuenta":"529915","Descripción":"Inventarios","Naturaleza":"Debe"},
    {"Cuenta":"529920","Descripción":"Propiedades, planta y equipo","Naturaleza":"Debe"},
    {"Cuenta":"529995","Descripción":"Otros activos","Naturaleza":"Debe"},
    {"Cuenta":"529999","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"53","Descripción":"No operacionales","Naturaleza":"Debe"},
    {"Cuenta":"5305","Descripción":"Financieros","Naturaleza":"Debe"},
    {"Cuenta":"530505","Descripción":"Gastos bancarios","Naturaleza":"Debe"},
    {"Cuenta":"530510","Descripción":"Reajuste monetario-UPAC (hoy UVR)","Naturaleza":"Debe"},
    {"Cuenta":"530515","Descripción":"Comisiones","Naturaleza":"Debe"},
    {"Cuenta":"530520","Descripción":"Intereses","Naturaleza":"Debe"},
    {"Cuenta":"530525","Descripción":"Diferencia en cambio","Naturaleza":"Debe"},
    {"Cuenta":"530530","Descripción":"Gastos en negociación certificados de cambio","Naturaleza":"Debe"},
    {"Cuenta":"530535","Descripción":"Descuentos comerciales condicionados","Naturaleza":"Debe"},
    {"Cuenta":"530540","Descripción":"Gastos manejo y emisión de bonos","Naturaleza":"Debe"},
    {"Cuenta":"530545","Descripción":"Prima amortizada","Naturaleza":"Debe"},
    {"Cuenta":"530595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"530599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5310","Descripción":"Pérdida en venta y retiro de bienes","Naturaleza":"Debe"},
    {"Cuenta":"531005","Descripción":"Venta de inversiones","Naturaleza":"Debe"},
    {"Cuenta":"531010","Descripción":"Venta de cartera","Naturaleza":"Debe"},
    {"Cuenta":"531015","Descripción":"Venta de propiedades, planta y equipo","Naturaleza":"Debe"},
    {"Cuenta":"531020","Descripción":"Venta de intangibles","Naturaleza":"Debe"},
    {"Cuenta":"531025","Descripción":"Venta de otros activos","Naturaleza":"Debe"},
    {"Cuenta":"531030","Descripción":"Retiro de propiedades, planta y equipo","Naturaleza":"Debe"},
    {"Cuenta":"531035","Descripción":"Retiro de otros activos","Naturaleza":"Debe"},
    {"Cuenta":"531040","Descripción":"Pérdidas por siniestros","Naturaleza":"Debe"},
    {"Cuenta":"531095","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"531099","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5313","Descripción":"Pérdidas método de participación","Naturaleza":"Debe"},
    {"Cuenta":"531305","Descripción":"De sociedades anónimas y/o asimiladas","Naturaleza":"Debe"},
    {"Cuenta":"531310","Descripción":"De sociedades limitadas y/o asimiladas","Naturaleza":"Debe"},
    {"Cuenta":"5315","Descripción":"Gastos extraordinarios","Naturaleza":"Debe"},
    {"Cuenta":"531505","Descripción":"Costas y procesos judiciales","Naturaleza":"Debe"},
    {"Cuenta":"531510","Descripción":"Actividades culturales y cívicas","Naturaleza":"Debe"},
    {"Cuenta":"531515","Descripción":"Costos y gastos de ejercicios anteriores","Naturaleza":"Debe"},
    {"Cuenta":"531520","Descripción":"Impuestos asumidos","Naturaleza":"Debe"},
    {"Cuenta":"531595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"531599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"5395","Descripción":"Gastos diversos","Naturaleza":"Debe"},
    {"Cuenta":"539505","Descripción":"Demandas laborales","Naturaleza":"Debe"},
    {"Cuenta":"539510","Descripción":"Demandas por incumplimiento de contratos","Naturaleza":"Debe"},
    {"Cuenta":"539515","Descripción":"Indemnizaciones","Naturaleza":"Debe"},
    {"Cuenta":"539520","Descripción":"Multas, sanciones y litigios","Naturaleza":"Debe"},
    {"Cuenta":"539525","Descripción":"Donaciones","Naturaleza":"Debe"},
    {"Cuenta":"539530","Descripción":"Constitución de garantías","Naturaleza":"Debe"},
    {"Cuenta":"539535","Descripción":"Amortización de bienes entregados en comodato","Naturaleza":"Debe"},
    {"Cuenta":"539595","Descripción":"Otros","Naturaleza":"Debe"},
    {"Cuenta":"539599","Descripción":"Ajustes por inflación","Naturaleza":"Debe"},
    {"Cuenta":"54","Descripción":"Impuesto de renta y complementarios","Naturaleza":"Debe"},
    {"Cuenta":"5405","Descripción":"Impuesto de renta y complementarios","Naturaleza":"Debe"},
    {"Cuenta":"540505","Descripción":"Impuesto de renta y complementarios","Naturaleza":"Debe"},
    {"Cuenta":"59","Descripción":"Ganancias y pérdidas","Naturaleza":"Debe"},
    {"Cuenta":"5905","Descripción":"Ganancias y pérdidas","Naturaleza":"Debe"},
    {"Cuenta":"590505","Descripción":"Ganancias y pérdidas","Naturaleza":"Debe"},
]