export const Ingresos = [
    {"Cuenta":"4","Descripción":"Ingresos","Naturaleza":"Haber"},
    {"Cuenta":"41","Descripción":"Operacionales","Naturaleza":"Haber"},
    {"Cuenta":"4105","Descripción":"Agricultura, ganadería, caza y silvicultura","Naturaleza":"Haber"},
    {"Cuenta":"410505","Descripción":"Cultivo de cereales","Naturaleza":"Haber"},
    {"Cuenta":"410510","Descripción":"Cultivos de hortalizas, legumbres y plantas ornamentales","Naturaleza":"Haber"},
    {"Cuenta":"410515","Descripción":"Cultivos de frutas, nueces y plantas aromáticas","Naturaleza":"Haber"},
    {"Cuenta":"410520","Descripción":"Cultivo de café","Naturaleza":"Haber"},
    {"Cuenta":"410525","Descripción":"Cultivo de flores","Naturaleza":"Haber"},
    {"Cuenta":"410530","Descripción":"Cultivo de caña de azúcar","Naturaleza":"Haber"},
    {"Cuenta":"410535","Descripción":"Cultivo de algodón y plantas para material textil","Naturaleza":"Haber"},
    {"Cuenta":"410540","Descripción":"Cultivo de banano","Naturaleza":"Haber"},
    {"Cuenta":"410545","Descripción":"Otros cultivos agrícolas","Naturaleza":"Haber"},
    {"Cuenta":"410550","Descripción":"Cría de ovejas, cabras, asnos, mulas y burdéganos","Naturaleza":"Haber"},
    {"Cuenta":"410555","Descripción":"Cría de ganado caballar y vacuno","Naturaleza":"Haber"},
    {"Cuenta":"410560","Descripción":"Producción avícola","Naturaleza":"Haber"},
    {"Cuenta":"410565","Descripción":"Cría de otros animales","Naturaleza":"Haber"},
    {"Cuenta":"410570","Descripción":"Servicios agrícolas y ganaderos","Naturaleza":"Haber"},
    {"Cuenta":"410575","Descripción":"Actividad de caza","Naturaleza":"Haber"},
    {"Cuenta":"410580","Descripción":"Actividad de silvicultura","Naturaleza":"Haber"},
    {"Cuenta":"410595","Descripción":"Actividades conexas","Naturaleza":"Haber"},
    {"Cuenta":"410599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4110","Descripción":"Pesca","Naturaleza":"Haber"},
    {"Cuenta":"411005","Descripción":"Actividad de pesca","Naturaleza":"Haber"},
    {"Cuenta":"411010","Descripción":"Explotación de criaderos de peces","Naturaleza":"Haber"},
    {"Cuenta":"411095","Descripción":"Actividades conexas","Naturaleza":"Haber"},
    {"Cuenta":"411099","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4115","Descripción":"Explotación de minas y canteras","Naturaleza":"Haber"},
    {"Cuenta":"411505","Descripción":"Carbón","Naturaleza":"Haber"},
    {"Cuenta":"411510","Descripción":"Petróleo crudo","Naturaleza":"Haber"},
    {"Cuenta":"411512","Descripción":"Gas natural","Naturaleza":"Haber"},
    {"Cuenta":"411514","Descripción":"Servicios relacionados con extracción de petróleo y gas","Naturaleza":"Haber"},
    {"Cuenta":"411515","Descripción":"Minerales de hierro","Naturaleza":"Haber"},
    {"Cuenta":"411520","Descripción":"Minerales metalíferos no ferrosos","Naturaleza":"Haber"},
    {"Cuenta":"411525","Descripción":"Piedra, arena y arcilla","Naturaleza":"Haber"},
    {"Cuenta":"411527","Descripción":"Piedras preciosas","Naturaleza":"Haber"},
    {"Cuenta":"411528","Descripción":"Oro","Naturaleza":"Haber"},
    {"Cuenta":"411530","Descripción":"Otras minas y canteras","Naturaleza":"Haber"},
    {"Cuenta":"411532","Descripción":"Prestación de servicios sector minero","Naturaleza":"Haber"},
    {"Cuenta":"411595","Descripción":"Actividades conexas","Naturaleza":"Haber"},
    {"Cuenta":"411599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4120","Descripción":"Industrias manufactureras","Naturaleza":"Haber"},
    {"Cuenta":"412001","Descripción":"Producción y procesamiento de carnes y productos cárnicos","Naturaleza":"Haber"},
    {"Cuenta":"412002","Descripción":"Productos de pescado","Naturaleza":"Haber"},
    {"Cuenta":"412003","Descripción":"Productos de frutas, legumbres y hortalizas","Naturaleza":"Haber"},
    {"Cuenta":"412004","Descripción":"Elaboración de aceites y grasas","Naturaleza":"Haber"},
    {"Cuenta":"412005","Descripción":"Elaboración de productos lácteos","Naturaleza":"Haber"},
    {"Cuenta":"412006","Descripción":"Elaboración de productos de molinería","Naturaleza":"Haber"},
    {"Cuenta":"412007","Descripción":"Elaboración de almidones y derivados","Naturaleza":"Haber"},
    {"Cuenta":"412008","Descripción":"Elaboración de alimentos para animales","Naturaleza":"Haber"},
    {"Cuenta":"412009","Descripción":"Elaboración de productos para panadería","Naturaleza":"Haber"},
    {"Cuenta":"412010","Descripción":"Elaboración de azúcar y melazas","Naturaleza":"Haber"},
    {"Cuenta":"412011","Descripción":"Elaboración de cacao, chocolate y confitería","Naturaleza":"Haber"},
    {"Cuenta":"412012","Descripción":"Elaboración de pastas y productos farináceos","Naturaleza":"Haber"},
    {"Cuenta":"412013","Descripción":"Elaboración de productos de café","Naturaleza":"Haber"},
    {"Cuenta":"412014","Descripción":"Elaboración de otros productos alimenticios","Naturaleza":"Haber"},
    {"Cuenta":"412015","Descripción":"Elaboración de bebidas alcohólicas y alcohol etílico","Naturaleza":"Haber"},
    {"Cuenta":"412016","Descripción":"Elaboración de vinos","Naturaleza":"Haber"},
    {"Cuenta":"412017","Descripción":"Elaboración de bebidas malteadas y de malta","Naturaleza":"Haber"},
    {"Cuenta":"412018","Descripción":"Elaboración de bebidas no alcohólicas","Naturaleza":"Haber"},
    {"Cuenta":"412019","Descripción":"Elaboración de productos de tabaco","Naturaleza":"Haber"},
    {"Cuenta":"412020","Descripción":"Preparación e hilatura de fibras textiles y tejeduría","Naturaleza":"Haber"},
    {"Cuenta":"412021","Descripción":"Acabado de productos textiles","Naturaleza":"Haber"},
    {"Cuenta":"412022","Descripción":"Elaboración de artículos de materiales textiles","Naturaleza":"Haber"},
    {"Cuenta":"412023","Descripción":"Elaboración de tapices y alfombras","Naturaleza":"Haber"},
    {"Cuenta":"412024","Descripción":"Elaboración de cuerdas, cordeles, bramantes y redes","Naturaleza":"Haber"},
    {"Cuenta":"412025","Descripción":"Elaboración de otros productos textiles","Naturaleza":"Haber"},
    {"Cuenta":"412026","Descripción":"Elaboración de tejidos","Naturaleza":"Haber"},
    {"Cuenta":"412027","Descripción":"Elaboración de prendas de vestir","Naturaleza":"Haber"},
    {"Cuenta":"412028","Descripción":"Preparación, adobo y teñido de pieles","Naturaleza":"Haber"},
    {"Cuenta":"412029","Descripción":"Curtido, adobo o preparación de cuero","Naturaleza":"Haber"},
    {"Cuenta":"412030","Descripción":"Elaboración de maletas, bolsos y similares","Naturaleza":"Haber"},
    {"Cuenta":"412031","Descripción":"Elaboración de calzado","Naturaleza":"Haber"},
    {"Cuenta":"412032","Descripción":"Producción de madera, artículos de madera y corcho","Naturaleza":"Haber"},
    {"Cuenta":"412033","Descripción":"Elaboración de pasta y productos de madera, papel y cartón","Naturaleza":"Haber"},
    {"Cuenta":"412034","Descripción":"Ediciones y publicaciones","Naturaleza":"Haber"},
    {"Cuenta":"412035","Descripción":"Impresión","Naturaleza":"Haber"},
    {"Cuenta":"412036","Descripción":"Servicios relacionados con la edición y la impresión","Naturaleza":"Haber"},
    {"Cuenta":"412037","Descripción":"Reproducción de grabaciones","Naturaleza":"Haber"},
    {"Cuenta":"412038","Descripción":"Elaboración de productos de horno de coque","Naturaleza":"Haber"},
    {"Cuenta":"412039","Descripción":"Elaboración de productos de la refinación de petróleo","Naturaleza":"Haber"},
    {"Cuenta":"412040","Descripción":"Elaboración de sustancias químicas básicas","Naturaleza":"Haber"},
    {"Cuenta":"412041","Descripción":"Elaboración de abonos y compuestos de nitrógeno","Naturaleza":"Haber"},
    {"Cuenta":"412042","Descripción":"Elaboración de plástico y caucho sintético","Naturaleza":"Haber"},
    {"Cuenta":"412043","Descripción":"Elaboración de productos químicos de uso agropecuario","Naturaleza":"Haber"},
    {"Cuenta":"412044","Descripción":"Elaboración de pinturas, tintas y masillas","Naturaleza":"Haber"},
    {"Cuenta":"412045","Descripción":"Elaboración de productos farmacéuticos y botánicos","Naturaleza":"Haber"},
    {"Cuenta":"412046","Descripción":"Elaboración de jabones, detergentes y preparados de tocador","Naturaleza":"Haber"},
    {"Cuenta":"412047","Descripción":"Elaboración de otros productos químicos","Naturaleza":"Haber"},
    {"Cuenta":"412048","Descripción":"Elaboración de fibras","Naturaleza":"Haber"},
    {"Cuenta":"412049","Descripción":"Elaboración  de otros productos de caucho","Naturaleza":"Haber"},
    {"Cuenta":"412050","Descripción":"Elaboración  de productos de plástico","Naturaleza":"Haber"},
    {"Cuenta":"412051","Descripción":"Elaboración  de vidrio y productos de vidrio","Naturaleza":"Haber"},
    {"Cuenta":"412052","Descripción":"Elaboración  de productos de cerámica, loza, piedra, arcilla y porcelana","Naturaleza":"Haber"},
    {"Cuenta":"412053","Descripción":"Elaboración  de cemento, cal y yeso","Naturaleza":"Haber"},
    {"Cuenta":"412054","Descripción":"Elaboración  de artículos de hormigón, cemento y yeso","Naturaleza":"Haber"},
    {"Cuenta":"412055","Descripción":"Corte, tallado y acabado de la piedra","Naturaleza":"Haber"},
    {"Cuenta":"412056","Descripción":"Elaboración de otros productos minerales no metálicos","Naturaleza":"Haber"},
    {"Cuenta":"412057","Descripción":"Industrias básicas y fundición de hierro y acero","Naturaleza":"Haber"},
    {"Cuenta":"412058","Descripción":"Productos primarios de metales preciosos y de metales no ferrosos","Naturaleza":"Haber"},
    {"Cuenta":"412059","Descripción":"Fundición de metales no ferrosos","Naturaleza":"Haber"},
    {"Cuenta":"412060","Descripción":"Fabricación de productos metálicos para uso estructural","Naturaleza":"Haber"},
    {"Cuenta":"412061","Descripción":"Forja, prensado, estampado, laminado de metal y pulvimetalurgia","Naturaleza":"Haber"},
    {"Cuenta":"412062","Descripción":"Revestimiento de metales y obras de ingeniería mecánica","Naturaleza":"Haber"},
    {"Cuenta":"412063","Descripción":"Fabricación de artículos de ferretería","Naturaleza":"Haber"},
    {"Cuenta":"412064","Descripción":"Elaboración de otros productos de metal","Naturaleza":"Haber"},
    {"Cuenta":"412065","Descripción":"Fabricación de maquinaria y equipo","Naturaleza":"Haber"},
    {"Cuenta":"412066","Descripción":"Fabricación de equipos de elevación y manipulación","Naturaleza":"Haber"},
    {"Cuenta":"412067","Descripción":"Elaboración de aparatos de uso doméstico","Naturaleza":"Haber"},
    {"Cuenta":"412068","Descripción":"Elaboración de equipo de oficina","Naturaleza":"Haber"},
    {"Cuenta":"412069","Descripción":"Elaboración de pilas y baterías primarias","Naturaleza":"Haber"},
    {"Cuenta":"412070","Descripción":"Elaboración de equipo de iluminación","Naturaleza":"Haber"},
    {"Cuenta":"412071","Descripción":"Elaboración de otros tipos de equipo eléctrico","Naturaleza":"Haber"},
    {"Cuenta":"412072","Descripción":"Fabricación de equipos de radio, televisión y comunicaciones","Naturaleza":"Haber"},
    {"Cuenta":"412073","Descripción":"Fabricación de aparatos e instrumentos médicos","Naturaleza":"Haber"},
    {"Cuenta":"412074","Descripción":"Fabricación de instrumentos de medición y control","Naturaleza":"Haber"},
    {"Cuenta":"412075","Descripción":"Fabricación de instrumentos de óptica y equipo fotográfico","Naturaleza":"Haber"},
    {"Cuenta":"412076","Descripción":"Fabricación de relojes","Naturaleza":"Haber"},
    {"Cuenta":"412077","Descripción":"Fabricación de vehículos automotores","Naturaleza":"Haber"},
    {"Cuenta":"412078","Descripción":"Fabricación de carrocerías para automotores","Naturaleza":"Haber"},
    {"Cuenta":"412079","Descripción":"Fabricación de partes piezas y accesorios para automotores","Naturaleza":"Haber"},
    {"Cuenta":"412080","Descripción":"Fabricación y reparación de buques y otras embarcaciones","Naturaleza":"Haber"},
    {"Cuenta":"412081","Descripción":"Fabricación de locomotoras y material rodante para ferrocarriles","Naturaleza":"Haber"},
    {"Cuenta":"412082","Descripción":"Fabricación de aeronaves","Naturaleza":"Haber"},
    {"Cuenta":"412083","Descripción":"Fabricación de motocicletas","Naturaleza":"Haber"},
    {"Cuenta":"412084","Descripción":"Fabricación de bicicletas y sillas de ruedas","Naturaleza":"Haber"},
    {"Cuenta":"412085","Descripción":"Fabricación de otros tipos de transporte","Naturaleza":"Haber"},
    {"Cuenta":"412086","Descripción":"Fabricación de muebles","Naturaleza":"Haber"},
    {"Cuenta":"412087","Descripción":"Fabricación de joyas y artículos conexos","Naturaleza":"Haber"},
    {"Cuenta":"412088","Descripción":"Fabricación de instrumentos de música","Naturaleza":"Haber"},
    {"Cuenta":"412089","Descripción":"Fabricación de artículos y equipo para deporte","Naturaleza":"Haber"},
    {"Cuenta":"412090","Descripción":"Fabricación de juegos y juguetes","Naturaleza":"Haber"},
    {"Cuenta":"412091","Descripción":"Reciclamiento de desperdicios","Naturaleza":"Haber"},
    {"Cuenta":"412095","Descripción":"Productos de otras industrias manufactureras","Naturaleza":"Haber"},
    {"Cuenta":"412099","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4125","Descripción":"Suministro de electricidad, gas y agua","Naturaleza":"Haber"},
    {"Cuenta":"412505","Descripción":"Generación, captación y distribución de energía eléctrica","Naturaleza":"Haber"},
    {"Cuenta":"412510","Descripción":"Fabricación de gas y distribución de combustibles gaseosos","Naturaleza":"Haber"},
    {"Cuenta":"412515","Descripción":"Captación, depuración y distribución de agua","Naturaleza":"Haber"},
    {"Cuenta":"412595","Descripción":"Actividades conexas","Naturaleza":"Haber"},
    {"Cuenta":"412599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4130","Descripción":"Construcción","Naturaleza":"Haber"},
    {"Cuenta":"413005","Descripción":"Preparación de terrenos","Naturaleza":"Haber"},
    {"Cuenta":"413010","Descripción":"Construcción de edificios y obras de ingeniería civil","Naturaleza":"Haber"},
    {"Cuenta":"413015","Descripción":"Acondicionamiento de edificios","Naturaleza":"Haber"},
    {"Cuenta":"413020","Descripción":"Terminación de edificaciones","Naturaleza":"Haber"},
    {"Cuenta":"413025","Descripción":"Alquiler de equipo con operarios","Naturaleza":"Haber"},
    {"Cuenta":"413095","Descripción":"Actividades conexas","Naturaleza":"Haber"},
    {"Cuenta":"413099","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4135","Descripción":"Comercio al por mayor y al por menor","Naturaleza":"Haber"},
    {"Cuenta":"413502","Descripción":"Venta de vehículos automotores","Naturaleza":"Haber"},
    {"Cuenta":"413504","Descripción":"Mantenimiento, reparación y lavado de vehículos automotores","Naturaleza":"Haber"},
    {"Cuenta":"413506","Descripción":"Venta de partes, piezas y accesorios de vehículos automotores","Naturaleza":"Haber"},
    {"Cuenta":"413508","Descripción":"Venta de combustibles sólidos, líquidos, gaseosos","Naturaleza":"Haber"},
    {"Cuenta":"413510","Descripción":"Venta de lubricantes, aditivos, llantas y lujos para automotores","Naturaleza":"Haber"},
    {"Cuenta":"413512","Descripción":"Venta a cambio de retribución o por contrata","Naturaleza":"Haber"},
    {"Cuenta":"413514","Descripción":"Venta de insumos, materias primas agropecuarias y flores","Naturaleza":"Haber"},
    {"Cuenta":"413516","Descripción":"Venta de otros insumos y materias primas no agropecuarias","Naturaleza":"Haber"},
    {"Cuenta":"413518","Descripción":"Venta de animales vivos y cueros","Naturaleza":"Haber"},
    {"Cuenta":"413520","Descripción":"Venta de productos en almacenes no especializados","Naturaleza":"Haber"},
    {"Cuenta":"413522","Descripción":"Venta de productos agropecuarios","Naturaleza":"Haber"},
    {"Cuenta":"413524","Descripción":"Venta de productos textiles, de vestir, de cuero y calzado","Naturaleza":"Haber"},
    {"Cuenta":"413526","Descripción":"Venta de papel y cartón","Naturaleza":"Haber"},
    {"Cuenta":"413528","Descripción":"Venta de libros, revistas, elementos de papelería, útiles y textos escolares","Naturaleza":"Haber"},
    {"Cuenta":"413530","Descripción":"Venta de juegos, juguetes y artículos deportivos","Naturaleza":"Haber"},
    {"Cuenta":"413532","Descripción":"Venta de instrumentos quirúrgicos y ortopédicos","Naturaleza":"Haber"},
    {"Cuenta":"413534","Descripción":"Venta de artículos en relojerías y joyerías","Naturaleza":"Haber"},
    {"Cuenta":"413536","Descripción":"Venta de electrodomésticos y muebles","Naturaleza":"Haber"},
    {"Cuenta":"413538","Descripción":"Venta de productos de aseo, farmacéuticos, medicinales, y artículos de tocador","Naturaleza":"Haber"},
    {"Cuenta":"413540","Descripción":"Venta de cubiertos, vajillas, cristalería, porcelanas, cerámicas y otros artículos de uso doméstico","Naturaleza":"Haber"},
    {"Cuenta":"413542","Descripción":"Venta de materiales de construcción, fontanería y calefacción","Naturaleza":"Haber"},
    {"Cuenta":"413544","Descripción":"Venta de pinturas y lacas","Naturaleza":"Haber"},
    {"Cuenta":"413546","Descripción":"Venta de productos de vidrios y marquetería","Naturaleza":"Haber"},
    {"Cuenta":"413548","Descripción":"Venta de herramientas y artículos de ferretería","Naturaleza":"Haber"},
    {"Cuenta":"413550","Descripción":"Venta de químicos","Naturaleza":"Haber"},
    {"Cuenta":"413552","Descripción":"Venta de productos intermedios, desperdicios y desechos","Naturaleza":"Haber"},
    {"Cuenta":"413554","Descripción":"Venta de maquinaria, equipo de oficina y programas de computador","Naturaleza":"Haber"},
    {"Cuenta":"413556","Descripción":"Venta de artículos en cacharrerías y misceláneas","Naturaleza":"Haber"},
    {"Cuenta":"413558","Descripción":"Venta de instrumentos musicales","Naturaleza":"Haber"},
    {"Cuenta":"413560","Descripción":"Venta de artículos en casas de empeño y prenderías","Naturaleza":"Haber"},
    {"Cuenta":"413562","Descripción":"Venta de equipo fotográfico","Naturaleza":"Haber"},
    {"Cuenta":"413564","Descripción":"Venta de equipo óptico y de precisión","Naturaleza":"Haber"},
    {"Cuenta":"413566","Descripción":"Venta de empaques","Naturaleza":"Haber"},
    {"Cuenta":"413568","Descripción":"Venta de equipo profesional y científico","Naturaleza":"Haber"},
    {"Cuenta":"413570","Descripción":"Venta de loterías, rifas, chance, apuestas y similares","Naturaleza":"Haber"},
    {"Cuenta":"413572","Descripción":"Reparación de efectos personales y electrodomésticos","Naturaleza":"Haber"},
    {"Cuenta":"413595","Descripción":"Venta de otros productos","Naturaleza":"Haber"},
    {"Cuenta":"413599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4140","Descripción":"Hoteles y restaurantes","Naturaleza":"Haber"},
    {"Cuenta":"414005","Descripción":"Hotelería","Naturaleza":"Haber"},
    {"Cuenta":"414010","Descripción":"Campamento y otros tipos de hospedaje","Naturaleza":"Haber"},
    {"Cuenta":"414015","Descripción":"Restaurantes","Naturaleza":"Haber"},
    {"Cuenta":"414020","Descripción":"Bares y cantinas","Naturaleza":"Haber"},
    {"Cuenta":"414095","Descripción":"Actividades conexas","Naturaleza":"Haber"},
    {"Cuenta":"414099","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4145","Descripción":"Transporte, almacenamiento y comunicaciones","Naturaleza":"Haber"},
    {"Cuenta":"414505","Descripción":"Servicio de transporte por carretera","Naturaleza":"Haber"},
    {"Cuenta":"414510","Descripción":"Servicio de transporte por vía férrea","Naturaleza":"Haber"},
    {"Cuenta":"414515","Descripción":"Servicio de transporte por vía acuática","Naturaleza":"Haber"},
    {"Cuenta":"414520","Descripción":"Servicio de transporte por vía aérea","Naturaleza":"Haber"},
    {"Cuenta":"414525","Descripción":"Servicio de transporte por tuberías","Naturaleza":"Haber"},
    {"Cuenta":"414530","Descripción":"Manipulación de carga","Naturaleza":"Haber"},
    {"Cuenta":"414535","Descripción":"Almacenamiento y depósito","Naturaleza":"Haber"},
    {"Cuenta":"414540","Descripción":"Servicios complementarios para el transporte","Naturaleza":"Haber"},
    {"Cuenta":"414545","Descripción":"Agencias de viaje","Naturaleza":"Haber"},
    {"Cuenta":"414550","Descripción":"Otras agencias de transporte","Naturaleza":"Haber"},
    {"Cuenta":"414555","Descripción":"Servicio postal y de correo","Naturaleza":"Haber"},
    {"Cuenta":"414560","Descripción":"Servicio telefónico","Naturaleza":"Haber"},
    {"Cuenta":"414565","Descripción":"Servicio de telégrafo","Naturaleza":"Haber"},
    {"Cuenta":"414570","Descripción":"Servicio de transmisión de datos","Naturaleza":"Haber"},
    {"Cuenta":"414575","Descripción":"Servicio de radio y televisión por cable","Naturaleza":"Haber"},
    {"Cuenta":"414580","Descripción":"Transmisión de sonido e imágenes por contrato","Naturaleza":"Haber"},
    {"Cuenta":"414595","Descripción":"Actividades conexas","Naturaleza":"Haber"},
    {"Cuenta":"414599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4150","Descripción":"Actividad financiera","Naturaleza":"Haber"},
    {"Cuenta":"415005","Descripción":"Venta de inversiones","Naturaleza":"Haber"},
    {"Cuenta":"415010","Descripción":"Dividendos de sociedades anónimas y/o asimiladas","Naturaleza":"Haber"},
    {"Cuenta":"415015","Descripción":"Participaciones de sociedades limitadas y/o asimiladas","Naturaleza":"Haber"},
    {"Cuenta":"415020","Descripción":"Intereses","Naturaleza":"Haber"},
    {"Cuenta":"415025","Descripción":"Reajuste monetario-UPAC (hoy UVR)","Naturaleza":"Haber"},
    {"Cuenta":"415030","Descripción":"Comisiones","Naturaleza":"Haber"},
    {"Cuenta":"415035","Descripción":"Operaciones de descuento","Naturaleza":"Haber"},
    {"Cuenta":"415040","Descripción":"Cuotas de inscripción-consorcios","Naturaleza":"Haber"},
    {"Cuenta":"415045","Descripción":"Cuotas de administración-consorcios","Naturaleza":"Haber"},
    {"Cuenta":"415050","Descripción":"Reajuste del sistema-consorcios","Naturaleza":"Haber"},
    {"Cuenta":"415055","Descripción":"Eliminación de suscriptores-consorcios","Naturaleza":"Haber"},
    {"Cuenta":"415060","Descripción":"Cuotas de ingreso o retiro-sociedad administradora","Naturaleza":"Haber"},
    {"Cuenta":"415065","Descripción":"Servicios a comisionistas","Naturaleza":"Haber"},
    {"Cuenta":"415070","Descripción":"Inscripciones y cuotas","Naturaleza":"Haber"},
    {"Cuenta":"415075","Descripción":"Recuperación de garantías","Naturaleza":"Haber"},
    {"Cuenta":"415080","Descripción":"Ingresos método de participación","Naturaleza":"Haber"},
    {"Cuenta":"415095","Descripción":"Actividades conexas","Naturaleza":"Haber"},
    {"Cuenta":"415099","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4155","Descripción":"Actividades inmobiliarias, empresariales y de alquiler","Naturaleza":"Haber"},
    {"Cuenta":"415505","Descripción":"Arrendamientos de bienes inmuebles","Naturaleza":"Haber"},
    {"Cuenta":"415510","Descripción":"Inmobiliarias por retribución o contrata","Naturaleza":"Haber"},
    {"Cuenta":"415515","Descripción":"Alquiler equipo de transporte","Naturaleza":"Haber"},
    {"Cuenta":"415520","Descripción":"Alquiler maquinaria y equipo","Naturaleza":"Haber"},
    {"Cuenta":"415525","Descripción":"Alquiler de efectos personales y enseres domésticos","Naturaleza":"Haber"},
    {"Cuenta":"415530","Descripción":"Consultoría en equipo y programas de informática","Naturaleza":"Haber"},
    {"Cuenta":"415535","Descripción":"Procesamiento de datos","Naturaleza":"Haber"},
    {"Cuenta":"415540","Descripción":"Mantenimiento y reparación de maquinaria de oficina","Naturaleza":"Haber"},
    {"Cuenta":"415545","Descripción":"Investigaciones científicas y de desarrollo","Naturaleza":"Haber"},
    {"Cuenta":"415550","Descripción":"Actividades empresariales de consultoría","Naturaleza":"Haber"},
    {"Cuenta":"415555","Descripción":"Publicidad","Naturaleza":"Haber"},
    {"Cuenta":"415560","Descripción":"Dotación de personal","Naturaleza":"Haber"},
    {"Cuenta":"415565","Descripción":"Investigación y seguridad","Naturaleza":"Haber"},
    {"Cuenta":"415570","Descripción":"Limpieza de inmuebles","Naturaleza":"Haber"},
    {"Cuenta":"415575","Descripción":"Fotografía","Naturaleza":"Haber"},
    {"Cuenta":"415580","Descripción":"Envase y empaque","Naturaleza":"Haber"},
    {"Cuenta":"415585","Descripción":"Fotocopiado","Naturaleza":"Haber"},
    {"Cuenta":"415590","Descripción":"Mantenimiento y reparación de maquinaria y equipo","Naturaleza":"Haber"},
    {"Cuenta":"415595","Descripción":"Actividades conexas","Naturaleza":"Haber"},
    {"Cuenta":"415599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4160","Descripción":"Enseñanza","Naturaleza":"Haber"},
    {"Cuenta":"416005","Descripción":"Actividades relacionadas con la educación","Naturaleza":"Haber"},
    {"Cuenta":"416095","Descripción":"Actividades conexas","Naturaleza":"Haber"},
    {"Cuenta":"416099","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4165","Descripción":"Servicios sociales y de salud","Naturaleza":"Haber"},
    {"Cuenta":"416505","Descripción":"Servicio hospitalario","Naturaleza":"Haber"},
    {"Cuenta":"416510","Descripción":"Servicio médico","Naturaleza":"Haber"},
    {"Cuenta":"416515","Descripción":"Servicio odontológico","Naturaleza":"Haber"},
    {"Cuenta":"416520","Descripción":"Servicio de laboratorio","Naturaleza":"Haber"},
    {"Cuenta":"416525","Descripción":"Actividades veterinarias","Naturaleza":"Haber"},
    {"Cuenta":"416530","Descripción":"Actividades de servicios sociales","Naturaleza":"Haber"},
    {"Cuenta":"416595","Descripción":"Actividades conexas","Naturaleza":"Haber"},
    {"Cuenta":"416599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4170","Descripción":"Otras actividades de servicios comunitarios, sociales y personales","Naturaleza":"Haber"},
    {"Cuenta":"417005","Descripción":"Eliminación de desperdicios y aguas residuales","Naturaleza":"Haber"},
    {"Cuenta":"417010","Descripción":"Actividades de asociación","Naturaleza":"Haber"},
    {"Cuenta":"417015","Descripción":"Producción y distribución de filmes y videocintas","Naturaleza":"Haber"},
    {"Cuenta":"417020","Descripción":"Exhibición de filmes y videocintas","Naturaleza":"Haber"},
    {"Cuenta":"417025","Descripción":"Actividad de radio y televisión","Naturaleza":"Haber"},
    {"Cuenta":"417030","Descripción":"Actividad teatral, musical y artística","Naturaleza":"Haber"},
    {"Cuenta":"417035","Descripción":"Grabación y producción de discos","Naturaleza":"Haber"},
    {"Cuenta":"417040","Descripción":"Entretenimiento y esparcimiento","Naturaleza":"Haber"},
    {"Cuenta":"417045","Descripción":"Agencias de noticias","Naturaleza":"Haber"},
    {"Cuenta":"417050","Descripción":"Lavanderías y similares","Naturaleza":"Haber"},
    {"Cuenta":"417055","Descripción":"Peluquerías y similares","Naturaleza":"Haber"},
    {"Cuenta":"417060","Descripción":"Servicios funerarios","Naturaleza":"Haber"},
    {"Cuenta":"417065","Descripción":"Zonas francas","Naturaleza":"Haber"},
    {"Cuenta":"417095","Descripción":"Actividades conexas","Naturaleza":"Haber"},
    {"Cuenta":"417099","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4175","Descripción":"Devoluciones  en ventas (DB)","Naturaleza":"Haber"},
    {"Cuenta":"417599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"42","Descripción":"No operacionales","Naturaleza":"Haber"},
    {"Cuenta":"4205","Descripción":"Otras ventas","Naturaleza":"Haber"},
    {"Cuenta":"420505","Descripción":"Materia prima","Naturaleza":"Haber"},
    {"Cuenta":"420510","Descripción":"Material de desecho","Naturaleza":"Haber"},
    {"Cuenta":"420515","Descripción":"Materiales varios","Naturaleza":"Haber"},
    {"Cuenta":"420520","Descripción":"Productos de diversificación","Naturaleza":"Haber"},
    {"Cuenta":"420525","Descripción":"Excedentes de exportación","Naturaleza":"Haber"},
    {"Cuenta":"420530","Descripción":"Envases y empaques","Naturaleza":"Haber"},
    {"Cuenta":"420535","Descripción":"Productos agrícolas","Naturaleza":"Haber"},
    {"Cuenta":"420540","Descripción":"De propaganda","Naturaleza":"Haber"},
    {"Cuenta":"420545","Descripción":"Productos en remate","Naturaleza":"Haber"},
    {"Cuenta":"420550","Descripción":"Combustibles y lubricantes","Naturaleza":"Haber"},
    {"Cuenta":"420599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4210","Descripción":"Financieros","Naturaleza":"Haber"},
    {"Cuenta":"421005","Descripción":"Intereses","Naturaleza":"Haber"},
    {"Cuenta":"421010","Descripción":"Reajuste monetario-UPAC (hoy UVR)","Naturaleza":"Haber"},
    {"Cuenta":"421015","Descripción":"Descuentos amortizados","Naturaleza":"Haber"},
    {"Cuenta":"421020","Descripción":"Diferencia en cambio","Naturaleza":"Haber"},
    {"Cuenta":"421025","Descripción":"Financiación vehículos","Naturaleza":"Haber"},
    {"Cuenta":"421030","Descripción":"Financiación sistemas de viajes","Naturaleza":"Haber"},
    {"Cuenta":"421035","Descripción":"Aceptaciones bancarias","Naturaleza":"Haber"},
    {"Cuenta":"421040","Descripción":"Descuentos comerciales condicionados","Naturaleza":"Haber"},
    {"Cuenta":"421045","Descripción":"Descuentos bancarios","Naturaleza":"Haber"},
    {"Cuenta":"421050","Descripción":"Comisiones cheques de otras plazas","Naturaleza":"Haber"},
    {"Cuenta":"421055","Descripción":"Multas y recargos","Naturaleza":"Haber"},
    {"Cuenta":"421060","Descripción":"Sanciones cheques devueltos","Naturaleza":"Haber"},
    {"Cuenta":"421095","Descripción":"Otros","Naturaleza":"Haber"},
    {"Cuenta":"421099","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4215","Descripción":"Dividendos y participaciones","Naturaleza":"Haber"},
    {"Cuenta":"421505","Descripción":"De sociedades anónimas y/o asimiladas","Naturaleza":"Haber"},
    {"Cuenta":"421510","Descripción":"De sociedades limitadas y/o asimiladas","Naturaleza":"Haber"},
    {"Cuenta":"421599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4218","Descripción":"Ingresos método de participación","Naturaleza":"Haber"},
    {"Cuenta":"421805","Descripción":"De sociedades anónimas y/o asimiladas","Naturaleza":"Haber"},
    {"Cuenta":"421810","Descripción":"De sociedades limitadas y/o asimiladas","Naturaleza":"Haber"},
    {"Cuenta":"4220","Descripción":"Arrendamientos","Naturaleza":"Haber"},
    {"Cuenta":"422005","Descripción":"Terrenos","Naturaleza":"Haber"},
    {"Cuenta":"422010","Descripción":"Construcciones y edificios","Naturaleza":"Haber"},
    {"Cuenta":"422015","Descripción":"Maquinaria y equipo","Naturaleza":"Haber"},
    {"Cuenta":"422020","Descripción":"Equipo de oficina","Naturaleza":"Haber"},
    {"Cuenta":"422025","Descripción":"Equipo de computación y comunicación","Naturaleza":"Haber"},
    {"Cuenta":"422030","Descripción":"Equipo médico-científico","Naturaleza":"Haber"},
    {"Cuenta":"422035","Descripción":"Equipo de hoteles y restaurantes","Naturaleza":"Haber"},
    {"Cuenta":"422040","Descripción":"Flota y equipo de transporte","Naturaleza":"Haber"},
    {"Cuenta":"422045","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Haber"},
    {"Cuenta":"422050","Descripción":"Flota y equipo aéreo","Naturaleza":"Haber"},
    {"Cuenta":"422055","Descripción":"Flota y equipo férreo","Naturaleza":"Haber"},
    {"Cuenta":"422060","Descripción":"Acueductos, plantas y redes","Naturaleza":"Haber"},
    {"Cuenta":"422062","Descripción":"Envases y empaques","Naturaleza":"Haber"},
    {"Cuenta":"422065","Descripción":"Plantaciones agrícolas y forestales","Naturaleza":"Haber"},
    {"Cuenta":"422070","Descripción":"Aeródromos","Naturaleza":"Haber"},
    {"Cuenta":"422075","Descripción":"Semovientes","Naturaleza":"Haber"},
    {"Cuenta":"422099","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4225","Descripción":"Comisiones","Naturaleza":"Haber"},
    {"Cuenta":"422505","Descripción":"Sobre inversiones","Naturaleza":"Haber"},
    {"Cuenta":"422510","Descripción":"De concesionarios","Naturaleza":"Haber"},
    {"Cuenta":"422515","Descripción":"De actividades financieras","Naturaleza":"Haber"},
    {"Cuenta":"422520","Descripción":"Por venta de servicios de taller","Naturaleza":"Haber"},
    {"Cuenta":"422525","Descripción":"Por venta de seguros","Naturaleza":"Haber"},
    {"Cuenta":"422530","Descripción":"Por ingresos para terceros","Naturaleza":"Haber"},
    {"Cuenta":"422535","Descripción":"Por distribución de películas","Naturaleza":"Haber"},
    {"Cuenta":"422540","Descripción":"Derechos de autor","Naturaleza":"Haber"},
    {"Cuenta":"422545","Descripción":"Derechos de programación","Naturaleza":"Haber"},
    {"Cuenta":"422599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4230","Descripción":"Honorarios","Naturaleza":"Haber"},
    {"Cuenta":"423005","Descripción":"Asesorías","Naturaleza":"Haber"},
    {"Cuenta":"423010","Descripción":"Asistencia técnica","Naturaleza":"Haber"},
    {"Cuenta":"423015","Descripción":"Administración de vinculadas","Naturaleza":"Haber"},
    {"Cuenta":"423099","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4235","Descripción":"Servicios","Naturaleza":"Haber"},
    {"Cuenta":"423505","Descripción":"De báscula","Naturaleza":"Haber"},
    {"Cuenta":"423510","Descripción":"De transporte","Naturaleza":"Haber"},
    {"Cuenta":"423515","Descripción":"De prensa","Naturaleza":"Haber"},
    {"Cuenta":"423520","Descripción":"Administrativos","Naturaleza":"Haber"},
    {"Cuenta":"423525","Descripción":"Técnicos","Naturaleza":"Haber"},
    {"Cuenta":"423530","Descripción":"De computación","Naturaleza":"Haber"},
    {"Cuenta":"423535","Descripción":"De telefax","Naturaleza":"Haber"},
    {"Cuenta":"423540","Descripción":"Taller de vehículos","Naturaleza":"Haber"},
    {"Cuenta":"423545","Descripción":"De recepción de aeronaves","Naturaleza":"Haber"},
    {"Cuenta":"423550","Descripción":"De transporte programa gas natural","Naturaleza":"Haber"},
    {"Cuenta":"423555","Descripción":"Por contratos","Naturaleza":"Haber"},
    {"Cuenta":"423560","Descripción":"De trilla","Naturaleza":"Haber"},
    {"Cuenta":"423565","Descripción":"De mantenimiento","Naturaleza":"Haber"},
    {"Cuenta":"423570","Descripción":"Al personal","Naturaleza":"Haber"},
    {"Cuenta":"423575","Descripción":"De casino","Naturaleza":"Haber"},
    {"Cuenta":"423580","Descripción":"Fletes","Naturaleza":"Haber"},
    {"Cuenta":"423585","Descripción":"Entre compañías","Naturaleza":"Haber"},
    {"Cuenta":"423595","Descripción":"Otros","Naturaleza":"Haber"},
    {"Cuenta":"423599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4240","Descripción":"Utilidad en venta de inversiones","Naturaleza":"Haber"},
    {"Cuenta":"424005","Descripción":"Acciones","Naturaleza":"Haber"},
    {"Cuenta":"424010","Descripción":"Cuotas o partes de interés social","Naturaleza":"Haber"},
    {"Cuenta":"424015","Descripción":"Bonos","Naturaleza":"Haber"},
    {"Cuenta":"424020","Descripción":"Cédulas","Naturaleza":"Haber"},
    {"Cuenta":"424025","Descripción":"Certificados","Naturaleza":"Haber"},
    {"Cuenta":"424030","Descripción":"Papeles comerciales","Naturaleza":"Haber"},
    {"Cuenta":"424035","Descripción":"Títulos","Naturaleza":"Haber"},
    {"Cuenta":"424045","Descripción":"Derechos fiduciarios","Naturaleza":"Haber"},
    {"Cuenta":"424050","Descripción":"Obligatorias","Naturaleza":"Haber"},
    {"Cuenta":"424095","Descripción":"Otras","Naturaleza":"Haber"},
    {"Cuenta":"424099","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4245","Descripción":"Utilidad en venta de propiedades, planta y equipo","Naturaleza":"Haber"},
    {"Cuenta":"424504","Descripción":"Terrenos","Naturaleza":"Haber"},
    {"Cuenta":"424506","Descripción":"Materiales industria petrolera","Naturaleza":"Haber"},
    {"Cuenta":"424508","Descripción":"Construcciones en curso","Naturaleza":"Haber"},
    {"Cuenta":"424512","Descripción":"Maquinaria en montaje","Naturaleza":"Haber"},
    {"Cuenta":"424516","Descripción":"Construcciones y edificaciones","Naturaleza":"Haber"},
    {"Cuenta":"424520","Descripción":"Maquinaria y equipo","Naturaleza":"Haber"},
    {"Cuenta":"424524","Descripción":"Equipo de oficina","Naturaleza":"Haber"},
    {"Cuenta":"424528","Descripción":"Equipo de computación y comunicación","Naturaleza":"Haber"},
    {"Cuenta":"424532","Descripción":"Equipo médico-científico","Naturaleza":"Haber"},
    {"Cuenta":"424536","Descripción":"Equipo de hoteles y restaurantes","Naturaleza":"Haber"},
    {"Cuenta":"424540","Descripción":"Flota y equipo de transporte","Naturaleza":"Haber"},
    {"Cuenta":"424544","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Haber"},
    {"Cuenta":"424548","Descripción":"Flota y equipo aéreo","Naturaleza":"Haber"},
    {"Cuenta":"424552","Descripción":"Flota y equipo férreo","Naturaleza":"Haber"},
    {"Cuenta":"424556","Descripción":"Acueductos, plantas y redes","Naturaleza":"Haber"},
    {"Cuenta":"424560","Descripción":"Armamento de vigilancia","Naturaleza":"Haber"},
    {"Cuenta":"424562","Descripción":"Envases y empaques","Naturaleza":"Haber"},
    {"Cuenta":"424564","Descripción":"Plantaciones agrícolas y forestales","Naturaleza":"Haber"},
    {"Cuenta":"424568","Descripción":"Vías de comunicación","Naturaleza":"Haber"},
    {"Cuenta":"424572","Descripción":"Minas y Canteras","Naturaleza":"Haber"},
    {"Cuenta":"424580","Descripción":"Pozos artesianos","Naturaleza":"Haber"},
    {"Cuenta":"424584","Descripción":"Yacimientos","Naturaleza":"Haber"},
    {"Cuenta":"424588","Descripción":"Semovientes","Naturaleza":"Haber"},
    {"Cuenta":"424599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4248","Descripción":"Utilidad en venta de otros bienes","Naturaleza":"Haber"},
    {"Cuenta":"424805","Descripción":"Intangibles","Naturaleza":"Haber"},
    {"Cuenta":"424810","Descripción":"Otros activos","Naturaleza":"Haber"},
    {"Cuenta":"424899","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4250","Descripción":"Recuperaciones","Naturaleza":"Haber"},
    {"Cuenta":"425005","Descripción":"Deudas malas","Naturaleza":"Haber"},
    {"Cuenta":"425010","Descripción":"Seguros","Naturaleza":"Haber"},
    {"Cuenta":"425015","Descripción":"Reclamos","Naturaleza":"Haber"},
    {"Cuenta":"425020","Descripción":"Reintegro por personal en comisión","Naturaleza":"Haber"},
    {"Cuenta":"425025","Descripción":"Reintegro garantías","Naturaleza":"Haber"},
    {"Cuenta":"425030","Descripción":"Descuentos concedidos","Naturaleza":"Haber"},
    {"Cuenta":"425035","Descripción":"De  provisiones","Naturaleza":"Haber"},
    {"Cuenta":"425040","Descripción":"Gastos bancarios","Naturaleza":"Haber"},
    {"Cuenta":"425045","Descripción":"De depreciación","Naturaleza":"Haber"},
    {"Cuenta":"425050","Descripción":"Reintegro de otros costos y gastos","Naturaleza":"Haber"},
    {"Cuenta":"425099","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4255","Descripción":"Indemnizaciones","Naturaleza":"Haber"},
    {"Cuenta":"425505","Descripción":"Por siniestro","Naturaleza":"Haber"},
    {"Cuenta":"425510","Descripción":"Por suministros","Naturaleza":"Haber"},
    {"Cuenta":"425515","Descripción":"Lucro cesante compañías de seguros","Naturaleza":"Haber"},
    {"Cuenta":"425520","Descripción":"Daño emergente compañías de seguros","Naturaleza":"Haber"},
    {"Cuenta":"425525","Descripción":"Por pérdida de mercancía","Naturaleza":"Haber"},
    {"Cuenta":"425530","Descripción":"Por incumplimiento de contratos","Naturaleza":"Haber"},
    {"Cuenta":"425535","Descripción":"De terceros","Naturaleza":"Haber"},
    {"Cuenta":"425540","Descripción":"Por incapacidades ISS","Naturaleza":"Haber"},
    {"Cuenta":"425595","Descripción":"Otras","Naturaleza":"Haber"},
    {"Cuenta":"425599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4260","Descripción":"Participaciones en concesiones","Naturaleza":"Haber"},
    {"Cuenta":"426099","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4265","Descripción":"Ingresos de ejercicios anteriores","Naturaleza":"Haber"},
    {"Cuenta":"426599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4275","Descripción":"Devoluciones en otras ventas (DB)","Naturaleza":"Haber"},
    {"Cuenta":"427599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4295","Descripción":"Diversos","Naturaleza":"Haber"},
    {"Cuenta":"429503","Descripción":"CERT","Naturaleza":"Haber"},
    {"Cuenta":"429505","Descripción":"Aprovechamientos","Naturaleza":"Haber"},
    {"Cuenta":"429507","Descripción":"Auxilios","Naturaleza":"Haber"},
    {"Cuenta":"429509","Descripción":"Subvenciones","Naturaleza":"Haber"},
    {"Cuenta":"429511","Descripción":"Ingresos por investigación y desarrollo","Naturaleza":"Haber"},
    {"Cuenta":"429513","Descripción":"Por trabajos ejecutados","Naturaleza":"Haber"},
    {"Cuenta":"429515","Descripción":"Regalías","Naturaleza":"Haber"},
    {"Cuenta":"429517","Descripción":"Derivados de las exportaciones","Naturaleza":"Haber"},
    {"Cuenta":"429519","Descripción":"Otros ingresos de explotación","Naturaleza":"Haber"},
    {"Cuenta":"429521","Descripción":"De la actividad ganadera","Naturaleza":"Haber"},
    {"Cuenta":"429525","Descripción":"Derechos y licitaciones","Naturaleza":"Haber"},
    {"Cuenta":"429530","Descripción":"Ingresos por elementos perdidos","Naturaleza":"Haber"},
    {"Cuenta":"429533","Descripción":"Multas y recargos","Naturaleza":"Haber"},
    {"Cuenta":"429535","Descripción":"Preavisos descontados","Naturaleza":"Haber"},
    {"Cuenta":"429537","Descripción":"Reclamos","Naturaleza":"Haber"},
    {"Cuenta":"429540","Descripción":"Recobro de daños","Naturaleza":"Haber"},
    {"Cuenta":"429543","Descripción":"Premios","Naturaleza":"Haber"},
    {"Cuenta":"429545","Descripción":"Bonificaciones","Naturaleza":"Haber"},
    {"Cuenta":"429547","Descripción":"Productos descontados","Naturaleza":"Haber"},
    {"Cuenta":"429549","Descripción":"Reconocimientos ISS","Naturaleza":"Haber"},
    {"Cuenta":"429551","Descripción":"Excedentes","Naturaleza":"Haber"},
    {"Cuenta":"429553","Descripción":"Sobrantes de caja","Naturaleza":"Haber"},
    {"Cuenta":"429555","Descripción":"Sobrantes en liquidación fletes","Naturaleza":"Haber"},
    {"Cuenta":"429557","Descripción":"Subsidios estatales","Naturaleza":"Haber"},
    {"Cuenta":"429559","Descripción":"Capacitación distribuidores","Naturaleza":"Haber"},
    {"Cuenta":"429561","Descripción":"De escrituración","Naturaleza":"Haber"},
    {"Cuenta":"429563","Descripción":"Registro promesas de venta","Naturaleza":"Haber"},
    {"Cuenta":"429567","Descripción":"Útiles, papelería y fotocopias","Naturaleza":"Haber"},
    {"Cuenta":"429571","Descripción":"Resultados, matrículas y traspasos","Naturaleza":"Haber"},
    {"Cuenta":"429573","Descripción":"Decoraciones","Naturaleza":"Haber"},
    {"Cuenta":"429575","Descripción":"Manejo de carga","Naturaleza":"Haber"},
    {"Cuenta":"429579","Descripción":"Historia clínica","Naturaleza":"Haber"},
    {"Cuenta":"429581","Descripción":"Ajuste al peso","Naturaleza":"Haber"},
    {"Cuenta":"429583","Descripción":"Llamadas telefónicas","Naturaleza":"Haber"},
    {"Cuenta":"429595","Descripción":"Otros","Naturaleza":"Haber"},
    {"Cuenta":"429599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"47","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"4705","Descripción":"Corrección monetaria","Naturaleza":"Haber"},
    {"Cuenta":"470505","Descripción":"Inversiones (CR)","Naturaleza":"Haber"},
    {"Cuenta":"470510","Descripción":"Inventarios (CR)","Naturaleza":"Haber"},
    {"Cuenta":"470515","Descripción":"Propiedades, planta y equipo (CR)","Naturaleza":"Haber"},
    {"Cuenta":"470520","Descripción":"Intangibles (CR)","Naturaleza":"Haber"},
    {"Cuenta":"470525","Descripción":"Activos diferidos","Naturaleza":"Haber"},
    {"Cuenta":"470530","Descripción":"Otros activos (CR)","Naturaleza":"Haber"},
    {"Cuenta":"470535","Descripción":"Pasivos sujetos de ajuste","Naturaleza":"Haber"},
    {"Cuenta":"470540","Descripción":"Patrimonio","Naturaleza":"Haber"},
    {"Cuenta":"470545","Descripción":"Depreciación acumulada (DB)","Naturaleza":"Haber"},
    {"Cuenta":"470550","Descripción":"Depreciación diferida (CR)","Naturaleza":"Haber"},
    {"Cuenta":"470555","Descripción":"Agotamiento acumulado (DB)","Naturaleza":"Haber"},
    {"Cuenta":"470560","Descripción":"Amortización acumulada (DB)","Naturaleza":"Haber"},
    {"Cuenta":"470565","Descripción":"Ingresos operacionales  (DB)","Naturaleza":"Haber"},
    {"Cuenta":"470568","Descripción":"Devoluciones en ventas (CR)","Naturaleza":"Haber"},
    {"Cuenta":"470570","Descripción":"Ingresos no operacionales (DB)","Naturaleza":"Haber"},
    {"Cuenta":"470575","Descripción":"Gastos operacionales de administración (CR)","Naturaleza":"Haber"},
    {"Cuenta":"470580","Descripción":"Gastos operacionales de ventas (CR)","Naturaleza":"Haber"},
    {"Cuenta":"470585","Descripción":"Gastos no operacionales (CR)","Naturaleza":"Haber"},
    {"Cuenta":"470590","Descripción":"Compras (CR)","Naturaleza":"Haber"},
    {"Cuenta":"470591","Descripción":"Devoluciones en compras (DB)","Naturaleza":"Haber"},
    {"Cuenta":"470592","Descripción":"Costo de ventas (CR)","Naturaleza":"Haber"},
    {"Cuenta":"470594","Descripción":"Costos de producción o de operación (CR)","Naturaleza":"Haber"},
]