export const Pasivos = [
    {"Cuenta":"2","Descripción":"Pasivo","Naturaleza":"Haber"},
    {"Cuenta":"21","Descripción":"Obligaciones financieras","Naturaleza":"Haber"},
    {"Cuenta":"2105","Descripción":"Bancos nacionales","Naturaleza":"Haber"},
    {"Cuenta":"210505","Descripción":"Sobregiros","Naturaleza":"Haber"},
    {"Cuenta":"210510","Descripción":"Pagarés","Naturaleza":"Haber"},
    {"Cuenta":"210515","Descripción":"Cartas de crédito","Naturaleza":"Haber"},
    {"Cuenta":"210520","Descripción":"Aceptaciones bancarias","Naturaleza":"Haber"},
    {"Cuenta":"2110","Descripción":"Bancos del exterior","Naturaleza":"Haber"},
    {"Cuenta":"211005","Descripción":"Sobregiros","Naturaleza":"Haber"},
    {"Cuenta":"211010","Descripción":"Pagarés","Naturaleza":"Haber"},
    {"Cuenta":"211015","Descripción":"Cartas de crédito","Naturaleza":"Haber"},
    {"Cuenta":"211020","Descripción":"Aceptaciones bancarias","Naturaleza":"Haber"},
    {"Cuenta":"2115","Descripción":"Corporaciones financieras","Naturaleza":"Haber"},
    {"Cuenta":"211505","Descripción":"Pagarés","Naturaleza":"Haber"},
    {"Cuenta":"211510","Descripción":"Aceptaciones financieras","Naturaleza":"Haber"},
    {"Cuenta":"211515","Descripción":"Cartas de crédito","Naturaleza":"Haber"},
    {"Cuenta":"211520","Descripción":"Contratos de arrendamiento financiero (leasing)","Naturaleza":"Haber"},
    {"Cuenta":"2120","Descripción":"Compañías de financiamiento comercial","Naturaleza":"Haber"},
    {"Cuenta":"212005","Descripción":"Pagarés","Naturaleza":"Haber"},
    {"Cuenta":"212010","Descripción":"Aceptaciones financieras","Naturaleza":"Haber"},
    {"Cuenta":"212020","Descripción":"Contratos de arrendamiento financiero (leasing)","Naturaleza":"Haber"},
    {"Cuenta":"2125","Descripción":"Corporaciones de ahorro y vivienda","Naturaleza":"Haber"},
    {"Cuenta":"212505","Descripción":"Sobregiros","Naturaleza":"Haber"},
    {"Cuenta":"212510","Descripción":"Pagarés","Naturaleza":"Haber"},
    {"Cuenta":"212515","Descripción":"Hipotecarias","Naturaleza":"Haber"},
    {"Cuenta":"2130","Descripción":"Entidades financieras del exterior","Naturaleza":"Haber"},
    {"Cuenta":"2135","Descripción":"Compromisos de recompra de inversiones negociadas","Naturaleza":"Haber"},
    {"Cuenta":"213505","Descripción":"Acciones","Naturaleza":"Haber"},
    {"Cuenta":"213510","Descripción":"Cuotas o partes de interés social","Naturaleza":"Haber"},
    {"Cuenta":"213515","Descripción":"Bonos","Naturaleza":"Haber"},
    {"Cuenta":"213520","Descripción":"Cédulas","Naturaleza":"Haber"},
    {"Cuenta":"213525","Descripción":"Certificados","Naturaleza":"Haber"},
    {"Cuenta":"213530","Descripción":"Papeles comerciales","Naturaleza":"Haber"},
    {"Cuenta":"213535","Descripción":"Títulos","Naturaleza":"Haber"},
    {"Cuenta":"213540","Descripción":"Aceptaciones bancarias o financieras","Naturaleza":"Haber"},
    {"Cuenta":"213595","Descripción":"Otros","Naturaleza":"Haber"},
    {"Cuenta":"2140","Descripción":"Compromisos de recompra de cartera negociada","Naturaleza":"Haber"},
    {"Cuenta":"2145","Descripción":"Obligaciones gubernamentales","Naturaleza":"Haber"},
    {"Cuenta":"214505","Descripción":"Gobierno Nacional","Naturaleza":"Haber"},
    {"Cuenta":"214510","Descripción":"Entidades oficiales","Naturaleza":"Haber"},
    {"Cuenta":"2195","Descripción":"Otras obligaciones","Naturaleza":"Haber"},
    {"Cuenta":"219505","Descripción":"Particulares","Naturaleza":"Haber"},
    {"Cuenta":"219510","Descripción":"Compañías vinculadas","Naturaleza":"Haber"},
    {"Cuenta":"219515","Descripción":"Casa matriz","Naturaleza":"Haber"},
    {"Cuenta":"219520","Descripción":"Socios o accionistas","Naturaleza":"Haber"},
    {"Cuenta":"219525","Descripción":"Fondos y cooperativas","Naturaleza":"Haber"},
    {"Cuenta":"219530","Descripción":"Directores","Naturaleza":"Haber"},
    {"Cuenta":"219595","Descripción":"Otras","Naturaleza":"Haber"},
    {"Cuenta":"22","Descripción":"Proveedores","Naturaleza":"Haber"},
    {"Cuenta":"2205","Descripción":"Nacionales","Naturaleza":"Haber"},
    {"Cuenta":"2210","Descripción":"Del exterior","Naturaleza":"Haber"},
    {"Cuenta":"2215","Descripción":"Cuentas corrientes comerciales","Naturaleza":"Haber"},
    {"Cuenta":"2220","Descripción":"Casa matriz","Naturaleza":"Haber"},
    {"Cuenta":"2225","Descripción":"Compañías vinculadas","Naturaleza":"Haber"},
    {"Cuenta":"23","Descripción":"Cuentas por pagar","Naturaleza":"Haber"},
    {"Cuenta":"2305","Descripción":"Cuentas corrientes comerciales","Naturaleza":"Haber"},
    {"Cuenta":"2310","Descripción":"A casa matriz","Naturaleza":"Haber"},
    {"Cuenta":"2315","Descripción":"A compañías vinculadas","Naturaleza":"Haber"},
    {"Cuenta":"2320","Descripción":"A contratistas","Naturaleza":"Haber"},
    {"Cuenta":"2330","Descripción":"Órdenes de compra por utilizar","Naturaleza":"Haber"},
    {"Cuenta":"2335","Descripción":"Costos y gastos por pagar","Naturaleza":"Haber"},
    {"Cuenta":"233505","Descripción":"Gastos financieros","Naturaleza":"Haber"},
    {"Cuenta":"233510","Descripción":"Gastos legales","Naturaleza":"Haber"},
    {"Cuenta":"233515","Descripción":"Libros, suscripciones, periódicos y revistas","Naturaleza":"Haber"},
    {"Cuenta":"233520","Descripción":"Comisiones","Naturaleza":"Haber"},
    {"Cuenta":"233525","Descripción":"Honorarios","Naturaleza":"Haber"},
    {"Cuenta":"233530","Descripción":"Servicios técnicos","Naturaleza":"Haber"},
    {"Cuenta":"233535","Descripción":"Servicios de mantenimiento","Naturaleza":"Haber"},
    {"Cuenta":"233540","Descripción":"Arrendamientos","Naturaleza":"Haber"},
    {"Cuenta":"233545","Descripción":"Transportes, fletes y acarreos","Naturaleza":"Haber"},
    {"Cuenta":"233550","Descripción":"Servicios públicos","Naturaleza":"Haber"},
    {"Cuenta":"233555","Descripción":"Seguros","Naturaleza":"Haber"},
    {"Cuenta":"233560","Descripción":"Gastos de viaje","Naturaleza":"Haber"},
    {"Cuenta":"233565","Descripción":"Gastos de representación y relaciones públicas","Naturaleza":"Haber"},
    {"Cuenta":"233570","Descripción":"Servicios aduaneros","Naturaleza":"Haber"},
    {"Cuenta":"233595","Descripción":"Otros","Naturaleza":"Haber"},
    {"Cuenta":"2340","Descripción":"Instalamentos por pagar","Naturaleza":"Haber"},
    {"Cuenta":"2345","Descripción":"Acreedores oficiales","Naturaleza":"Haber"},
    {"Cuenta":"2350","Descripción":"Regalías por pagar","Naturaleza":"Haber"},
    {"Cuenta":"2355","Descripción":"Deudas con accionistas o socios","Naturaleza":"Haber"},
    {"Cuenta":"235505","Descripción":"Accionistas","Naturaleza":"Haber"},
    {"Cuenta":"235510","Descripción":"Socios","Naturaleza":"Haber"},
    {"Cuenta":"2357","Descripción":"Deudas con directores","Naturaleza":"Haber"},
    {"Cuenta":"2360","Descripción":"Dividendos o participaciones por pagar","Naturaleza":"Haber"},
    {"Cuenta":"236005","Descripción":"Dividendos","Naturaleza":"Haber"},
    {"Cuenta":"236010","Descripción":"Participaciones","Naturaleza":"Haber"},
    {"Cuenta":"2365","Descripción":"Retención en la fuente","Naturaleza":"Haber"},
    {"Cuenta":"236505","Descripción":"Salarios y pagos laborales","Naturaleza":"Haber"},
    {"Cuenta":"236510","Descripción":"Dividendos y/o participaciones","Naturaleza":"Haber"},
    {"Cuenta":"236515","Descripción":"Honorarios","Naturaleza":"Haber"},
    {"Cuenta":"236520","Descripción":"Comisiones","Naturaleza":"Haber"},
    {"Cuenta":"236525","Descripción":"Servicios","Naturaleza":"Haber"},
    {"Cuenta":"236530","Descripción":"Arrendamientos","Naturaleza":"Haber"},
    {"Cuenta":"236535","Descripción":"Rendimientos financieros","Naturaleza":"Haber"},
    {"Cuenta":"236540","Descripción":"Compras","Naturaleza":"Haber"},
    {"Cuenta":"236545","Descripción":"Loterías, rifas, apuestas y similares","Naturaleza":"Haber"},
    {"Cuenta":"236550","Descripción":"Por pagos al exterior","Naturaleza":"Haber"},
    {"Cuenta":"236555","Descripción":"Por ingresos obtenidos en el exterior","Naturaleza":"Haber"},
    {"Cuenta":"236560","Descripción":"Enajenación propiedades planta y equipo, personas naturales","Naturaleza":"Haber"},
    {"Cuenta":"236565","Descripción":"Por impuesto de timbre","Naturaleza":"Haber"},
    {"Cuenta":"236570","Descripción":"Otras retenciones y patrimonio","Naturaleza":"Haber"},
    {"Cuenta":"236575","Descripción":"Autorretenciones","Naturaleza":"Haber"},
    {"Cuenta":"2367","Descripción":"Impuesto a las ventas retenido","Naturaleza":"Haber"},
    {"Cuenta":"2368","Descripción":"Impuesto de industria y comercio retenido","Naturaleza":"Haber"},
    {"Cuenta":"2370","Descripción":"Retenciones y aportes de nómina","Naturaleza":"Haber"},
    {"Cuenta":"237005","Descripción":"Aportes a entidades promotoras de salud, EPS","Naturaleza":"Haber"},
    {"Cuenta":"237006","Descripción":"Aportes a administradoras de riesgos profesionales, ARP","Naturaleza":"Haber"},
    {"Cuenta":"237010","Descripción":"Aportes al ICBF, SENA y cajas de compensación","Naturaleza":"Haber"},
    {"Cuenta":"237015","Descripción":"Aportes al FIC","Naturaleza":"Haber"},
    {"Cuenta":"237025","Descripción":"Embargos judiciales","Naturaleza":"Haber"},
    {"Cuenta":"237030","Descripción":"Libranzas","Naturaleza":"Haber"},
    {"Cuenta":"237035","Descripción":"Sindicatos","Naturaleza":"Haber"},
    {"Cuenta":"237040","Descripción":"Cooperativas","Naturaleza":"Haber"},
    {"Cuenta":"237045","Descripción":"Fondos","Naturaleza":"Haber"},
    {"Cuenta":"237095","Descripción":"Otros","Naturaleza":"Haber"},
    {"Cuenta":"2375","Descripción":"Cuotas por devolver","Naturaleza":"Haber"},
    {"Cuenta":"2380","Descripción":"Acreedores varios","Naturaleza":"Haber"},
    {"Cuenta":"238005","Descripción":"Depositarios","Naturaleza":"Haber"},
    {"Cuenta":"238010","Descripción":"Comisionistas de bolsas","Naturaleza":"Haber"},
    {"Cuenta":"238015","Descripción":"Sociedad administradora-Fondos de inversión","Naturaleza":"Haber"},
    {"Cuenta":"238020","Descripción":"Reintegros por pagar","Naturaleza":"Haber"},
    {"Cuenta":"238025","Descripción":"Fondo de perseverancia","Naturaleza":"Haber"},
    {"Cuenta":"238030","Descripción":"Fondos de cesantías y/o pensiones","Naturaleza":"Haber"},
    {"Cuenta":"238035","Descripción":"Donaciones asignadas por pagar","Naturaleza":"Haber"},
    {"Cuenta":"238095","Descripción":"Otros","Naturaleza":"Haber"},
    {"Cuenta":"24","Descripción":"Impuestos, gravámenes y tasas","Naturaleza":"Haber"},
    {"Cuenta":"2404","Descripción":"De renta y complementarios","Naturaleza":"Haber"},
    {"Cuenta":"240405","Descripción":"Vigencia fiscal corriente","Naturaleza":"Haber"},
    {"Cuenta":"240410","Descripción":"Vigencias fiscales anteriores","Naturaleza":"Haber"},
    {"Cuenta":"2408","Descripción":"Impuesto sobre las ventas por pagar","Naturaleza":"Haber"},
    {"Cuenta":"2412","Descripción":"De industria y comercio","Naturaleza":"Haber"},
    {"Cuenta":"241205","Descripción":"Vigencia fiscal corriente","Naturaleza":"Haber"},
    {"Cuenta":"241210","Descripción":"Vigencias fiscales anteriores","Naturaleza":"Haber"},
    {"Cuenta":"2416","Descripción":"A la propiedad raíz","Naturaleza":"Haber"},
    {"Cuenta":"2420","Descripción":"Derechos sobre instrumentos públicos","Naturaleza":"Haber"},
    {"Cuenta":"2424","Descripción":"De valorización","Naturaleza":"Haber"},
    {"Cuenta":"242405","Descripción":"Vigencia fiscal corriente","Naturaleza":"Haber"},
    {"Cuenta":"242410","Descripción":"Vigencias fiscales anteriores","Naturaleza":"Haber"},
    {"Cuenta":"2428","Descripción":"De turismo","Naturaleza":"Haber"},
    {"Cuenta":"2432","Descripción":"Tasa por utilización de puertos","Naturaleza":"Haber"},
    {"Cuenta":"2436","Descripción":"De vehículos","Naturaleza":"Haber"},
    {"Cuenta":"243605","Descripción":"Vigencia fiscal corriente","Naturaleza":"Haber"},
    {"Cuenta":"243610","Descripción":"Vigencias fiscales anteriores","Naturaleza":"Haber"},
    {"Cuenta":"2440","Descripción":"De espectáculos públicos","Naturaleza":"Haber"},
    {"Cuenta":"2444","Descripción":"De hidrocarburos y minas","Naturaleza":"Haber"},
    {"Cuenta":"244405","Descripción":"De hidrocarburos","Naturaleza":"Haber"},
    {"Cuenta":"244410","Descripción":"De minas","Naturaleza":"Haber"},
    {"Cuenta":"2448","Descripción":"Regalías e impuestos a la pequeña y mediana minería","Naturaleza":"Haber"},
    {"Cuenta":"2452","Descripción":"A las exportaciones cafeteras","Naturaleza":"Haber"},
    {"Cuenta":"2456","Descripción":"A las importaciones","Naturaleza":"Haber"},
    {"Cuenta":"2460","Descripción":"Cuotas de fomento","Naturaleza":"Haber"},
    {"Cuenta":"2464","Descripción":"De licores, cervezas y cigarrillos","Naturaleza":"Haber"},
    {"Cuenta":"246405","Descripción":"De licores","Naturaleza":"Haber"},
    {"Cuenta":"246410","Descripción":"De cervezas","Naturaleza":"Haber"},
    {"Cuenta":"246415","Descripción":"De cigarrillos","Naturaleza":"Haber"},
    {"Cuenta":"2468","Descripción":"Al sacrificio de ganado","Naturaleza":"Haber"},
    {"Cuenta":"2472","Descripción":"Al azar y juegos","Naturaleza":"Haber"},
    {"Cuenta":"2476","Descripción":"Gravámenes y regalías por utilización del suelo","Naturaleza":"Haber"},
    {"Cuenta":"2495","Descripción":"Otros","Naturaleza":"Haber"},
    {"Cuenta":"25","Descripción":"Obligaciones laborales","Naturaleza":"Haber"},
    {"Cuenta":"2505","Descripción":"Salarios por pagar","Naturaleza":"Haber"},
    {"Cuenta":"2510","Descripción":"Cesantías consolidadas","Naturaleza":"Haber"},
    {"Cuenta":"251005","Descripción":"Ley laboral anterior","Naturaleza":"Haber"},
    {"Cuenta":"251010","Descripción":"Ley 50 de 1990 y normas posteriores","Naturaleza":"Haber"},
    {"Cuenta":"2515","Descripción":"Intereses sobre cesantías","Naturaleza":"Haber"},
    {"Cuenta":"2520","Descripción":"Prima de servicios","Naturaleza":"Haber"},
    {"Cuenta":"2525","Descripción":"Vacaciones consolidadas","Naturaleza":"Haber"},
    {"Cuenta":"2530","Descripción":"Prestaciones extralegales","Naturaleza":"Haber"},
    {"Cuenta":"253005","Descripción":"Primas","Naturaleza":"Haber"},
    {"Cuenta":"253010","Descripción":"Auxilios","Naturaleza":"Haber"},
    {"Cuenta":"253015","Descripción":"Dotación y suministro a trabajadores","Naturaleza":"Haber"},
    {"Cuenta":"253020","Descripción":"Bonificaciones","Naturaleza":"Haber"},
    {"Cuenta":"253025","Descripción":"Seguros","Naturaleza":"Haber"},
    {"Cuenta":"253095","Descripción":"Otras","Naturaleza":"Haber"},
    {"Cuenta":"2532","Descripción":"Pensiones por pagar","Naturaleza":"Haber"},
    {"Cuenta":"2535","Descripción":"Cuotas partes pensiones de jubilación","Naturaleza":"Haber"},
    {"Cuenta":"2540","Descripción":"Indemnizaciones laborales","Naturaleza":"Haber"},
    {"Cuenta":"26","Descripción":"Pasivos estimados y provisiones","Naturaleza":"Haber"},
    {"Cuenta":"2605","Descripción":"Para costos y gastos","Naturaleza":"Haber"},
    {"Cuenta":"260505","Descripción":"Intereses","Naturaleza":"Haber"},
    {"Cuenta":"260510","Descripción":"Comisiones","Naturaleza":"Haber"},
    {"Cuenta":"260515","Descripción":"Honorarios","Naturaleza":"Haber"},
    {"Cuenta":"260520","Descripción":"Servicios técnicos","Naturaleza":"Haber"},
    {"Cuenta":"260525","Descripción":"Transportes, fletes y acarreos","Naturaleza":"Haber"},
    {"Cuenta":"260530","Descripción":"Gastos de viaje","Naturaleza":"Haber"},
    {"Cuenta":"260535","Descripción":"Servicios públicos","Naturaleza":"Haber"},
    {"Cuenta":"260540","Descripción":"Regalías","Naturaleza":"Haber"},
    {"Cuenta":"260545","Descripción":"Garantías","Naturaleza":"Haber"},
    {"Cuenta":"260550","Descripción":"Materiales y repuestos","Naturaleza":"Haber"},
    {"Cuenta":"260595","Descripción":"Otros","Naturaleza":"Haber"},
    {"Cuenta":"2610","Descripción":"Para obligaciones laborales","Naturaleza":"Haber"},
    {"Cuenta":"261005","Descripción":"Cesantías","Naturaleza":"Haber"},
    {"Cuenta":"261010","Descripción":"Intereses sobre cesantías","Naturaleza":"Haber"},
    {"Cuenta":"261015","Descripción":"Vacaciones","Naturaleza":"Haber"},
    {"Cuenta":"261020","Descripción":"Prima de servicios","Naturaleza":"Haber"},
    {"Cuenta":"261025","Descripción":"Prestaciones extralegales","Naturaleza":"Haber"},
    {"Cuenta":"261030","Descripción":"Viáticos","Naturaleza":"Haber"},
    {"Cuenta":"261095","Descripción":"Otras","Naturaleza":"Haber"},
    {"Cuenta":"2615","Descripción":"Para obligaciones fiscales","Naturaleza":"Haber"},
    {"Cuenta":"261505","Descripción":"De renta y complementarios","Naturaleza":"Haber"},
    {"Cuenta":"261510","Descripción":"De industria y comercio","Naturaleza":"Haber"},
    {"Cuenta":"261515","Descripción":"Tasa por utilización de puertos","Naturaleza":"Haber"},
    {"Cuenta":"261520","Descripción":"De vehículos","Naturaleza":"Haber"},
    {"Cuenta":"261525","Descripción":"De hidrocarburos y minas","Naturaleza":"Haber"},
    {"Cuenta":"261595","Descripción":"Otros","Naturaleza":"Haber"},
    {"Cuenta":"2620","Descripción":"Pensiones de jubilación","Naturaleza":"Haber"},
    {"Cuenta":"262005","Descripción":"Cálculo actuarial pensiones de jubilación","Naturaleza":"Haber"},
    {"Cuenta":"262010","Descripción":"Pensiones de jubilación por amortizar (DB)","Naturaleza":"Haber"},
    {"Cuenta":"2625","Descripción":"Para obras de urbanismo","Naturaleza":"Haber"},
    {"Cuenta":"262505","Descripción":"Acueducto y alcantarillado","Naturaleza":"Haber"},
    {"Cuenta":"262510","Descripción":"Energía eléctrica","Naturaleza":"Haber"},
    {"Cuenta":"262515","Descripción":"Teléfonos","Naturaleza":"Haber"},
    {"Cuenta":"262595","Descripción":"Otros","Naturaleza":"Haber"},
    {"Cuenta":"2630","Descripción":"Para mantenimiento y reparaciones","Naturaleza":"Haber"},
    {"Cuenta":"263005","Descripción":"Terrenos","Naturaleza":"Haber"},
    {"Cuenta":"263010","Descripción":"Construcciones y edificaciones","Naturaleza":"Haber"},
    {"Cuenta":"263015","Descripción":"Maquinaria y equipo","Naturaleza":"Haber"},
    {"Cuenta":"263020","Descripción":"Equipo de oficina","Naturaleza":"Haber"},
    {"Cuenta":"263025","Descripción":"Equipo de computación y comunicación","Naturaleza":"Haber"},
    {"Cuenta":"263030","Descripción":"Equipo médico-científico","Naturaleza":"Haber"},
    {"Cuenta":"263035","Descripción":"Equipo de hoteles y restaurantes","Naturaleza":"Haber"},
    {"Cuenta":"263040","Descripción":"Flota y equipo de transporte","Naturaleza":"Haber"},
    {"Cuenta":"263045","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Haber"},
    {"Cuenta":"263050","Descripción":"Flota y equipo aéreo","Naturaleza":"Haber"},
    {"Cuenta":"263055","Descripción":"Flota y equipo férreo","Naturaleza":"Haber"},
    {"Cuenta":"263060","Descripción":"Acueductos, plantas y redes","Naturaleza":"Haber"},
    {"Cuenta":"263065","Descripción":"Armamento de vigilancia","Naturaleza":"Haber"},
    {"Cuenta":"263070","Descripción":"Envases y empaques","Naturaleza":"Haber"},
    {"Cuenta":"263075","Descripción":"Plantaciones agrícolas y forestales","Naturaleza":"Haber"},
    {"Cuenta":"263080","Descripción":"Vías de comunicación","Naturaleza":"Haber"},
    {"Cuenta":"263085","Descripción":"Pozos artesianos","Naturaleza":"Haber"},
    {"Cuenta":"263095","Descripción":"Otros","Naturaleza":"Haber"},
    {"Cuenta":"2635","Descripción":"Para contingencias","Naturaleza":"Haber"},
    {"Cuenta":"263505","Descripción":"Multas y sanciones autoridades administrativas","Naturaleza":"Haber"},
    {"Cuenta":"263510","Descripción":"Intereses por multas y sanciones","Naturaleza":"Haber"},
    {"Cuenta":"263515","Descripción":"Reclamos","Naturaleza":"Haber"},
    {"Cuenta":"263520","Descripción":"Laborales","Naturaleza":"Haber"},
    {"Cuenta":"263525","Descripción":"Civiles","Naturaleza":"Haber"},
    {"Cuenta":"263530","Descripción":"Penales","Naturaleza":"Haber"},
    {"Cuenta":"263535","Descripción":"Administrativos","Naturaleza":"Haber"},
    {"Cuenta":"263540","Descripción":"Comerciales","Naturaleza":"Haber"},
    {"Cuenta":"263595","Descripción":"Otras","Naturaleza":"Haber"},
    {"Cuenta":"2640","Descripción":"Para obligaciones de garantías","Naturaleza":"Haber"},
    {"Cuenta":"2695","Descripción":"Provisiones diversas","Naturaleza":"Haber"},
    {"Cuenta":"269505","Descripción":"Para beneficencia","Naturaleza":"Haber"},
    {"Cuenta":"269510","Descripción":"Para comunicaciones","Naturaleza":"Haber"},
    {"Cuenta":"269515","Descripción":"Para pérdida en transporte","Naturaleza":"Haber"},
    {"Cuenta":"269520","Descripción":"Para operación","Naturaleza":"Haber"},
    {"Cuenta":"269525","Descripción":"Para protección de bienes agotables","Naturaleza":"Haber"},
    {"Cuenta":"269530","Descripción":"Para ajustes en redención de unidades","Naturaleza":"Haber"},
    {"Cuenta":"269535","Descripción":"Autoseguro","Naturaleza":"Haber"},
    {"Cuenta":"269540","Descripción":"Planes y programas de reforestación y electrificación","Naturaleza":"Haber"},
    {"Cuenta":"269595","Descripción":"Otras","Naturaleza":"Haber"},
    {"Cuenta":"27","Descripción":"Diferidos","Naturaleza":"Haber"},
    {"Cuenta":"2705","Descripción":"Ingresos recibidos por anticipado","Naturaleza":"Haber"},
    {"Cuenta":"270505","Descripción":"Intereses","Naturaleza":"Haber"},
    {"Cuenta":"270510","Descripción":"Comisiones","Naturaleza":"Haber"},
    {"Cuenta":"270515","Descripción":"Arrendamientos","Naturaleza":"Haber"},
    {"Cuenta":"270520","Descripción":"Honorarios","Naturaleza":"Haber"},
    {"Cuenta":"270525","Descripción":"Servicios técnicos","Naturaleza":"Haber"},
    {"Cuenta":"270530","Descripción":"De suscriptores","Naturaleza":"Haber"},
    {"Cuenta":"270535","Descripción":"Transportes, fletes y acarreos","Naturaleza":"Haber"},
    {"Cuenta":"270540","Descripción":"Mercancía en tránsito ya vendida","Naturaleza":"Haber"},
    {"Cuenta":"270545","Descripción":"Matrículas y pensiones","Naturaleza":"Haber"},
    {"Cuenta":"270550","Descripción":"Cuotas de administración","Naturaleza":"Haber"},
    {"Cuenta":"270595","Descripción":"Otros","Naturaleza":"Haber"},
    {"Cuenta":"2710","Descripción":"Abonos diferidos","Naturaleza":"Haber"},
    {"Cuenta":"271005","Descripción":"Reajuste del sistema","Naturaleza":"Haber"},
    {"Cuenta":"2715","Descripción":"Utilidad diferida en ventas a plazos","Naturaleza":"Haber"},
    {"Cuenta":"2720","Descripción":"Crédito por corrección monetaria diferida","Naturaleza":"Haber"},
    {"Cuenta":"2725","Descripción":"Impuestos diferidos","Naturaleza":"Haber"},
    {"Cuenta":"272505","Descripción":"Por depreciación flexible","Naturaleza":"Haber"},
    {"Cuenta":"272595","Descripción":"Diversos","Naturaleza":"Haber"},
    {"Cuenta":"272599","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"28","Descripción":"Otros pasivos","Naturaleza":"Haber"},
    {"Cuenta":"2805","Descripción":"Anticipos y avances recibidos","Naturaleza":"Haber"},
    {"Cuenta":"280505","Descripción":"De clientes","Naturaleza":"Haber"},
    {"Cuenta":"280510","Descripción":"Sobre contratos","Naturaleza":"Haber"},
    {"Cuenta":"280515","Descripción":"Para obras en proceso","Naturaleza":"Haber"},
    {"Cuenta":"280595","Descripción":"Otros","Naturaleza":"Haber"},
    {"Cuenta":"2810","Descripción":"Depósitos recibidos","Naturaleza":"Haber"},
    {"Cuenta":"281005","Descripción":"Para futura suscripción de acciones","Naturaleza":"Haber"},
    {"Cuenta":"281010","Descripción":"Para futuro pago de cuotas o derechos sociales","Naturaleza":"Haber"},
    {"Cuenta":"281015","Descripción":"Para garantía en la prestación de servicios","Naturaleza":"Haber"},
    {"Cuenta":"281020","Descripción":"Para garantía de contratos","Naturaleza":"Haber"},
    {"Cuenta":"281025","Descripción":"De licitaciones","Naturaleza":"Haber"},
    {"Cuenta":"281030","Descripción":"De manejo de bienes","Naturaleza":"Haber"},
    {"Cuenta":"281035","Descripción":"Fondo de reserva","Naturaleza":"Haber"},
    {"Cuenta":"281095","Descripción":"Otros","Naturaleza":"Haber"},
    {"Cuenta":"2815","Descripción":"Ingresos recibidos para terceros","Naturaleza":"Haber"},
    {"Cuenta":"281505","Descripción":"Valores recibidos para terceros","Naturaleza":"Haber"},
    {"Cuenta":"281510","Descripción":"Venta por cuenta de terceros","Naturaleza":"Haber"},
    {"Cuenta":"2820","Descripción":"Cuentas de operación conjunta","Naturaleza":"Haber"},
    {"Cuenta":"2825","Descripción":"Retenciones a terceros sobre contratos","Naturaleza":"Haber"},
    {"Cuenta":"282505","Descripción":"Cumplimiento obligaciones laborales","Naturaleza":"Haber"},
    {"Cuenta":"282510","Descripción":"Para estabilidad de obra","Naturaleza":"Haber"},
    {"Cuenta":"282515","Descripción":"Garantía cumplimiento de contratos","Naturaleza":"Haber"},
    {"Cuenta":"2830","Descripción":"Embargos judiciales","Naturaleza":"Haber"},
    {"Cuenta":"283005","Descripción":"Indemnizaciones","Naturaleza":"Haber"},
    {"Cuenta":"283010","Descripción":"Depósitos judiciales","Naturaleza":"Haber"},
    {"Cuenta":"2835","Descripción":"Acreedores del sistema","Naturaleza":"Haber"},
    {"Cuenta":"283505","Descripción":"Cuotas netas","Naturaleza":"Haber"},
    {"Cuenta":"283510","Descripción":"Grupos en formación","Naturaleza":"Haber"},
    {"Cuenta":"2840","Descripción":"Cuentas en participación","Naturaleza":"Haber"},
    {"Cuenta":"2895","Descripción":"Diversos","Naturaleza":"Haber"},
    {"Cuenta":"289505","Descripción":"Préstamos de productos","Naturaleza":"Haber"},
    {"Cuenta":"289510","Descripción":"Reembolso de costos exploratorios","Naturaleza":"Haber"},
    {"Cuenta":"289515","Descripción":"Programa de extensión agropecuaria","Naturaleza":"Haber"},
    {"Cuenta":"29","Descripción":"Bonos y papeles comerciales","Naturaleza":"Haber"},
    {"Cuenta":"2905","Descripción":"Bonos en circulación","Naturaleza":"Haber"},
    {"Cuenta":"2910","Descripción":"Bonos obligatoriamente convertibles en acciones","Naturaleza":"Haber"},
    {"Cuenta":"2915","Descripción":"Papeles comerciales","Naturaleza":"Haber"},
    {"Cuenta":"2920","Descripción":"Bonos pensionales","Naturaleza":"Haber"},
    {"Cuenta":"292005","Descripción":"Valor bonos pensionales","Naturaleza":"Haber"},
    {"Cuenta":"292010","Descripción":"Bonos pensionales por amortizar (DB)","Naturaleza":"Haber"},
    {"Cuenta":"292015","Descripción":"Intereses causados sobre bonos pensionales","Naturaleza":"Haber"},
    {"Cuenta":"2925","Descripción":"Títulos pensionales","Naturaleza":"Haber"},
    {"Cuenta":"292505","Descripción":"Valor títulos pensionales","Naturaleza":"Haber"},
    {"Cuenta":"292510","Descripción":"Títulos pensionales por amortizar (DB)","Naturaleza":"Haber"},
    {"Cuenta":"292515","Descripción":"Intereses causados sobre títulos pensionales","Naturaleza":"Haber"},
]