export const Patrimonios = [
    {"Cuenta":"3","Descripción":"Patrimonio","Naturaleza":"Haber"},
    {"Cuenta":"31","Descripción":"Capital social","Naturaleza":"Haber"},
    {"Cuenta":"3105","Descripción":"Capital suscrito y pagado","Naturaleza":"Haber"},
    {"Cuenta":"310505","Descripción":"Capital autorizado","Naturaleza":"Haber"},
    {"Cuenta":"310510","Descripción":"Capital por suscribir (DB)","Naturaleza":"Haber"},
    {"Cuenta":"310515","Descripción":"Capital suscrito por cobrar (DB)","Naturaleza":"Haber"},
    {"Cuenta":"3115","Descripción":"Aportes sociales","Naturaleza":"Haber"},
    {"Cuenta":"311505","Descripción":"Cuotas o partes de interés social","Naturaleza":"Haber"},
    {"Cuenta":"311510","Descripción":"Aportes de socios-fondo mutuo de inversión","Naturaleza":"Haber"},
    {"Cuenta":"311515","Descripción":"Contribución de la empresa-fondo mutuo de inversión","Naturaleza":"Haber"},
    {"Cuenta":"311520","Descripción":"Suscripciones del público","Naturaleza":"Haber"},
    {"Cuenta":"3120","Descripción":"Capital asignado","Naturaleza":"Haber"},
    {"Cuenta":"3125","Descripción":"Inversión suplementaria al capital asignado","Naturaleza":"Haber"},
    {"Cuenta":"3130","Descripción":"Capital de personas naturales","Naturaleza":"Haber"},
    {"Cuenta":"3135","Descripción":"Aportes del Estado","Naturaleza":"Haber"},
    {"Cuenta":"3140","Descripción":"Fondo social","Naturaleza":"Haber"},
    {"Cuenta":"32","Descripción":"Superávit de capital","Naturaleza":"Haber"},
    {"Cuenta":"3205","Descripción":"Prima en colocación de acciones, cuotas o partes de interés social","Naturaleza":"Haber"},
    {"Cuenta":"320505","Descripción":"Prima en colocación de acciones","Naturaleza":"Haber"},
    {"Cuenta":"320510","Descripción":"Prima en colocación de acciones por cobrar (DB)","Naturaleza":"Haber"},
    {"Cuenta":"320515","Descripción":"Prima en colocación de cuotas o partes de interés social","Naturaleza":"Haber"},
    {"Cuenta":"3210","Descripción":"Donaciones","Naturaleza":"Haber"},
    {"Cuenta":"321005","Descripción":"En dinero","Naturaleza":"Haber"},
    {"Cuenta":"321010","Descripción":"En valores mobiliarios","Naturaleza":"Haber"},
    {"Cuenta":"321015","Descripción":"En bienes muebles","Naturaleza":"Haber"},
    {"Cuenta":"321020","Descripción":"En bienes inmuebles","Naturaleza":"Haber"},
    {"Cuenta":"321025","Descripción":"En intangibles","Naturaleza":"Haber"},
    {"Cuenta":"3215","Descripción":"Crédito mercantil","Naturaleza":"Haber"},
    {"Cuenta":"3220","Descripción":"Know how","Naturaleza":"Haber"},
    {"Cuenta":"3225","Descripción":"Superávit método de participación","Naturaleza":"Haber"},
    {"Cuenta":"322505","Descripción":"De acciones","Naturaleza":"Haber"},
    {"Cuenta":"322510","Descripción":"De cuotas o partes de interés social","Naturaleza":"Haber"},
    {"Cuenta":"33","Descripción":"Reservas","Naturaleza":"Haber"},
    {"Cuenta":"3305","Descripción":"Reservas obligatorias","Naturaleza":"Haber"},
    {"Cuenta":"330505","Descripción":"Reserva legal","Naturaleza":"Haber"},
    {"Cuenta":"330510","Descripción":"Reservas por disposiciones fiscales","Naturaleza":"Haber"},
    {"Cuenta":"330515","Descripción":"Reserva para readquisición de acciones","Naturaleza":"Haber"},
    {"Cuenta":"330516","Descripción":"Acciones propias readquiridas (DB)","Naturaleza":"Haber"},
    {"Cuenta":"330517","Descripción":"Reserva para readquisición de cuotas o partes de interés social","Naturaleza":"Haber"},
    {"Cuenta":"330518","Descripción":"Cuotas o partes de interés social propias readquiridas (DB)","Naturaleza":"Haber"},
    {"Cuenta":"330520","Descripción":"Reserva para extensión agropecuaria","Naturaleza":"Haber"},
    {"Cuenta":"330525","Descripción":"Reserva Ley 7ª de 1990","Naturaleza":"Haber"},
    {"Cuenta":"330530","Descripción":"Reserva para reposición de semovientes","Naturaleza":"Haber"},
    {"Cuenta":"330535","Descripción":"Reserva Ley 4ª de 1980","Naturaleza":"Haber"},
    {"Cuenta":"330595","Descripción":"Otras","Naturaleza":"Haber"},
    {"Cuenta":"3310","Descripción":"Reservas estatutarias","Naturaleza":"Haber"},
    {"Cuenta":"331005","Descripción":"Para futuras capitalizaciones","Naturaleza":"Haber"},
    {"Cuenta":"331010","Descripción":"Para reposición de activos","Naturaleza":"Haber"},
    {"Cuenta":"331015","Descripción":"Para futuros ensanches","Naturaleza":"Haber"},
    {"Cuenta":"331095","Descripción":"Otras","Naturaleza":"Haber"},
    {"Cuenta":"3315","Descripción":"Reservas ocasionales","Naturaleza":"Haber"},
    {"Cuenta":"331505","Descripción":"Para beneficencia y civismo","Naturaleza":"Haber"},
    {"Cuenta":"331510","Descripción":"Para futuras capitalizaciones","Naturaleza":"Haber"},
    {"Cuenta":"331515","Descripción":"Para futuros ensanches","Naturaleza":"Haber"},
    {"Cuenta":"331520","Descripción":"Para adquisición o reposición de propiedades, planta y equipo","Naturaleza":"Haber"},
    {"Cuenta":"331525","Descripción":"Para investigaciones y desarrollo","Naturaleza":"Haber"},
    {"Cuenta":"331530","Descripción":"Para fomento económico","Naturaleza":"Haber"},
    {"Cuenta":"331535","Descripción":"Para capital de trabajo","Naturaleza":"Haber"},
    {"Cuenta":"331540","Descripción":"Para estabilización de rendimientos","Naturaleza":"Haber"},
    {"Cuenta":"331545","Descripción":"A disposición del máximo órgano social","Naturaleza":"Haber"},
    {"Cuenta":"331595","Descripción":"Otras","Naturaleza":"Haber"},
    {"Cuenta":"34","Descripción":"Revalorización del patrimonio","Naturaleza":"Haber"},
    {"Cuenta":"3405","Descripción":"Ajustes por inflación","Naturaleza":"Haber"},
    {"Cuenta":"340505","Descripción":"De capital social","Naturaleza":"Haber"},
    {"Cuenta":"340510","Descripción":"De superávit de capital","Naturaleza":"Haber"},
    {"Cuenta":"340515","Descripción":"De reservas","Naturaleza":"Haber"},
    {"Cuenta":"340520","Descripción":"De resultados de ejercicios anteriores","Naturaleza":"Haber"},
    {"Cuenta":"340525","Descripción":"De activos en período improductivo","Naturaleza":"Haber"},
    {"Cuenta":"340530","Descripción":"De saneamiento fiscal","Naturaleza":"Haber"},
    {"Cuenta":"340535","Descripción":"De ajustes Decreto 3019 de 1989","Naturaleza":"Haber"},
    {"Cuenta":"340540","Descripción":"De dividendos y participaciones decretadas en acciones, cuotas o partes de interés social","Naturaleza":"Haber"},
    {"Cuenta":"340545","Descripción":"Superávit método de participación","Naturaleza":"Haber"},
    {"Cuenta":"3410","Descripción":"Saneamiento fiscal","Naturaleza":"Haber"},
    {"Cuenta":"3415","Descripción":"Ajustes por inflación Decreto 3019 de 1989","Naturaleza":"Haber"},
    {"Cuenta":"35","Descripción":"Dividendos o participaciones decretados en acciones, cuotas o partes de interés social","Naturaleza":"Haber"},       
    {"Cuenta":"3505","Descripción":"Dividendos decretados en acciones","Naturaleza":"Haber"},
    {"Cuenta":"3510","Descripción":"Participaciones decretadas en cuotas o partes de interés social","Naturaleza":"Haber"},
    {"Cuenta":"36","Descripción":"Resultados del ejercicio","Naturaleza":"Haber"},
    {"Cuenta":"3605","Descripción":"Utilidad del ejercicio","Naturaleza":"Haber"},
    {"Cuenta":"3610","Descripción":"Pérdida del ejercicio","Naturaleza":"Haber"},
    {"Cuenta":"37","Descripción":"Resultados de ejercicios anteriores","Naturaleza":"Haber"},
    {"Cuenta":"3705","Descripción":"Utilidades acumuladas","Naturaleza":"Haber"},
    {"Cuenta":"3710","Descripción":"Pérdidas acumuladas","Naturaleza":"Haber"},
    {"Cuenta":"38","Descripción":"Superávit por valorizaciones","Naturaleza":"Haber"},
    {"Cuenta":"3805","Descripción":"De inversiones","Naturaleza":"Haber"},
    {"Cuenta":"380505","Descripción":"Acciones","Naturaleza":"Haber"},
    {"Cuenta":"380510","Descripción":"Cuotas o partes de interés social","Naturaleza":"Haber"},
    {"Cuenta":"380515","Descripción":"Derechos fiduciarios","Naturaleza":"Haber"},
    {"Cuenta":"3810","Descripción":"De propiedades, planta y equipo","Naturaleza":"Haber"},
    {"Cuenta":"381004","Descripción":"Terrenos","Naturaleza":"Haber"},
    {"Cuenta":"381006","Descripción":"Materiales proyectos petroleros","Naturaleza":"Haber"},
    {"Cuenta":"381008","Descripción":"Construcciones y edificaciones","Naturaleza":"Haber"},
    {"Cuenta":"381012","Descripción":"Maquinaria y equipo","Naturaleza":"Haber"},
    {"Cuenta":"381016","Descripción":"Equipo de oficina","Naturaleza":"Haber"},
    {"Cuenta":"381020","Descripción":"Equipo de computación y comunicación","Naturaleza":"Haber"},
    {"Cuenta":"381024","Descripción":"Equipo médico-científico","Naturaleza":"Haber"},
    {"Cuenta":"381028","Descripción":"Equipo de hoteles y restaurantes","Naturaleza":"Haber"},
    {"Cuenta":"381032","Descripción":"Flota y equipo de transporte","Naturaleza":"Haber"},
    {"Cuenta":"381036","Descripción":"Flota y equipo fluvial y/o marítimo","Naturaleza":"Haber"},
    {"Cuenta":"381040","Descripción":"Flota y equipo aéreo","Naturaleza":"Haber"},
    {"Cuenta":"381044","Descripción":"Flota y equipo férreo","Naturaleza":"Haber"},
    {"Cuenta":"381048","Descripción":"Acueductos, plantas y redes","Naturaleza":"Haber"},
    {"Cuenta":"381052","Descripción":"Armamento de vigilancia","Naturaleza":"Haber"},
    {"Cuenta":"381056","Descripción":"Envases y empaques","Naturaleza":"Haber"},
    {"Cuenta":"381060","Descripción":"Plantaciones agrícolas y forestales","Naturaleza":"Haber"},
    {"Cuenta":"381064","Descripción":"Vías de comunicación","Naturaleza":"Haber"},
    {"Cuenta":"381068","Descripción":"Minas y canteras","Naturaleza":"Haber"},
    {"Cuenta":"381072","Descripción":"Pozos artesianos","Naturaleza":"Haber"},
    {"Cuenta":"381076","Descripción":"Yacimientos","Naturaleza":"Haber"},
    {"Cuenta":"381080","Descripción":"Semovientes","Naturaleza":"Haber"},
    {"Cuenta":"3895","Descripción":"De otros activos","Naturaleza":"Haber"},
    {"Cuenta":"389505","Descripción":"Bienes de arte y cultura","Naturaleza":"Haber"},
    {"Cuenta":"389510","Descripción":"Bienes entregados en comodato","Naturaleza":"Haber"},
    {"Cuenta":"389515","Descripción":"Bienes recibidos en pago","Naturaleza":"Haber"},
    {"Cuenta":"389520","Descripción":"Inventario de semovientes","Naturaleza":"Haber"},
]